### ISSUE TITLE
Browser-Phone installation instructions for a web server

### ISSUE THREAD

**Issue by vhatzist** [InnovateAsterisk/Browser-Phone#100]
Hello Conrad,

Up to now we have been testing the hosted version of Browser-Phone. Are there instructions on how to install it on any web server so that it can be used from a web site?

**Comment by vhatzist** [comment]
Perhaps serving the Phone directory from the web server would be enough?

**Comment by InnovateAsterisk** [comment]
Yes, just clone the project to your web server, its pretty much good to go as is. Although I would make your own index page and configure the phone the way you would want it. You may also want to host your own dependancy files.

**Comment by vhatzist** [comment]
Thank you Conrad!
