### ISSUE TITLE
keepAlive settings don't seem to work

### ISSUE THREAD

**Issue by pravin-navle** [InnovateAsterisk/Browser-Phone#101]
First of all thanks a lot for the wonderful project. I have been using it in the production environment recently with Asterisk at the backend. Sometimes when there is a network fluctuation, the Asterisk marks the extension as Unreachable. We don't get to know this as the Browser-Phone still shows the status as Registered. Due to this, the calls also don't connect. 
So to temporarily solve the problem we refresh the page and the extension get's registered.
So to notify the user that the extension is unreachable, I tried to dig into SIPJs documentation and they have mentioned transportOptions settings like keepAliveInterval and keepAliveDebounce. 

So I have added the below lines 
 keepAliveInterval: 2,
 keepAliveDebounce: 5

 to the CreateUserAgent function :

`    try {
        console.log("Creating User Agent...");
        userAgent = new SIP.UA({
            displayName: profileName,
            uri: SipUsername + "@" + wssServer,
            transportOptions: {
                wsServers: "wss://" + wssServer + ":" + WebSocketPort + "" + ServerPath,
                traceSip: false,
                connectionTimeout: TransportConnectionTimeout,
                maxReconnectionAttempts: TransportReconnectionAttempts,
                reconnectionTimeout: TransportReconnectionTimeout,
                keepAliveInterval: 2,
                keepAliveDebounce: 5
            },
            authorizationUser: SipUsername,
            password: SipPassword,
            registerExpires: RegisterExpires,
            hackWssInTransport: WssInTransport,
            hackIpInContact: IpInContact,
            userAgentString: userAgentStr,
            autostart: false,
            register: false,
        });
        console.log("Creating User Agent... Done");
    }`

To start the keepAlive internal they have mentioned to use the startSendingKeepAlives() transport instance method.
So I'm calling transport.startSendingKeepAlives(); instance method inside this code 

`        transport.on('connected', function() {
            console.log("Connected to Web Socket!");
            $("#regStatus").html(lang.connected_to_web_socket);
            transport.startSendingKeepAlives();
            $("#WebRtcFailed").hide();
            // Auto start register
            Register(); 
        });`

But this doesn't seem to work when the network is disconnected/fluctuates.

I digged further and found that we have to create the transport constructor. So I added this code `transportConstructor: SIP.Transport`  to the CreateUserAgent function:

`userAgent = new SIP.UA({
            displayName: profileName,
            uri: SipUsername + "@" + wssServer,
            transportConstructor: SIP.Transport,
            transportOptions: {
                wsServers: "wss://" + wssServer + ":" + WebSocketPort + "" + ServerPath,
                traceSip: false,
                connectionTimeout: TransportConnectionTimeout,
                maxReconnectionAttempts: TransportReconnectionAttempts,
                reconnectionTimeout: TransportReconnectionTimeout,
                keepAliveInterval: 5,
                keepAliveDebounce: 10
            },
            authorizationUser: SipUsername,
            password: SipPassword,
            registerExpires: RegisterExpires,
            hackWssInTransport: WssInTransport,
            hackIpInContact: IpInContact,
            userAgentString: userAgentStr,
            autostart: false,
            register: false,
        });`

But this causes sipjs to thrown an error.
 Uncaught TypeError: Cannot read property 'then' of undefined
    at t.value (sip-0.11.6.min.js:formatted:97)
    at r.start (sip-0.11.6.min.js:formatted:4517)
    at CreateUserAgent (phone.js:2034)
![image](https://user-images.githubusercontent.com/26799986/94798935-fb254680-03ff-11eb-9fea-4c2a434ece70.png)

All I want to do is detect network fluctuation and show a refresh button to the user asterisk marks the extension as unreachable as early as possible to the user.

Any help regarding the keepAlive setting or anything similar and how to integrate it in phone.js will be very useful. 

Thanks

**Comment by InnovateAsterisk** [comment]
Well, there could be a a rather simple solution, the default registration expires is 300 seconds, and can be made lower using the db variable RegisterExpires. Setting this to 120 or even 60 would make the phone re-register every 120 or 60 seconds. Even tho this will not fix any network issues, it will reduce the gap between the issue, and the phone re-registering, and being available again. 

I realise that there are a number of keep-alive options,  but from my experience keep-alive only helps if your NATing router closes connections that don't have packets within their timeout period. Even with this, the Asterisk Qualify setting is easier to implement. (It makes Asterisk send an OPTIONS message every X seconds)

The other thing to remember is that if your internet is having network fluctuation to such a point that the extensions de-register... you may want to look at that, as this will probably effect call quality.

**Comment by pravin-navle** [comment]
Thank you so much for the tips. I'll definitely implement this.

**Comment by InnovateAsterisk** [comment]
https://github.com/InnovateAsterisk/Browser-Phone/commit/7a6dd82a1bf69c84a11e9a41236b07819d2b6128
