### ISSUE TITLE
registration Expired and Abrupt socket disconnection after that.

### ISSUE THREAD

**Issue by pravin-navle** [InnovateAsterisk/Browser-Phone#105]
Hello, Sometimes we face this issue where the registration gets expired and after that, all the registration attempts fail. Then after some time, the Websocket abrupt disconnection error is printed and then the sip js gets reconnected successfully after that.
This issue is rare and happens sometimes. We also tried to ping our WebSocket server. The ping was pretty good at 2ms without any packet loss.
Can you please help me figure out what is the issue and how we should debug it?
Please check the attached images. 
![1](https://user-images.githubusercontent.com/26799986/96573683-22c74a80-12ec-11eb-80a6-8d24e9c0d4bc.png)
![2](https://user-images.githubusercontent.com/26799986/96573691-2529a480-12ec-11eb-9084-f22ed8475fff.png)

**Comment by InnovateAsterisk** [comment]
Well, the first issue is; why is the phone registration expiring? - the disconnects etc seems to be as a results of that first, so let's make sure the phone can stay registered. The only reason i can think of that a phone registration expires, is that Asterisk and the phone cannot agree on the expire. The phone will send a expire=300 (this can also be set) in the register but its important that your Asterisk (or whatever SIP server) can honour this expire. Sometimes servers are set to "override" this expires, or they have a "max expires" please make sure neither of these are in use (or are the same as the phone).

Also make sure that there are no routers or proxies that can expire these connections (remember its a persistent wss connection), some routers don't like this. Make sure qualify is ON, and set to something about 60 seconds - or lower than your NAT connection timeout in any case. There is no reason for Asterisk to close the WebSocket connection if you have it setup like this. As far as I know, on the browser side the web socket is simply never closed unless explicitly told to do so.

In testing I have had my browser phone registered for almost an entire day without being de-registered, it only re-registers every 300 seconds, to keep the registration open.

**Comment by pravin-navle** [comment]
Thanks a lot for the detailed explanation that you have given. Will implement this.
