### ISSUE TITLE
INVALID_STATE_ERROR with status code 5

### ISSUE THREAD

**Issue by pravin-navle** [InnovateAsterisk/Browser-Phone#107]
Hello. Sometimes I encounter this sip js error. It is very rare. When this happens it appears like two calls are running at the same time. In my setup, I have auto-answer enabled. Please see the image below.
![image](https://user-images.githubusercontent.com/26799986/97066476-7f1fb800-15d3-11eb-85fc-3fcea0a0ca28.png)

In the above image, we can see Line 1 and Line 2 but from these 2 lines, only Line 2 call is actually running. Line 1 was cancelled by customer end but it failed to get removed from the Ui side. I'm also sharing the log below for both the calls.
From the below log please help me to what exactly has happened and how can the line which is already got terminated be removed from the Ui side. i tried to remove the lines from the terminated, cancel, rejected events but this doesn't seem to be a good solution to me and might fail sometimes. Please help me to understand this log and solution is possible here.

sip-0.11.6.min.V1.js:1 Fri Oct 23 2020 16:05:27 GMT+0530 (India Standard Time) | sip.sipmessage | header "Content-Disposition" not present
sip-0.11.6.min.V1.js:1 Fri Oct 23 2020 16:05:27 GMT+0530 (India Standard Time) | sip.dialog | new UAS dialog created with status EARLY
New Incoming Call! "1234567" <1234567>
CurrentCalls - undefined
CurrentCalls - 0
SUBSCRIBE: 1234567@domain.com
Selecting Buddy: 16034493278492276
Auto Answer Call...
Auto Answer audio Calling ...
Audio  ...
Audio Is Playing Done ...
Selecting Line : 1
sip-0.11.6.min.V1.js:1 Fri Oct 23 2020 16:05:28 GMT+0530 (India Standard Time) | sip.dialog | dialog 191a6b0904b455701b8cb2a3737ce480@192.168.34.35:5060dc733hmgifas7bc2d46d changed to CONFIRMED state
sip-0.11.6.min.V1.js:1 Fri Oct 23 2020 16:05:28 GMT+0530 (India Standard Time) | sip.invitecontext.sessionDescriptionHandler | SessionDescriptionHandlerOptions: {"constraints":{},"peerConnectionOptions":{"iceCheckingTimeout":5000,"rtcConfiguration":{"iceServers":[]}}}
sip-0.11.6.min.V1.js:1 Fri Oct 23 2020 16:05:28 GMT+0530 (India Standard Time) | sip.invitecontext.sessionDescriptionHandler | initPeerConnection
sip-0.11.6.min.V1.js:1 Fri Oct 23 2020 16:05:28 GMT+0530 (India Standard Time) | sip.invitecontext.sessionDescriptionHandler | New peer connection created
Selecting Buddy: 16034493278492276
phone.html:91 web_hook_on_invite s
web_hook_on_invite @ phone.html:91
sip-0.11.6.min.V1.js:1 Fri Oct 23 2020 16:05:28 GMT+0530 (India Standard Time) | sip.invitecontext.sessionDescriptionHandler | closing PeerConnection
**Call Cancelled**
New CDR Object
Last Activity is now: 2020-10-23 10:35:28 UTC
phone.html:103 web_hook_on_terminate s
web_hook_on_terminate @ phone.html:103
Call rejected: Canceled
New CDR Object
Last Activity is now: 2020-10-23 10:35:29 UTC
phone.html:103 web_hook_on_terminate s
web_hook_on_terminate @ phone.html:103
Call rejected: Canceled
Call failed: Canceled
sip-0.11.6.min.V1.js:1 Fri Oct 23 2020 16:05:29 GMT+0530 (India Standard Time) | sip.inviteservercontext | closing INVITE session 191a6b0904b455701b8cb2a3737ce480@192.168.34.35:5060as7bc2d46d
sip-0.11.6.min.V1.js:1 Fri Oct 23 2020 16:05:29 GMT+0530 (India Standard Time) | sip.invitecontext.sessionDescriptionHandler | closing PeerConnection
sip-0.11.6.min.V1.js:1 Fri Oct 23 2020 16:05:29 GMT+0530 (India Standard Time) | sip.dialog | dialog 191a6b0904b455701b8cb2a3737ce480@192.168.34.35:5060dc733hmgifas7bc2d46d deleted
Call to close any open window
Call terminated
Session terminated **// No Closing Line 1 printed after this.**
sip-0.11.6.min.V1.js:1 Fri Oct 23 2020 16:05:29 GMT+0530 (India Standard Time) | sip.sipmessage | header "Content-Disposition" not present
sip-0.11.6.min.V1.js:1 Fri Oct 23 2020 16:05:29 GMT+0530 (India Standard Time) | sip.dialog | new UAS dialog created with status EARLY
New Incoming Call! "4747474747" <4747474747> //second call landed here without removing Line 1 from the Ui
CurrentCalls - undefined
CurrentCalls - 0
SUBSCRIBE: 4747474747@domain.com
Selecting Buddy: 160344933000227D
Auto Answer Call...
Auto Answer audio Calling ...
Audio  ...
Audio Is Playing Done ...
Selecting Line : 2
sip-0.11.6.min.V1.js:1 Fri Oct 23 2020 16:05:30 GMT+0530 (India Standard Time) | sip.dialog | dialog 74568ec7612266fa5c793c2712f5a9d8@192.168.34.35:50606qeol406vjas75c64095 changed to CONFIRMED state
sip-0.11.6.min.V1.js:1 Fri Oct 23 2020 16:05:30 GMT+0530 (India Standard Time) | sip.invitecontext.sessionDescriptionHandler | SessionDescriptionHandlerOptions: {"constraints":{},"peerConnectionOptions":{"iceCheckingTimeout":5000,"rtcConfiguration":{"iceServers":[]}}}
sip-0.11.6.min.V1.js:1 Fri Oct 23 2020 16:05:30 GMT+0530 (India Standard Time) | sip.invitecontext.sessionDescriptionHandler | initPeerConnection
sip-0.11.6.min.V1.js:1 Fri Oct 23 2020 16:05:30 GMT+0530 (India Standard Time) | sip.invitecontext.sessionDescriptionHandler | New peer connection created
Selecting Buddy: 160344933000227D
phone.html:91 web_hook_on_invite s
web_hook_on_invite @ phone.html:91
Putting an active call on hold: Line: 2 buddy: 160344933000227D
**sip-0.11.6.min.V1.js:1 Uncaught ecode: 2message: "Invalid status: 5"name: "INVALID_STATE_ERROR"status: 5__proto__: Error
    at https://domain.com/lib/SipJS/sip-0.11.6.min.V1.js:1:17185
    at Object.<anonymous> (https://domain.com/lib/SipJS/sip-0.11.6.min.V1.js:1:17197)
    at i (https://domain.com/lib/SipJS/sip-0.11.6.min.V1.js:1:319)
    at e.exports (https://domain.com/lib/SipJS/sip-0.11.6.min.V1.js:1:2788)
    at Object.<anonymous> (https://domain.com/lib/SipJS/sip-0.11.6.min.V1.js:1:2485)
    at i (https://domain.com/lib/SipJS/sip-0.11.6.min.V1.js:1:319)
    at https://domain.com/lib/SipJS/sip-0.11.6.min.V1.js:1:1118
    at https://domain.com/lib/SipJS/sip-0.11.6.min.V1.js:1:1127
    at https://domain.com/lib/SipJS/sip-0.11.6.min.V1.js:1:183
    at https://domain.com/lib/SipJS/sip-0.11.6.min.V1.js:1:187**
**//The above is what I'm unable to understand like it is regarding which call and what exactly happened here.**
sip-0.11.6.min.V1.js:1 Fri Oct 23 2020 16:05:30 GMT+0530 (India Standard Time) | sip.invitecontext.sessionDescriptionHandler | track added
phone.html:97 web_hook_on_modify trackAdded s
web_hook_on_modify @ phone.html:97
sip-0.11.6.min.V1.js:1 Fri Oct 23 2020 16:05:30 GMT+0530 (India Standard Time) | sip.invitecontext.sessionDescriptionHandler | acquiring local media
Audio Is Playing  ...
sinkId applied: default
Audio Is Playing  ...
phone.html:97 web_hook_on_modify trackAdded s
web_hook_on_modify @ phone.html:97
sip-0.11.6.min.V1.js:1 Fri Oct 23 2020 16:05:30 GMT+0530 (India Standard Time) | sip.invitecontext.sessionDescriptionHandler | acquired local media streams
sinkId applied: default
sip-0.11.6.min.V1.js:1 Fri Oct 23 2020 16:05:30 GMT+0530 (India Standard Time) | sip.invitecontext.sessionDescriptionHandler | RTCIceGatheringState changed: gathering
sip-0.11.6.min.V1.js:1 Fri Oct 23 2020 16:05:30 GMT+0530 (India Standard Time) | sip.invitecontext.sessionDescriptionHandler | ICE candidate received: candidate:2276718763 1 udp 2122260223 172.18.1.111 44163 typ host generation 0 ufrag Z/fO network-id 1
sip-0.11.6.min.V1.js:1 Fri Oct 23 2020 16:05:30 GMT+0530 (India Standard Time) | sip.invitecontext.sessionDescriptionHandler | RTCIceGatheringState changed: complete
 Direction Change:  sendrecv
phone.html:97 web_hook_on_modify directionChanged s
web_hook_on_modify @ phone.html:97
Creating LocalAudio AudioContext on line 2
Adding Track to Monitor:  Default
SoundMeter connecting...
SoundMeter for LocalAudio Connected, displaying levels for Line: 2
Creating RemoteAudio AudioContext on Line:2
SoundMeter connecting...
SoundMeter for RemoteAudio Connected, displaying levels for Line: 2
phone.html:97 web_hook_on_modify accepted s
web_hook_on_modify @ phone.html:97
sip-0.11.6.min.V1.js:1 Fri Oct 23 2020 16:05:31 GMT+0530 (India Standard Time) | sip.invitecontext.sessionDescriptionHandler | ICE candidate gathering complete
Object
Object
Registered!
phone.html:82 web_hook_on_register r
web_hook_on_register @ phone.html:82
Selecting Line : 2
Putting Call on hold: 2
Direction Change:  sendonly
phone.html:97 web_hook_on_modify directionChanged s
web_hook_on_modify @ phone.html:97
Taking call off hold: 2
Direction Change:  sendrecv
phone.html:97 web_hook_on_modify directionChanged s
web_hook_on_modify @ phone.html:97
sip-0.11.6.min.V1.js:1 Fri Oct 23 2020 16:12:29 GMT+0530 (India Standard Time) | sip.invitecontext.sessionDescriptionHandler | track added
phone.html:97 web_hook_on_modify trackAdded s
web_hook_on_modify @ phone.html:97
sinkId applied: default
Call ended, bye!
Disconnecting SoundMeter...
New CDR Object
Last Activity is now: 2020-10-23 10:43:05 UTC
phone.html:103 web_hook_on_terminate s
web_hook_on_terminate @ phone.html:103
sip-0.11.6.min.V1.js:1 Fri Oct 23 2020 16:13:06 GMT+0530 (India Standard Time) | sip.inviteservercontext | closing INVITE session 74568ec7612266fa5c793c2712f5a9d8@192.168.34.35:5060as75c64095
sip-0.11.6.min.V1.js:1 Fri Oct 23 2020 16:13:06 GMT+0530 (India Standard Time) | sip.invitecontext.sessionDescriptionHandler | closing PeerConnection
sip-0.11.6.min.V1.js:1 Fri Oct 23 2020 16:13:06 GMT+0530 (India Standard Time) | sip.dialog | dialog 74568ec7612266fa5c793c2712f5a9d8@192.168.34.35:50606qeol406vjas75c64095 deleted
Call to close any open window
Call terminated
Session terminated
**IndexDB connected to CallQosData (also  this event not triggered for Line 1)
Call CallQos Sucess: 74568ec7612266fa5c793c2712f5a9d8@192.168.34.35:5060as75c64095 (also  this event not triggered for Line 1)
Closing Line: 2 (also  this event not triggered for Line 1) **
Selecting previously selected buddy... 160344933000227D
Selecting Buddy: 160344933000227D

**Comment by InnovateAsterisk** [comment]
I believe the "INVALID_STATE_ERROR" is when the session is not in the correct state for the method, for example, this happens when you try send a bye, before answering a line.

I'll double check the states, and send an update. It would help to know the line numbers so i can trace the state error.

**Comment by InnovateAsterisk** [comment]
https://github.com/InnovateAsterisk/Browser-Phone/commit/7a6dd82a1bf69c84a11e9a41236b07819d2b6128
