### ISSUE TITLE
trunk calling no ring or ivr

### ISSUE THREAD

**Issue by casualcodex** [InnovateAsterisk/Browser-Phone#109]
Hi Conrad, hope you are well and safe! When I try to place a call over outbound trunk I cannot hear any ring tone or if the phone is switched off the ivr does not play on the app. Is there any way to fix this? If I make the same call over zoiper, both ring and ivrplayback is relayed

**Comment by casualcodex** [comment]
I checked your code, you have a condition based on some responses to playback the local ring,busy files . 

 // Provisional 1xx
        if(response.status_code == 100){
            $(MessageObjId).html(lang.trying);
        } else if(response.status_code == 180){
            $(MessageObjId).html(lang.ringing);

== 100 is good, it indicates that it's trying to establish a connection. 

but continuing after is whre this start to get trickier. == 180 ,you ring via local file, which is also good in normal occasions . But in real life, 183 session is sent almost all the time and it might contain media (usually operator generated IVR messages) 

So I'm trying to figure out how ; if 183 is sent before 180, how to play attached media(invalid number,mobile switched off,person is busy...etc)  If I change the code to ring on 183 response, it will always ring no matter what respıonse comes after(486,487,480...etc) , just like giving fake ring back , or running asterisk dial with,R option. You input is highly appreciated. 

Kind Regards,
casualx

**Comment by InnovateAsterisk** [comment]
Hmm, yes, this used to be in placed, but i took it out, as I thought it would be a cleaner approach to have the system always play it own remote ring tone. There seems to be a lot of disparity around this topic, and so in the end i just forced it, but let me see if i can make a user option for this.

**Comment by casualcodex** [comment]
Hello Conrad, hope you are doing well! can you point me to the exact line responsible for dealing with this? Maybe give me a hint so I can try to play around with the code and see if I can get this to actually work?

**Comment by InnovateAsterisk** [comment]
Do you have a SIP trace of a typical call (best is form chrome devtools ws message console)?

**Comment by casualcodex** [comment]
something like this perhaps ? 

INVITE sip:05328196642@192.168.1.120 SIP/2.0
Via: SIP/2.0/WSS 192.0.2.101;branch=z9hG4bK6449942
Max-Forwards: 70
To: <sip:05328196642@192.168.1.120>
From: "4000" <sip:4000@192.168.1.120>;tag=tctn8ea3uo
Call-ID: 63vihqpb71dt1fv5lgcd
CSeq: 9855 INVITE
Contact: <sip:9nrf1h4t@192.0.2.101;transport=wss;ob>
Allow: ACK,CANCEL,INVITE,MESSAGE,BYE,OPTIONS,INFO,NOTIFY,REFER
Supported: 100rel, outbound
User-Agent: Browser Phone
Content-Type: application/sdp
Content-Length: 2439

v=0
o=- 789428192590246152 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE 0
a=msid-semantic: WMS wIx5Aw2jOWkBTkviNokJd3AdPjoNJK6m6sp8
m=audio 57240 UDP/TLS/RTP/SAVPF 111 103 104 9 0 8 106 105 13 110 112 113 126
c=IN IP4 94.55.170.280
a=rtcp:9 IN IP4 0.0.0.0
a=candidate:3458083907 1 udp 2122260223 192.168.81.1 57238 typ host generation 0 network-id 1
a=candidate:409348628 1 udp 2122194687 192.168.5.1 57239 typ host generation 0 network-id 2
a=candidate:3659473419 1 udp 2122129151 192.168.0.14 57240 typ host generation 0 network-id 3 network-cost 10
a=candidate:2157826227 1 tcp 1518280447 192.168.81.1 9 typ host tcptype active generation 0 network-id 1
a=candidate:1457903332 1 tcp 1518214911 192.168.5.1 9 typ host tcptype active generation 0 network-id 2
a=candidate:2493308667 1 tcp 1518149375 192.168.0.14 9 typ host tcptype active generation 0 network-id 3 network-cost 10
a=candidate:739204063 1 udp 1685921535 94.55.170.280 57240 typ srflx raddr 192.168.0.14 rport 57240 generation 0 network-id 3 network-cost 10
a=ice-ufrag:3SDw
a=ice-pwd:sWmdik9fktjSHSJLsynFl3oz
a=ice-options:trickle
a=fingerprint:sha-256 E7:FC:8A:3D:AF:1E:4F:41:3F:61:C8:61:24:C4:79:C4:D1:64:24:82:8A:99:B6:CD:9C:06:3C:07:D0:F9:88:CF
a=setup:actpass
a=mid:0
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid
a=extmap:5 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id
a=extmap:6 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id
a=sendrecv
a=msid:wIx5Aw2jOWkBTkviNokJd3AdPjoNJK6m6sp8 f002558e-bbbc-4a11-9673-b2b832619842
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptime=10;useinbandfec=1
a=rtpmap:103 ISAC/16000
a=rtpmap:104 ISAC/32000
a=rtpmap:9 G722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:106 CN/32000
a=rtpmap:105 CN/16000
a=rtpmap:13 CN/8000
a=rtpmap:110 telephone-event/48000
a=rtpmap:112 telephone-event/32000
a=rtpmap:113 telephone-event/16000
a=rtpmap:126 telephone-event/8000
a=ssrc:1964699779 cname:n3t57dNDGc0PGRRD
a=ssrc:1964699779 msid:wIx5Aw2jOWkBTkviNokJd3AdPjoNJK6m6sp8 f002558e-bbbc-4a11-9673-b2b832619842
a=ssrc:1964699779 mslabel:wIx5Aw2jOWkBTkviNokJd3AdPjoNJK6m6sp8
a=ssrc:1964699779 label:f002558e-bbbc-4a11-9673-b2b832619842


sip-0.11.6.min.js:1 Mon Dec 14 2020 22:14:22 GMT+0300 (GMT+03:00) | sip.transport | received WebSocket text message:

SIP/2.0 401 Unauthorized
Via: SIP/2.0/WSS 192.0.2.101;rport=56724;received=94.55.170.280;branch=z9hG4bK6449942
Call-ID: 63vihqpb71dt1fv5lgcd
From: "4000" <sip:4000@192.168.1.120>;tag=tctn8ea3uo
To: <sip:05328196642@192.168.1.120>;tag=z9hG4bK6449942
CSeq: 9855 INVITE
WWW-Authenticate: Digest realm="asterisk",nonce="1607973261/2807f8e71a3a754de326d6fd591e53be",opaque="2ccc3a7d731b5c63",algorithm=md5,qop="auth"
Server: Asterisk PBX 17.7.0
Content-Length:  0



sip-0.11.6.min.js:1 Mon Dec 14 2020 22:14:22 GMT+0300 (GMT+03:00) | sip.transport | sending WebSocket message:

ACK sip:05328196642@192.168.1.120 SIP/2.0
Via: SIP/2.0/WSS 192.0.2.101;branch=z9hG4bK3197319
Max-Forwards: 70
To: <sip:05328196642@192.168.1.120>;tag=z9hG4bK6449942
From: "4000" <sip:4000@192.168.1.120>;tag=tctn8ea3uo
Call-ID: 63vihqpb71dt1fv5lgcd
CSeq: 9855 ACK
Supported: 100rel, outbound
User-Agent: Browser Phone
Content-Length: 0



sip-0.11.6.min.js:1 Mon Dec 14 2020 22:14:22 GMT+0300 (GMT+03:00) | sip.transport | sending WebSocket message:

INVITE sip:05328196642@192.168.1.120 SIP/2.0
Via: SIP/2.0/WSS 192.0.2.101;branch=z9hG4bK92425
Max-Forwards: 70
To: <sip:05328196642@192.168.1.120>
From: "4000" <sip:4000@192.168.1.120>;tag=tctn8ea3uo
Call-ID: 63vihqpb71dt1fv5lgcd
CSeq: 9856 INVITE
Authorization: Digest algorithm=MD5, username="4000", realm="asterisk", nonce="1607973261/2807f8e71a3a754de326d6fd591e53be", uri="sip:05328196642@192.168.1.120", response="2e96a363661008dc03af9d54536655bb", opaque="2ccc3a7d731b5c63", qop=auth, cnonce="vfbd2loc6977", nc=00000001
Contact: <sip:9nrf1h4t@192.0.2.101;transport=wss;ob>
Allow: ACK,CANCEL,INVITE,MESSAGE,BYE,OPTIONS,INFO,NOTIFY,REFER
Supported: 100rel, outbound
User-Agent: Browser Phone
Content-Type: application/sdp
Content-Length: 2439

v=0
o=- 789428192590246152 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE 0
a=msid-semantic: WMS wIx5Aw2jOWkBTkviNokJd3AdPjoNJK6m6sp8
m=audio 57240 UDP/TLS/RTP/SAVPF 111 103 104 9 0 8 106 105 13 110 112 113 126
c=IN IP4 94.55.170.280
a=rtcp:9 IN IP4 0.0.0.0
a=candidate:3458083907 1 udp 2122260223 192.168.81.1 57238 typ host generation 0 network-id 1
a=candidate:409348628 1 udp 2122194687 192.168.5.1 57239 typ host generation 0 network-id 2
a=candidate:3659473419 1 udp 2122129151 192.168.0.14 57240 typ host generation 0 network-id 3 network-cost 10
a=candidate:2157826227 1 tcp 1518280447 192.168.81.1 9 typ host tcptype active generation 0 network-id 1
a=candidate:1457903332 1 tcp 1518214911 192.168.5.1 9 typ host tcptype active generation 0 network-id 2
a=candidate:2493308667 1 tcp 1518149375 192.168.0.14 9 typ host tcptype active generation 0 network-id 3 network-cost 10
a=candidate:739204063 1 udp 1685921535 94.55.170.280 57240 typ srflx raddr 192.168.0.14 rport 57240 generation 0 network-id 3 network-cost 10
a=ice-ufrag:3SDw
a=ice-pwd:sWmdik9fktjSHSJLsynFl3oz
a=ice-options:trickle
a=fingerprint:sha-256 E7:FC:8A:3D:AF:1E:4F:41:3F:61:C8:61:24:C4:79:C4:D1:64:24:82:8A:99:B6:CD:9C:06:3C:07:D0:F9:88:CF
a=setup:actpass
a=mid:0
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid
a=extmap:5 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id
a=extmap:6 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id
a=sendrecv
a=msid:wIx5Aw2jOWkBTkviNokJd3AdPjoNJK6m6sp8 f002558e-bbbc-4a11-9673-b2b832619842
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptime=10;useinbandfec=1
a=rtpmap:103 ISAC/16000
a=rtpmap:104 ISAC/32000
a=rtpmap:9 G722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:106 CN/32000
a=rtpmap:105 CN/16000
a=rtpmap:13 CN/8000
a=rtpmap:110 telephone-event/48000
a=rtpmap:112 telephone-event/32000
a=rtpmap:113 telephone-event/16000
a=rtpmap:126 telephone-event/8000
a=ssrc:1964699779 cname:n3t57dNDGc0PGRRD
a=ssrc:1964699779 msid:wIx5Aw2jOWkBTkviNokJd3AdPjoNJK6m6sp8 f002558e-bbbc-4a11-9673-b2b832619842
a=ssrc:1964699779 mslabel:wIx5Aw2jOWkBTkviNokJd3AdPjoNJK6m6sp8
a=ssrc:1964699779 label:f002558e-bbbc-4a11-9673-b2b832619842


sip-0.11.6.min.js:1 Mon Dec 14 2020 22:14:22 GMT+0300 (GMT+03:00) | sip.transport | received WebSocket text message:

SIP/2.0 100 Trying
Via: SIP/2.0/WSS 192.0.2.101;rport=56724;received=94.55.170.280;branch=z9hG4bK92425
Call-ID: 63vihqpb71dt1fv5lgcd
From: "4000" <sip:4000@192.168.1.120>;tag=tctn8ea3uo
To: <sip:05328196642@192.168.1.120>
CSeq: 9856 INVITE
Server: Asterisk PBX 17.7.0
Content-Length:  0



(index):59 web_hook_on_modify progress r {passedOptions: {…}, sessionDescriptionHandlerFactoryOptions: {…}, sessionDescriptionHandlerOptions: {…}, modifiers: {…}, inviteWithoutSdp: false, …}
web_hook_on_modify @ (index):59
(anonymous) @ phone.js:2361
i.emit @ sip-0.11.6.min.js:1
value @ sip-0.11.6.min.js:1
receiveResponse @ sip-0.11.6.min.js:1
r.receiveResponse @ sip-0.11.6.min.js:1
r.onTransportReceiveMsg @ sip-0.11.6.min.js:1
i.emit @ sip-0.11.6.min.js:1
value @ sip-0.11.6.min.js:1
sip-0.11.6.min.js:1 Mon Dec 14 2020 22:14:22 GMT+0300 (GMT+03:00) | sip.transport | received WebSocket text message:

SIP/2.0 183 Session Progress
Via: SIP/2.0/WSS 192.0.2.101;rport=56724;received=94.55.170.280;branch=z9hG4bK92425
Call-ID: 63vihqpb71dt1fv5lgcd
From: "4000" <sip:4000@192.168.1.120>;tag=tctn8ea3uo
To: <sip:05328196642@192.168.1.120>;tag=e3e33e01-ec5a-46ab-a99a-93feedce793f
CSeq: 9856 INVITE
Server: Asterisk PBX 17.7.0
Contact: <sip:192.168.1.120:8089;transport=ws>
Allow: OPTIONS, REGISTER, SUBSCRIBE, NOTIFY, PUBLISH, INVITE, ACK, BYE, CANCEL, UPDATE, PRACK, MESSAGE, REFER
Content-Type: application/sdp
Content-Length:   827

v=0
o=- 855978248 4 IN IP4 192.168.1.120
s=Asterisk
c=IN IP4 192.168.1.120
t=0 0
a=msid-semantic:WMS *
a=group:BUNDLE 0
m=audio 12402 UDP/TLS/RTP/SAVPF 9 0 8 126
a=connection:new
a=setup:active
a=fingerprint:SHA-256 86:55:27:D2:FA:07:68:B8:27:FA:F3:D1:CB:77:CF:1F:3D:2F:40:B3:D8:E2:DF:68:CC:BE:1B:8F:DE:83:B4:E9
a=ice-ufrag:4fbaf4be039ecc966d34ab3438023e36
a=ice-pwd:125bbfaf4ec0b63e0df1dc893c0a275f
a=candidate:H334d4379 1 UDP 2130706431 192.168.1.120 12402 typ host
a=rtpmap:9 G722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:126 telephone-event/8000
a=fmtp:126 0-16
a=ptime:20
a=maxptime:150
a=sendrecv
a=rtcp-mux
a=ssrc:657703977 cname:631ff323-ffd3-4a55-803f-bcfbef776d28
a=msid:e8367692-0ce6-45b7-ad8c-e82483bbc3ed 16ddfbb6-0627-49db-b5ca-09a4ec8f314f
a=rtcp-fb:* transport-cc
a=mid:0


sip-0.11.6.min.js:1 Mon Dec 14 2020 22:14:22 GMT+0300 (GMT+03:00) | sip.dialog | new UAC dialog created with status EARLY
(index):59 web_hook_on_modify progress r {passedOptions: {…}, sessionDescriptionHandlerFactoryOptions: {…}, sessionDescriptionHandlerOptions: {…}, modifiers: {…}, inviteWithoutSdp: false, …}
web_hook_on_modify @ (index):59
(anonymous) @ phone.js:2361
i.emit @ sip-0.11.6.min.js:1
value @ sip-0.11.6.min.js:1
receiveResponse @ sip-0.11.6.min.js:1
r.receiveResponse @ sip-0.11.6.min.js:1
r.onTransportReceiveMsg @ sip-0.11.6.min.js:1
i.emit @ sip-0.11.6.min.js:1
value @ sip-0.11.6.min.js:1
sip-0.11.6.min.js:1 Mon Dec 14 2020 22:14:22 GMT+0300 (GMT+03:00) | sip.transport | received WebSocket text message:

SIP/2.0 183 Session Progress
Via: SIP/2.0/WSS 192.0.2.101;rport=56724;received=94.55.170.280;branch=z9hG4bK92425
Call-ID: 63vihqpb71dt1fv5lgcd
From: "4000" <sip:4000@192.168.1.120>;tag=tctn8ea3uo
To: <sip:05328196642@192.168.1.120>;tag=e3e33e01-ec5a-46ab-a99a-93feedce793f
CSeq: 9856 INVITE
Server: Asterisk PBX 17.7.0
Allow: OPTIONS, REGISTER, SUBSCRIBE, NOTIFY, PUBLISH, INVITE, ACK, BYE, CANCEL, UPDATE, PRACK, MESSAGE, REFER
Contact: <sip:192.168.1.120:8089;transport=ws>
Content-Type: application/sdp
Content-Length:   827

v=0
o=- 855978248 4 IN IP4 192.168.1.120
s=Asterisk
c=IN IP4 192.168.1.120
t=0 0
a=msid-semantic:WMS *
a=group:BUNDLE 0
m=audio 12402 UDP/TLS/RTP/SAVPF 9 0 8 126
a=connection:new
a=setup:active
a=fingerprint:SHA-256 86:55:27:D2:FA:07:68:B8:27:FA:F3:D1:CB:77:CF:1F:3D:2F:40:B3:D8:E2:DF:68:CC:BE:1B:8F:DE:83:B4:E9
a=ice-ufrag:4fbaf4be039ecc966d34ab3438023e36
a=ice-pwd:125bbfaf4ec0b63e0df1dc893c0a275f
a=candidate:H334d4379 1 UDP 2130706431 192.168.1.120 12402 typ host
a=rtpmap:9 G722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:126 telephone-event/8000
a=fmtp:126 0-16
a=ptime:20
a=maxptime:150
a=sendrecv
a=rtcp-mux
a=ssrc:657703977 cname:631ff323-ffd3-4a55-803f-bcfbef776d28
a=msid:e8367692-0ce6-45b7-ad8c-e82483bbc3ed 16ddfbb6-0627-49db-b5ca-09a4ec8f314f
a=rtcp-fb:* transport-cc
a=mid:0


2sip-0.11.6.min.js:1 Mon Dec 14 2020 22:14:23 GMT+0300 (GMT+03:00) | sip.transport | received WebSocket text message:

SIP/2.0 183 Session Progress
Via: SIP/2.0/WSS 192.0.2.101;rport=56724;received=94.55.170.280;branch=z9hG4bK92425
Call-ID: 63vihqpb71dt1fv5lgcd
From: "4000" <sip:4000@192.168.1.120>;tag=tctn8ea3uo
To: <sip:05328196642@192.168.1.120>;tag=e3e33e01-ec5a-46ab-a99a-93feedce793f
CSeq: 9856 INVITE
Server: Asterisk PBX 17.7.0
Allow: OPTIONS, REGISTER, SUBSCRIBE, NOTIFY, PUBLISH, INVITE, ACK, BYE, CANCEL, UPDATE, PRACK, MESSAGE, REFER
Contact: <sip:192.168.1.120:8089;transport=ws>
Content-Type: application/sdp
Content-Length:   827

v=0
o=- 855978248 4 IN IP4 192.168.1.120
s=Asterisk
c=IN IP4 192.168.1.120
t=0 0
a=msid-semantic:WMS *
a=group:BUNDLE 0
m=audio 12402 UDP/TLS/RTP/SAVPF 9 0 8 126
a=connection:new
a=setup:active
a=fingerprint:SHA-256 86:55:27:D2:FA:07:68:B8:27:FA:F3:D1:CB:77:CF:1F:3D:2F:40:B3:D8:E2:DF:68:CC:BE:1B:8F:DE:83:B4:E9
a=ice-ufrag:4fbaf4be039ecc966d34ab3438023e36
a=ice-pwd:125bbfaf4ec0b63e0df1dc893c0a275f
a=candidate:H334d4379 1 UDP 2130706431 192.168.1.120 12402 typ host
a=rtpmap:9 G722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:126 telephone-event/8000
a=fmtp:126 0-16
a=ptime:20
a=maxptime:150
a=sendrecv
a=rtcp-mux
a=ssrc:657703977 cname:631ff323-ffd3-4a55-803f-bcfbef776d28
a=msid:e8367692-0ce6-45b7-ad8c-e82483bbc3ed 16ddfbb6-0627-49db-b5ca-09a4ec8f314f
a=rtcp-fb:* transport-cc
a=mid:0


sip-0.11.6.min.js:1 Mon Dec 14 2020 22:14:26 GMT+0300 (GMT+03:00) | sip.transport | received WebSocket text message:

SIP/2.0 486 Busy Here
Via: SIP/2.0/WSS 192.0.2.101;rport=56724;received=94.55.170.280;branch=z9hG4bK92425
Call-ID: 63vihqpb71dt1fv5lgcd
From: "4000" <sip:4000@192.168.1.120>;tag=tctn8ea3uo
To: <sip:05328196642@192.168.1.120>;tag=e3e33e01-ec5a-46ab-a99a-93feedce793f
CSeq: 9856 INVITE
Server: Asterisk PBX 17.7.0
Allow: OPTIONS, REGISTER, SUBSCRIBE, NOTIFY, PUBLISH, INVITE, ACK, BYE, CANCEL, UPDATE, PRACK, MESSAGE, REFER
Reason: Q.850;cause=17
Content-Length:  0



sip-0.11.6.min.js:1 Mon Dec 14 2020 22:14:26 GMT+0300 (GMT+03:00) | sip.transport | sending WebSocket message:

ACK sip:05328196642@192.168.1.120 SIP/2.0
Via: SIP/2.0/WSS 192.0.2.101;branch=z9hG4bK2706996
Max-Forwards: 70
To: <sip:05328196642@192.168.1.120>;tag=e3e33e01-ec5a-46ab-a99a-93feedce793f
From: "4000" <sip:4000@192.168.1.120>;tag=tctn8ea3uo
Call-ID: 63vihqpb71dt1fv5lgcd
CSeq: 9856 ACK
Supported: 100rel, outbound
User-Agent: Browser Phone
Content-Length: 0



phone.js:2429 Call rejected: Busy
phone.js:4279 486(Busy Here)
phone.js:4333 New CDR {CdrId: "160797326641848D", ItemType: "CDR", ItemDate: "2020-12-14 19:14:21 UTC", CallAnswer: null, CallEnd: "2020-12-14 19:14:26 UTC", …}
phone.js:4518 Last Activity is now: 2020-12-14 19:14:26 UTC
(index):65 web_hook_on_terminate r {passedOptions: {…}, sessionDescriptionHandlerFactoryOptions: {…}, sessionDescriptionHandlerOptions: {…}, modifiers: {…}, inviteWithoutSdp: false, …}
web_hook_on_terminate @ (index):65
teardownSession @ phone.js:2760
(anonymous) @ phone.js:2430
i.emit @ sip-0.11.6.min.js:1
rejected @ sip-0.11.6.min.js:1
value @ sip-0.11.6.min.js:1
receiveResponse @ sip-0.11.6.min.js:1
r.receiveResponse @ sip-0.11.6.min.js:1
r.onTransportReceiveMsg @ sip-0.11.6.min.js:1
i.emit @ sip-0.11.6.min.js:1
value @ sip-0.11.6.min.js:1
phone.js:2434 Call failed: Busy
sip-0.11.6.min.js:1 Mon Dec 14 2020 22:14:26 GMT+0300 (GMT+03:00) | sip.inviteclientcontext | closing INVITE session 63vihqpb71dt1fv5lgcdtctn8ea3uo
sip-0.11.6.min.js:1 Mon Dec 14 2020 22:14:26 GMT+0300 (GMT+03:00) | sip.invitecontext.sessionDescriptionHandler | closing PeerConnection
sip-0.11.6.min.js:1 Mon Dec 14 2020 22:14:26 GMT+0300 (GMT+03:00) | sip.dialog | dialog 63vihqpb71dt1fv5lgcdtctn8ea3uoe3e33e01-ec5a-46ab-a99a-93feedce793f deleted
phone.js:2450 Session terminated
phone.js:7043 Closing Line: 1
phone.js:7026 Selecting previously selected buddy... 160795258576413B4
phone.js:7733 Selecting Buddy: 160795258576413B4

**Comment by InnovateAsterisk** [comment]
Your sequence is as follows:
==> INVITE sip:05328196642@192.168.1.120 SIP/2.0
<== SIP/2.0 401 Unauthorized
<== ACK sip:05328196642@192.168.1.120 SIP/2.0
==> INVITE sip:05328196642@192.168.1.120 SIP/2.0 <-- (with auth)
==> SIP/2.0 100 Trying
==> SIP/2.0 183 Session Progress
==> SIP/2.0 183 Session Progress
==> SIP/2.0 486 Busy Here
<== ACK sip:05328196642@192.168.1.120 SIP/2.0

You will see that the **180 Ringing** never arrives from the Asterisk, so the Browsers Phone probably doesn't start the local EARLY media.

https://github.com/InnovateAsterisk/Browser-Phone/blob/2d964d355b2c195ae881a8e7bbefe222e085256f/Phone/phone.js#L2388

There are a few things to consider here... and this is a complex issue, some of it revolves around ICE negotiations and the ability for WebRTC to establish a connection (have full media) if this has not completed and the TLS handshakes have taken place... something that 183 Session Progress may require too soon.

The answer to this may be more simple, if you look at this logically, when a call is routed between extension, there is little logic to handle in the Asterisk dialplan, just send the call to the extension, and let the endpoint handle the SIP negotiation, however, when you trunk the call out, try this... Answer the call before you dial your SIP Trunk, this way the call will be fully established (between browser phone and asterisk) and the remote party audio from the trunk will flow back to the browser phone, even if this is an IVR or the Beeb Beeb tone generated.

**Comment by InnovateAsterisk** [comment]
https://github.com/InnovateAsterisk/Browser-Phone/commit/7a6dd82a1bf69c84a11e9a41236b07819d2b6128
