### ISSUE TITLE
missing language strings

### ISSUE THREAD

**Issue by vieridipaola** [InnovateAsterisk/Browser-Phone#111]
Hi,

There are two strings that should be localized:

https://github.com/InnovateAsterisk/Browser-Phone/blob/2d964d355b2c195ae881a8e7bbefe222e085256f/Phone/phone.js#L8501

Thanks

**Comment by InnovateAsterisk** [comment]
https://github.com/InnovateAsterisk/Browser-Phone/commit/7a6dd82a1bf69c84a11e9a41236b07819d2b6128
