### ISSUE TITLE
ICE failure: no audio

### ISSUE THREAD

**Issue by vieridipaola** [InnovateAsterisk/Browser-Phone#116]
Hi,

I've bumped into one situation where I can call a remote Browser-Phone without issues, but if the remote party initiates the call (eg. to my Browser-Phone) then no one hears anything after the call is established.

The remote Browser-Phone's console shows this error message:

`WebRTC: ICE failed, add a TURN server and see about:webrtc for more details`

I didn't have the chance to check about:webrtc (Firefox), but maybe someone knows what's going on.
Correct me if I'm wrong, but SIPjs uses Google's ICE TURN servers by default, right?

On a server I installed and configured my own TURN server with:
https://github.com/coturn/coturn
I successfully used it once with another webrtc application, but never with Browser-Phone.

In the meantime however, I asked the remote user to reboot the WAN device and the calls started working fine again (no ICE errors and no audio issues).
I guess that if this is a home router firewall/firmware issue then it would come back up again even if I were to configure Browser-Phone to use my coturn service.

Any experience in this field?

**Comment by vieridipaola** [comment]
How would I specify more than one TURN or STUN server?

In phone.js, function CreateUserAgent() contains:

```
                    iceCheckingTimeout: IceStunCheckTimeout,
                    rtcConfiguration: {.
                        iceServers : [
                            { urls: IceStunServerProtocol + ":"+ IceStunServerAddress +":"+ IceStunServerPort }
                        ]
                    }
```

The problem is that some turn servers may require credentials and it seems to be implemented to pass just one URL.
I'm not an expert but it may be something of this kind:

```
                    iceServers : {
                                [
									{ urls: IceStunServerProtocol + ":"+ IceStunServerAddress + ":" + IceStunServerPort, username: IceStunServerUsername, credential: IceStunServerPassword }
								]
                    }
```
					
For more than one server I don't know what would be best for "setItem".

**Comment by vieridipaola** [comment]
I also noticed that phone.js sets the timeout to 500 ms by default:

`var IceStunCheckTimeout = parseInt(getDbItem("IceStunCheckTimeout", 500));`

Isn't that too short?
Looking at the SIPjs doc, it seems that the default is 5000 ms. Could it be a typo in phone.js?

**Comment by InnovateAsterisk** [comment]
ICE, STUN, and TURN, sure is a messy business, and making this setting compatible with everyone's settings sounds like it may need to be a custom json string. It's fine, ill do that.

Another thing you can try is to make sure the media always flows "through" the Asterisk box, (directmedia=no), this way the asterisk box is always the destination of the media, and this would be by way of the same LIVE ip that you are registering with, so it would always be reachable even if that IP was natting into your hosted box.

I may say tho, if STUN is failing to return the live IP address, there are probably more pressing issues to resolve, and by the time you are relying on TURN to make the magic happen you are quite far down a rabbit hole... something this project/app wasn't really designed for.

**Comment by vieridipaola** [comment]
I use pjsip_wizard, and I defined this regarding directmedia:

```
endpoint/direct_media = yes
endpoint/disable_direct_media_on_nat = yes
endpoint/direct_media_method = invite
```

Would you suggest changing direct_media to 'no' even though disable_direct_media_on_nat is 'yes'?

In the meantime I explicitly set the IceStunCheckTimeout to 10000 ms instead of the phone.js default of 500.

Changing the customization of iceServers to a json string is more flexible and simpler to maintain.

Thanks

**Comment by InnovateAsterisk** [comment]
> Would you suggest changing direct_media to 'no' even though disable_direct_media_on_nat is 'yes'?

Asterisk by default will try to stay out of the media path, this is mainly to free up resource and to eliminate would could be an extra hop, however I have found this always to be less useful, and besides as soon as you want something like call recording or transcoding, you have to be in the media path again. I have found that having Asterisk as a live reachable ip address and to never have direct media ensures that none of these media silence issues occur... and a cost?? a bit of resources... its an easy deal for me. CPU & Bandwidth is cheap problems are expensive.

Yes, if you are a Zoom, then sure you want to have the endpoints directly connect to each other, but even they have admitted that at least 40% of their traffic ends up going through their servers. I think point-to-point is a lovely dreamy idea, fill of terrible headaches. IMHO

Another thing to remember about point-to-point... they are never the same, so you cant optimise any routes. With a single point in the cloud as being your media server, both parties can ensure that they have well QOSed routes to a single IP address, and ensure perfect call quality. Point-to-point would only be able to get you to as far as your own ISP.

**Comment by vieridipaola** [comment]
Thanks for sharing your thoughts on direct media.

So, just to help sum things up before closing this issue, the requests are:

1) convert iceServers into a customizable/provisionable JSON string:

https://github.com/InnovateAsterisk/Browser-Phone/blob/2d964d355b2c195ae881a8e7bbefe222e085256f/Phone/phone.js#L1711

2) consider changing the default value of IceStunCheckTimeout to 5000 ms (or is 500 a value you consider more appropriate?):

https://github.com/InnovateAsterisk/Browser-Phone/blob/2d964d355b2c195ae881a8e7bbefe222e085256f/Phone/phone.js#L111

Thanks

**Comment by InnovateAsterisk** [comment]
https://github.com/InnovateAsterisk/Browser-Phone/commit/7a6dd82a1bf69c84a11e9a41236b07819d2b6128
