### ISSUE TITLE
contact/buddy list ordering

### ISSUE THREAD

**Issue by vieridipaola** [InnovateAsterisk/Browser-Phone#119]
Hi,

UI ordering of the contact/buddy list is done by extension/phone number, I presume.
When receiving or making calls, it would be nice to order by date (eg. most recent calls first).

**Comment by vieridipaola** [comment]
Well, after reviewing the source code it seems that phone.js is actually sorting by date... I'll have to figure out why some incoming calls (ringing but not answered) are not placed in pole position (but in 3rd or 4th).

**Comment by InnovateAsterisk** [comment]
It's a LastActivity, so if "nothing really happened" then this date object will not get updated. It gets set at various events.

If it is supposed to but doesn't, it could be a bug, or maybe "ringing" was left out.

**Comment by vieridipaola** [comment]
I think this is a specific use case, and maybe you can reproduce it .

I disable call waiting in Browser-Phone and receive a call. There's an open window ringing, as expected. The buddy is created and listed in the left panel, as expected.

However, I do not answer the call, and while it's still ringing another call comes in. It is obviously rejected as CW is disabled.

`Call Waiting Disabled, rejecting call.`

The problem now is that I also get a call to CloseWindow() as I see this in the log:

`Call to close any open window`

So, I have:

1) the auto-rejected incoming call that takes first position as it's the latest event (it's as expected)

2) the currently ringing call is still ringing, but the window has been closed and the "selected buddy" is not the right one

The end result is that the user is confused and does not know where to answer the incoming call.
It is available of course in the left panel where the buddy list is and in second position. That is unless there's another call coming in in the meantime (auto-rejected due to CW policy) -- in that case it would be in 3rd position. This can go on... :-(

So I guess a fix would be to try not to close the window in this specific case, or to auto-select the buddy/contact that is actually ringing.

**Comment by vieridipaola** [comment]
This is where it gets closed:

https://github.com/InnovateAsterisk/Browser-Phone/blob/2d964d355b2c195ae881a8e7bbefe222e085256f/Phone/phone.js#L1933

**Comment by vieridipaola** [comment]
Maybe line 1933 could be replaced with:

`if(session.data.terminateby != "us") CloseWindow();`

Any thoughts?

**Comment by vieridipaola** [comment]
The source code change I mentioned above seems to work for me. Do you think it can backfire in some other cases?

**Comment by InnovateAsterisk** [comment]
Well, the one way to think of this is that any line (call) that come into the system should be made into a full blown line, answered or not. I think you already mentioned this before. Currently the system kind of ignores any line that isn't answered yet, and you have to select the buddy, then click the answer button... however something that is scheduled for change is that all inbound sessions, answered or not get made into full blown lines, that appear above all the other contacts (in the active lines section). 

The reason this is advisable is that the call notification window has the potential to double up, if you have a ringing inbound call, and then another call comes in... something that is typically tricky to handle with windows in any case, but the notification window really should just remain there only to notify the user, and should have little to no real functionality. Any lookups, CRM information or anything else really should be placed on the call Line UI... that can be expanded, and multiple of them can exists (unlike popup windows).

You can try your solution, however further development on this will move the functionality to the Lines section.

**Comment by InnovateAsterisk** [comment]
BTW, from a timeline perspective, i'm hoping to have this and a few more other updates out by 1st quarter 2021, as well as some basic XMPP (optional) features. I've had to relocate to be closer to family, and this move is consuming a lot of my time... i'll be back full time early next year, so there will be a big push for features and updates.

**Comment by vieridipaola** [comment]
Great!
Take care.

**Comment by InnovateAsterisk** [comment]
https://github.com/InnovateAsterisk/Browser-Phone/commit/7a6dd82a1bf69c84a11e9a41236b07819d2b6128
