### ISSUE TITLE
Update js.sip  Early media problem

### ISSUE THREAD

**Issue by xgs-spain** [InnovateAsterisk/Browser-Phone#125]
First of all, thanks for the great work! Your videos and code were a great help!

I wonder if you have plans to update sip.js to the latest. I had encounter an important problem for my needs with the early media , since you cant hear the audio until the call is answered. An stupid example, my VoIP provider plays an audio saying you dont have enough credit for that call, and it took me a while to realize what was going on.

Checking sip.js documentation I could see this about the issue:

> How can I play early media (with an invite with SDP)?
> With the release of 0.16 you can now play early media on an invite with SDP and 100 rel enabled. This requires that InviterOptions.earlyMedia is set to true. At the moment, SIP.js only supports early media on an invite with SDP if the call does not fork. If your call does fork SIP.js will throw an error and the call will not connect (regardless of who answers the call). If you want to do early media with a call that forks, please use InviterOptions.inviteWithoutSdp.

Any help to update the library without breaking everything would be very much appreciated! Of course if i am pointing in the wrong direction do not hesitate to correct me. Thanks!

**Comment by InnovateAsterisk** [comment]
I'll take a look at updating to the new version.

However, this project is hardly ever used directly with an ISP, as most Voice Service Providers don't allow Websocket connections for the transport. The reason I mention this, is that if you are using say Asterisk as a box to terminate your registrations, and forward on your calls, you will have access to the dial plan, and so just Answer you calls first, then when you you send them out via the trunk, you can even use the r parameter in the Dial command, so it sounds like its ringing. This way you always have fully established 2 way audio at the start of every call.

**Comment by xgs-spain** [comment]
Thanks for your feedback!

Answering all the calls looks odd, since CDRs, messages in Browser Phone (answered, rejected, recordings, etc) will look broken. I also tried to workaround the problem adding a custom header in the 183 progress packet from Asterisk to see if i was able to detect it in Browser Phone and parametrize header with audio files, but Asterisk can not do it (only in INVITES). Probably adding Kamailio in between would be possible but seems too much and more logical to update js.sip . In addition that would only work for my own early media I generate from Asterisk, but would not help for the early media the other leg might add since we can not parametrize it.

I tried some workarounds in sip.js i found for example here [https://github.com/onsip/SIP.js/issues/211](url) but i am lost. The version used here was 0.11.6 and it is hard to find documentation previous to 0.14.0 to understand how sip.js worked back in the day.

Any help would be awesome. Thanks again for the great project!

**Comment by xgs-spain** [comment]
I am still far from saying i made it work... but looks promising! At least I can receive the early media, i have to make further test if the call gets answered after the 183 Progress.

Right after this line: $(MessageObjId).html(response.reason_phrase + "...");  I included the following code:

if (response.status_code === 183 && response.body && this.hasOffer && !this.dialog) {
                if (!response.hasHeader('require') || response.getHeader('require').indexOf('100rel') === -1) {
                  if (this.sessionDescriptionHandler.hasDescription(response.getHeader('Content-Type'))) {
                    // Mimic rel-100 behavior
                    if (!this.createDialog(response, 'UAC')) { // confirm the dialog, eventhough it's a provisional answer
                      return
                    }

                    // this ensures that 200 will not try to set description
                    this.hasAnswer = true

                    // This ensures that when you receive a 1XX after the 183, no
                    // earlyDialog are created once the dialog has been confirmed.
                    //
                    // Without this piece of code:
                    //  1. upon reception of a 1XX a new earlyDialog is created and a
                    //     PRACK is send (CSEQ is incremented in this new dialog object).
                    //  2. at some point we receive the 200.
                    //  3. when sending a SIP INFO it will use the CSEQ from the confirmed
                    //     dialog. This CSEQ was already used when sending the PRACK.
                    //     Asterisk ignores this message since it thinks it is a
                    //     retransmit.
                    this.dialog.pracked.push(response.getHeader('rseq'))

                    // This is different from the behaviour in SIP.JS. Due to concurrency
                    // issues, we need to consider that we already have STATUS_EARLY_MEDIA
                    // before actually setting the description.
                    //
                    // @hack: https://github.com/onsip/SIP.js/issues/242
                    //this.status = Session.C.STATUS_EARLY_MEDIA
                    this.status =SIP.Session.C.STATUS_EARLY_MEDIA

                    // Mute local streams since we are going to establish early media.
                    //this.mute()
                    RTCRtpSender.track.enabled = false;

                    //this.mediaHandler
                    this.sessionDescriptionHandler
                      //.setDescription(response)
                      .setDescription(response.body)
                      .catch((reason) => {
                        this.logger.warn(reason)
                        this.failed(response, C.causes.BAD_MEDIA_DESCRIPTION)
                        this.terminate({ status_code: 488, reason_phrase: 'Bad Media Description' })
                      })
                  }
                }
              }

Test it yourself and include a nice version of it hehe. I think other people might benefit from this addition!

**Comment by InnovateAsterisk** [comment]
Did you try with `Progress()`, rather than with `Answer()`

Im busy with some tests, and found that:

```
[early]
exten => s,1,NoOp(Early Media Test)
exten => s,n,Progress()
exten => s,n,Wait(2)
exten => s,n,Playback(tt-monkeys)
exten => s,n,Wait(2)
exten => s,n,Progress()
exten => s,n,Wait(2)
exten => s,n,Ringing()
exten => s,n,Wait(2)
exten => s,n,Answer()
exten => s,n,Wait(1)
exten => s,n,MusicOnHold()
```

results in:

```
=> SIP/2.0 100 Trying...
=> SIP/2.0 183 Session Progress...
=> SIP/20 200 OK... (From the Playback)
```
At this point tt-monkeys is heared, followed by 2 seconds of ring and then the music on hold (or whatever comes next)

**Comment by xgs-spain** [comment]
Thats what i do, but in the Browser-phone without the code that specifically acts when a progress is received, i cant hear audio at all.

if (response.status_code === 183 && response.body && this.hasOffer ....

Do you hear the tt-monkeys without changes on your Browser-phone??

**Comment by InnovateAsterisk** [comment]
>Do you hear the tt-monkeys without changes on your Browser-phone??

Yes, but that's probably because Asterisk is also sending the 200 OK. (I believe this is from the Playback function)

![image](https://user-images.githubusercontent.com/58937573/114863523-1f6ed080-9df0-11eb-93f3-63c9e78ab6b8.png)

If the 200 OK is not sent, then the phone does not fire the `session.on('accepted'...` code, but in there it only updates some of the UI elements, and doesn't deal with media - that's done in `session.on('trackAdded'...`. So if the session receives the track, you will get audio.

I checked the 183 Session Progress does have the SDP so is able to initialise a call. (The 200 OK also contains the SDP). 

I assume that your ISP is not going to send the 200 OK, as its not going to officially answer your call, but rather make the announcement using `183 Session Progress` that you, for example, don't have sufficient credit or whatever.  I cannot recreate this behaviour in Asterisk.

**Comment by InnovateAsterisk** [comment]
https://wiki.asterisk.org/wiki/display/AST/Early+Media+and+the+Progress+Application

Ah, i see it is possible...

**Comment by xgs-spain** [comment]
It certainly is, dont know why your asterisk is sending the answer (200) when you use playback... that is not the case for me, and this is how it should work in my opinion. If you send the answer then it is not early media at all hehe

But with my code, everything works fine after many tests. I only had problem with RTCRtpSender.track.enabled = false; (intented to mute your microphone) because some cases RTCRtpSender is undefined, so i just add a simple if and when is undefined everything works ok as well without that line.

**Comment by InnovateAsterisk** [comment]
Now that I can simulate this, I can fix it. Either it will be with a newer version of sipjs (that appears to support it natively) or with your patch.

**Comment by casualcodex** [comment]
Hello @xgs-spain , nice work. I was having the same issue and I did see this code on another post on GitHub but could not understand how to implemt it. I went for the easy solution as to answer the call before placing the outbound leg in order to hear any operator side announcements. Works ok but it also has its flaws. Each call gets logged as answers...and so on. How did you implement this, did you make any specific changes on asterisk ? Would you mind guiding me ?

Thanks in advance, Ucin

**Comment by InnovateAsterisk** [comment]
https://github.com/InnovateAsterisk/Browser-Phone/commit/7a6dd82a1bf69c84a11e9a41236b07819d2b6128
