### ISSUE TITLE
can't get user media in chrome

### ISSUE THREAD

**Issue by morteza-jamaseb** [InnovateAsterisk/Browser-Phone#127]
everything working fine in firefox but in chrome can't getUserMedia (asked permission and allowed user media) but still can't hear anything

**Comment by morteza-jamaseb** [comment]
works fine on chrome in mobile devices too.

**Comment by morteza-jamaseb** [comment]
problem was windows firewall

**Comment by parabol** [comment]
> problem was windows firewall

did you close firewall completely? or open related udp ports for
