### ISSUE TITLE
Disable Presence that happens automatically 

### ISSUE THREAD

**Issue by casualcodex** [InnovateAsterisk/Browser-Phone#130]
Hello Conrad , hope you are doing well! 

Is there a way to completely disable automatic presence request ?

**Comment by casualcodex** [comment]
Btw, I have commented out the whole block representing presence & subscription. Also somewhere else where it calls the function . I hope I did not break anything :)

**Comment by InnovateAsterisk** [comment]
After this line: 
https://github.com/InnovateAsterisk/Browser-Phone/blob/2d964d355b2c195ae881a8e7bbefe222e085256f/Phone/phone.js#L3841

return the function:
```
// Start subscribe all
return;
console.log("Starting Subscribe of all ("+ Buddies.length +") Extension Buddies...");
```

And here:
https://github.com/InnovateAsterisk/Browser-Phone/blob/2d964d355b2c195ae881a8e7bbefe222e085256f/Phone/phone.js#L3856
return the function:
```
function SubscribeBuddy(buddyObj) {
    return;
    var dialogOptions = { expires: 300, extraHeaders: ['Accept: application/pidf+xml'] }
```

Going forward buddies will have the option to subscribe.

**Comment by InnovateAsterisk** [comment]
https://github.com/InnovateAsterisk/Browser-Phone/commit/7a6dd82a1bf69c84a11e9a41236b07819d2b6128
