### ISSUE TITLE
 Spanish Language

### ISSUE THREAD

**Issue by michelhevia** [InnovateAsterisk/Browser-Phone#133]
Attached is the file es.json (as zip) for translation to Spanish (Spain)

[es.zip](https://github.com/InnovateAsterisk/Browser-Phone/files/6375602/es.zip)

**Comment by InnovateAsterisk** [comment]
Thank you, I have included this file, but will only merge it with the master when i release next.

**Comment by InnovateAsterisk** [comment]
https://github.com/InnovateAsterisk/Browser-Phone/commit/7a6dd82a1bf69c84a11e9a41236b07819d2b6128
