### ISSUE TITLE
Incoming call notification

### ISSUE THREAD

**Issue by HSMM** [InnovateAsterisk/Browser-Phone#137]
Can i receive notification to the notification center in windows 10?
For example
![image](https://user-images.githubusercontent.com/56293541/119229843-6c963e80-bb22-11eb-9a0b-9f84effbc758.png)

**Comment by InnovateAsterisk** [comment]
I have not seen this before - I use Mac OS. I'll take a look at this.

**Comment by HSMM** [comment]
I have a problem with notification work. The notification does not work in Windows 10.
Notifications in browser settings are allowed.
![image](https://user-images.githubusercontent.com/56293541/122405172-804d8d00-cf88-11eb-99d9-4be427cb692c.png)
Made a notification check for Linux and MacOS - works well

**Comment by InnovateAsterisk** [comment]
I believe Notifications are only possible under secure context.
