### ISSUE TITLE
conference audio or video call

### ISSUE THREAD

**Issue by edimondi** [InnovateAsterisk/Browser-Phone#145]
hi, i wanted to know if there is a way to make a conference audio or video call with 3 or more people .thanks

**Comment by InnovateAsterisk** [comment]
This is not currently in place, but I'm busy with it. 

In the mean while, you can try using the 3 way audio conference feature. This allows you, during a call, to bring a 3rd party into the call, the browser phone then bridges the conversation 3 ways, and you can all talk. This is not a feature with video.

The current conferencing development will be more along the lines of Zoom/Teams/Jitsi etc

**Comment by edimondi** [comment]
i do not have any conference audio button, do i need to make any configuration to show up the conference button?

**Comment by InnovateAsterisk** [comment]
It looks like that was disabled by default in an update... not a problem just look for:

EnableConference: https://github.com/InnovateAsterisk/Browser-Phone/blob/5dd6ce5efbc2565f613dee7b5a129d9c4107e031/Phone/phone.js#L121

Either set it to 1 or do your own database set for 1

```let EnableConference = (getDbItem("EnableConference", "1") == "1");```

**Comment by edimondi** [comment]
Thank you it works now, i really appreciate it
