### ISSUE TITLE
error on chrome IOS

### ISSUE THREAD

**Issue by adrehmanforunity** [InnovateAsterisk/Browser-Phone#155]
It's working well over windows

whereas it's not working on IOS with Chrome, it feels like something is wrong where code is collecting information related to resources and "Audio/Video".

![image](https://user-images.githubusercontent.com/62665767/131667451-b51befa0-7714-4d21-818e-ff98de1dc2cf.png)

**Comment by InnovateAsterisk** [comment]
Works fine for me.

https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getSupportedConstraints



![IMG_3962](https://user-images.githubusercontent.com/58937573/131703996-12d0b5e5-85df-4e79-b05e-b94da3c407f9.jpg)

**Comment by adrehmanforunity** [comment]
okay.. we verified it was an older version of IOS, safari, and chrome, and everything is updated now.



![image](https://user-images.githubusercontent.com/62665767/132090302-d1193936-9a92-437c-b8ae-96a6bb9f2ef9.png)
![image](https://user-images.githubusercontent.com/62665767/132090404-adac2601-e4e6-486c-8399-d4434577027f.png)


On chrome, screen and console logs are attached.


![image](https://user-images.githubusercontent.com/62665767/132090439-342065d1-bfd1-40ff-8f7c-a3f913d94c44.png)
[Chorom-Console.txt](https://github.com/InnovateAsterisk/Browser-Phone/files/7109569/Chorom-Console.txt)





BTW, on windows all is good.

**Comment by InnovateAsterisk** [comment]
A desktop computer will use MacOS, the IOS is for mobile devices like iPhones etc. (There is quite a big difference especially in Chrome).

The Errors you are showing above point to it being an ICE error (not the same as the first errors). You can try to first remove the ICE settings, and then try again, or check that the ICE settings are the same as the working windows instance.

**Comment by adrehmanforunity** [comment]
Thanks for the information and sorry I am new to MAC things and IOS, following are the results as we have concluded. 

On the IOS "Safari" we haven't tested it yet, but you did so it's working.
On the IOS "Edge" we haven't tested it yet, we request you to test, if possible 
On the IOS "Chrome" we haven't tested it yet, we request you to test, if possible

**On the MacOS "Safari" we have said error**
On the MacOS "Chrome" all good

On the Andriod "Chrome" all good
On the Andriod "Edge" all good

On the windows "Chrome" all good
On the windows"Edge" all good

I can easily try without ICE settings. and get back to you.

**Comment by InnovateAsterisk** [comment]
> On the IOS "Safari" we haven't tested it yet, but you did so it's working.

On my iPhone, I found this to be the best working solution, for a few reasons - 
1) You can permanently allow the microphone (tap the aA (left of the address) > Website Settings. 
2) Typing in the text area (especially with an external keyboard) is a better experience. (although it has to be said... its still quite annoying with such a small amount of screen space). This is better on an iPad.
3) Remove Developer tools is possible, so full debugging is available.

> On the IOS "Edge" we haven't tested it yet, we request you to test, if possible

I only have this installed on my iPad - its the same as Chrome. It kinda IS Chrome, just with a different logo.

> On the IOS "Chrome" we haven't tested it yet, we request you to test, if possible

It keeps asking for permission to use the microphone... its annoying, but it seems to work fine.

Generally, im not convinced that this is the right solution of mobile devices - there are other apps out there for this.

**Comment by adrehmanforunity** [comment]
Thanks for the hint, this is an ICE setting-related issue resolved and working well now.
