### ISSUE TITLE
Webrtc error answering video call

### ISSUE THREAD

**Issue by stefanofavaro** [InnovateAsterisk/Browser-Phone#157]
Hello,
I have used Asterisk 13 together with browser phone in the past without problems.
Now I'm having problems answering video calls. I always get a webRTC error. Audio calls are working normally.
I don't know if this is due to the latest chrome update Versione 93.0.4577.63 (Build ufficiale) (a 64 bit).
Does someone have the same error ?
Thanks.
S

This is a short log:
Tue Sep 07 2021 16:24:24 GMT+0200 (Ora legale dell’Europa centrale) | sip.invitecontext.sessionDescriptionHandler | track added
phone.js:2161 Uncaught TypeError: Cannot set properties of undefined (setting 'srcObject')
    at s.<anonymous> (phone.js:2161)
    at s.i.emit (sip-0.11.6.min.js:1)
    at s.trackAdded (sip-0.11.6.min.js:1)
    at RTCPeerConnection.<anonymous> (sip-0.11.6.min.js:1)
sip-0.11.6.min.js:1 Tue Sep 07 2021 16:24:24 GMT+0200 (Ora legale dell’Europa centrale) | sip.invitecontext.sessionDescriptionHandler | track added
phone.js:2161 Uncaught TypeError: Cannot set properties of undefined (setting 'srcObject')
    at s.<anonymous> (phone.js:2161)
    at s.i.emit (sip-0.11.6.min.js:1)
    at s.trackAdded (sip-0.11.6.min.js:1)
    at RTCPeerConnection.<anonymous> (sip-0.11.6.min.js:1)
sip-0.11.6.min.js:1 Tue Sep 07 2021 16:24:24 GMT+0200 (Ora legale dell’Europa centrale) | sip.invitecontext.sessionDescriptionHandler | acquiring local media
phone.js:2152 sinkId applied: default
sip-0.11.6.min.js:1 Tue Sep 07 2021 16:24:25 GMT+0200 (Ora legale dell’Europa centrale) | sip.invitecontext.sessionDescriptionHandler | unable to acquire streams
t.print @ sip-0.11.6.min.js:1
sip-0.11.6.min.js:1 TypeError: Cannot set properties of undefined (setting 'srcObject')
    at s.<anonymous> (phone.js:2161)
    at s.i.emit (sip-0.11.6.min.js:1)
    at s.trackAdded (sip-0.11.6.min.js:1)
    at s.<anonymous> (sip-0.11.6.min.js:1)
t.print @ sip-0.11.6.min.js:1
sip-0.11.6.min.js:1 Tue Sep 07 2021 16:24:25 GMT+0200 (Ora legale dell’Europa centrale) | sip.inviteservercontext | unable to acquire streams
sip-0.11.6.min.js:1 TypeError: Cannot set properties of undefined (setting 'srcObject')
    at s.<anonymous> (phone.js:2161)
    at s.i.emit (sip-0.11.6.min.js:1)
    at s.trackAdded (sip-0.11.6.min.js:1)
    at s.<anonymous> (sip-0.11.6.min.js:1)
phone.js:2265 Call failed: WebRTC Error

**Comment by InnovateAsterisk** [comment]
I'm on the same build as you, Version 93.0.4577.63 (Official Build) (arm64), but I cannot replicate the issue.

The main problem I see is "`unable to acquire streams`"... this takes place when the sipjs code starts the invite using something like getUserMedia(), or in this case accepts the invite. 

Does this not happen when the call is outbound?

Only thing I have noticed is that on a Mac, Safari is having issues playing back the video - it just shows black, or it shows fine, and then when you present something else, it cannot return the main stream.

**Comment by stefanofavaro** [comment]
Thanks for the reply. Yes this happens only when I receive a video call. I've made a test and see that the video element on the html is not present, so I have created a fixed one. In this case the video call is not dropped, the inviter is working (local video and remote video) but the receiver only see a black screen.
    <body>
        <div id=Phone></div>
        <video id=line-1-remoteVideo autoplay="autoplay"></video>
        <video id=line-1-localVideo autoplay="autoplay"></video>
    </body>

**Comment by InnovateAsterisk** [comment]
That sure is strange. So what you are saying is that at this point: 
https://github.com/InnovateAsterisk/Browser-Phone/blob/be6758cd3cc9e7e4f6c1c5e9c0a0b2b4fbca27cb/Phone/phone.js#L2161
The video element is not created yet... Ill take a look.

**Comment by InnovateAsterisk** [comment]
The video elements (that you created manually) get created here: 
https://github.com/InnovateAsterisk/Browser-Phone/blob/be6758cd3cc9e7e4f6c1c5e9c0a0b2b4fbca27cb/Phone/phone.js#L6703

With the only condition of their inclusion being if they are of type "extension" or "xmpp":
https://github.com/InnovateAsterisk/Browser-Phone/blob/be6758cd3cc9e7e4f6c1c5e9c0a0b2b4fbca27cb/Phone/phone.js#L6680

The AddLineHtml() gets called as the call comes in, and is part of the "Answer with Video" button... so it cannot not exist at the time you click answer with video.

Please try your side by putting a break point at 2161, and check ing that the HTML is constructed.

**Comment by stefanofavaro** [comment]
Oh ok. The problem was the buddyobj.type. In this case it is "contact". I've added the condition. Now it works.
Thanks.
