### ISSUE TITLE
Video conference

### ISSUE THREAD

**Issue by stefanofavaro** [InnovateAsterisk/Browser-Phone#160]
Hello do you have plans to implement video conference ?
Using confbridge application in asterisk.
Thanks.

**Comment by InnovateAsterisk** [comment]
Yes, there are a few things to get right first with this, like establishing the group etc, and then the setup in Asterisk, but yes - this is under the  current TODO.

**Comment by prosenkiewicz** [comment]
Hi, my company would gladly use this application for video conferences. That's' why I want to take care of this issue, if you have any tips for me to make it as good as possible that would great. 
Best regards.
