### ISSUE TITLE
Multiple sip accounts

### ISSUE THREAD

**Issue by edimondi** [InnovateAsterisk/Browser-Phone#163]
hi there, is there any way creating multiple accounts and select which one to be active. Thanks

**Comment by edimondi** [comment]
Hello, any update when this feature will be available? Thanks

**Comment by InnovateAsterisk** [comment]
After careful consideration, the direction of this project is to not include this feature. 

However, the solution to this would be for the server to perform the role of account aggregation. The Server should be able to accept inbound calls form multiple sources and send them to the single AOR. A single AOR (with multiple Contact) environment is the correct topography for most single user situations. It dramatically simplifies concepts like DND, and presence.

If you are truly a member of Two unique and separate organisations, then www.siperb.com would be the only other solution (when available) if you don't want to have your own server perform the role of a standalone WS server.
