### ISSUE TITLE
first caller stuck on hold after speaking with the second caller

### ISSUE THREAD

**Issue by edimondi** [InnovateAsterisk/Browser-Phone#166]
hi there, thanks again for your work you are doing great. I had an issue today when i added the caller1 on hold and called extension 193 and when i finished with extension 193 than i could not pick up caller 1 from hold, there was no way, i noticed this in the debug screen, its like it did not create Line 2 when i called extension 193:
phone.js:5902 Putting Call on hold: 1
phone.js:2037 Direction Change:  sendonly
phone.js:4508 INVITE (audio): 193@mydomain Object

**AND HERE IS THE NORMAL BEHAVIOR:**
Putting Call on hold: 1
phone.js:2037 Direction Change:  sendonly
phone.js:6605 Selecting Line : 25 
phone.js:4508 INVITE (audio): 163@MYDOMAIN

**Comment by InnovateAsterisk** [comment]
This is now fix
