### ISSUE TITLE
A little problem about the use of the recording function

### ISSUE THREAD

**Issue by Haoxw** [InnovateAsterisk/Browser-Phone#167]
Hello! I'd like to ask you a question again.
I've tested our recording feature, and in Asterisk 13.11 based environment (WebRTC), I clicked record, but no recording file was actually generated, I'd like to ask how our recording works and what configuration I need to do to enable this feature.

**Comment by Haoxw** [comment]
I tested that the recording function does not work properly in Win10 with Chrome version "84.0.4147.135(64Bit)", but I remember that the recording function works properly in earlier versions. I'm using this version of the "sip-0.15.11.js" library, will it have any effect on the recording function.

**Comment by InnovateAsterisk** [comment]
You may need to issue the following command in Safari developer tools:
```
> indexedDB.deleteDatabase('CallRecordings');
```
They don't have a delete feature.

**Comment by InnovateAsterisk** [comment]
Ah... i see what happened now. Safari used to have the MediaRecorder feature as experimental, and off by default. Even though i tried to use it / tested it, it simply was terrible recording quality... but i had left the code in place for if you have manually enabled the MediaRecorder feature in the developer menu, anyway, it appears that now Safari have MediaRecorder as default enabled... but its still just as terrible as it was before, and only supports mp4, so it breaks the current code. 

Personally, I wouldn't use Safari... they are just too far behind.
