### ISSUE TITLE
XMPP support

### ISSUE THREAD

**Issue by InnovateAsterisk** [InnovateAsterisk/Browser-Phone#17]
Allow a user to select between xmpp and sip in the type configuration.

**Comment by Ch4ng3TheW0rld** [comment]
Yes, it would be nice to has the option to select xmpp or sip

**Comment by InnovateAsterisk** [comment]
https://github.com/InnovateAsterisk/Browser-Phone/commit/7a6dd82a1bf69c84a11e9a41236b07819d2b6128
