### ISSUE TITLE
setRemoteDescription' on RTCPeerConnection failed

### ISSUE THREAD

**Issue by terenz198** [InnovateAsterisk/Browser-Phone#179]
Hi,
Thank you for this hepfull WebRTC client. 
After running Browser Phone (version 0.2.1) without any problem, there is a unexpected error since a few days. Sometimes when I try to make a call from remote when the phone is answered, the call instantly gets terminated and following is the error I get :
![Capture d’écran du 2021-12-14 07-03-09](https://user-images.githubusercontent.com/96106426/145953657-21978980-c732-4563-9670-b494188c208e.png)
Any help is appreciated.
Thank you very much.

**Comment by InnovateAsterisk** [comment]
Are you able to download and use the new version of Browser Phone - it uses SIP.JS version 0.20.0? I see you are still on sip-0.11.6.js

You will need to git clone the entire project. (Both the CSS and the JS files are different). Otherwise, as a test, use the hosted demo: https://www.innovateasterisk.com/phone/ (its using the latest project version) to replicate the issue. If you can reliably recreate the issue, then please send/post the SIP trace messages for the call. (In the developer tools, find the /ws/ websocket connection in Network, tab over to Frames, and copy and paste the inbound INVITE message.)

**Comment by terenz198** [comment]
Thank you for the quick response to my problem. It is difficult for me to migrate to the current version of Browser-phone, because I have made a number of changes. I use Apache as reverse proxy for WebSockets. I will send you the SIP trace messages for the call.
Thanks

**Comment by InnovateAsterisk** [comment]
The one thing that I can see form the screen shot you sent is that the error is caused in the SIPJS code, and probably just a response to the `setRemoteDescription()` error handing - in other words this:
https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/setRemoteDescription

It returns a promise, and this has the error - It's as a result of Chrome or your browser attempting to set the peer connection description from a SIP message from your Asterisk Server. Specifically, it's complaining about the missing DTLS fingerprint that is supposed to be part of the incoming SIP message INVITE in the SDP.

Something like this: 
```
a=fingerprint:sha-256 1B:EA:BF:33:B8:11:26:6D:91:AD:1B:A0:16:FD:5D:60:59:33:F7:46:A3:BA:99:2A:1D:04:99:A6:F2:C6:2D:43
```
If you can confirm that this **is missing** in your invite, then you need to check why Asterisk is not sending you calls with the correctly formed INVITE.

If, on the other hand, it **IS** sending you the fingerprint in the INVITE.. then its an interpretation issue, or maybe you are doing some modification to the SDP.

Either way, you need to rule out one of these first.

**Comment by InnovateAsterisk** [comment]
Yip, that's not going to work ;(

It's almost as if you have not set `webrtc=yes` in the endpoint settings. Are you using PJSIP or chan_sip?

**Comment by terenz198** [comment]
I use PJSIP. 
In my pjsip configuration file, i don't set `webrtc=yes`. I always thought that setting the following options:
`use_avpf=yes`; 
`media_encryption=dtls`; 
`dtls_verify=fingerprint`; 
`dtls_setup=actpass`; 
`ice_support=yes`; 
`media_use_received_transport=yes`; 
`rtcp_mux=yes`

 would do same action. Am I wrong ?

Will test with `webrtc=yes` options and getting you back
Kind regards

**Comment by InnovateAsterisk** [comment]
It's almost the same, but as the versions of Asterisk increase, there are more differences that emerge. However, even with the features that you have set above, you are not being invited according to this.

You are either dialling another extension, or maybe your contact is not being updated correctly. 


It should look like this:
```
INVITE sip:mefrmqg6@172.31.18.8:55402;transport=WS SIP/2.0
Via: SIP/2.0/WS 172.31.25.159:8080;rport;branch=z9hG4bKPj8e5e834e-5e6c-4834-b63b-fb2f4fc3dc68;alias
From: "Eight Hundred" <sip:800@ip-172-31-25-159>;tag=9e2efd60-6db9-489f-83a1-6bac02c66fd0
To: <sip:mefrmqg6@172.31.18.8>
Contact: <sip:asterisk@ip-172-31-25-159:5060;transport=ws>
Call-ID: 33ad9115-249b-43ff-9d52-4f02b76cd992
CSeq: 7933 INVITE
Allow: OPTIONS, REGISTER, SUBSCRIBE, NOTIFY, PUBLISH, INVITE, ACK, BYE, CANCEL, UPDATE, PRACK, MESSAGE, REFER
Supported: 100rel, timer, replaces, norefersub, histinfo
Session-Expires: 1800
Min-SE: 90
Max-Forwards: 70
User-Agent: Innovate Asterisk
Content-Type: application/sdp
Content-Length:   941

v=0
o=- 120194368 120194368 IN IP4 172.31.25.159
s=Asterisk
c=IN IP4 172.31.25.159
t=0 0
a=msid-semantic:WMS *
a=group:BUNDLE audio-0
m=audio 16010 UDP/TLS/RTP/SAVPF 107 0 101
a=connection:new
a=setup:actpass
a=fingerprint:SHA-256 42:14:5C:06:5A:01:13:F5:17:BD:10:FF:A3:3E:16:2C:36:7A:A0:82:06:81:AA:FD:32:A9:F5:D8:54:44:0E:5A
a=ice-ufrag:392dc46e4a67b0061ece165314cf2f64
a=ice-pwd:428d592d2454057949a3e7be3d454b8c
a=candidate:H3432a5cc 1 UDP 2130706431 52.50.165.204 16010 typ host
a=candidate:Hb6de93cb 1 UDP 2130706431 fe80::4ff:a7ff:feb7:47e8 16010 typ host
a=rtpmap:107 opus/48000/2
a=fmtp:107 useinbandfec=1
a=rtpmap:0 PCMU/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-16
a=ptime:20
a=maxptime:20
a=sendrecv
a=rtcp-mux
a=ssrc:2007341327 cname:36176ac0-2b84-4df5-9c00-b255258bd0d8
a=msid:1ef5ff7b-2147-432c-959e-83dbda8f8bdd e09c84e6-8d8d-4263-b689-09c96862c83c
a=rtcp-fb:* transport-cc
a=mid:audio-0

```

**Comment by terenz198** [comment]
Trying to find the solution by myself I should have told you right away. You made my day.
Saving me from several days of trouble.

1. First, I didn't have the `webrtc=yes` option on pjsip config file
2. I was trying to call a phone_endpoint extension from a webrtc_endpoint extension with Browser-phone

This is what I am getting now for a webRTC_endpoint incoming SIP message INVITE

INVITE sip:trpt6p50@192.168.227.115:45830;transport=ws SIP/2.0
Via: SIP/2.0/WS 192.168.227.115:8080;rport;branch=z9hG4bKPjaf72689d-c12c-4fb8-ba6c-8c79eb38410d;alias
From: "User one" <sip:100@pi-desktop>;tag=55300c29-def9-412e-a07c-9c2bce9e9be5
To: <sip:trpt6p50@192.168.227.115>
Contact: <sip:asterisk@pi-desktop:5060;transport=ws>
Call-ID: 2366c126-4c40-439a-a344-1abf23659bf0
CSeq: 25580 INVITE
Allow: OPTIONS, REGISTER, SUBSCRIBE, NOTIFY, PUBLISH, INVITE, ACK, BYE, CANCEL, UPDATE, PRACK, MESSAGE, REFER
Supported: 100rel, timer, replaces, norefersub, histinfo
Session-Expires: 1800
Min-SE: 90
Max-Forwards: 70
User-Agent: Raspberry Pi BPX
Content-Type: application/sdp
Content-Length:   937

v=0
o=- 1780594057 1780594057 IN IP4 192.168.8.115
s=Asterisk
c=IN IP4 192.168.8.115
t=0 0
a=msid-semantic:WMS *
a=group:BUNDLE audio-0
m=audio 19240 UDP/TLS/RTP/SAVPF 0 107 101
a=connection:new
a=setup:actpass
a=fingerprint:SHA-256 EF:3F:B9:F7:AE:B7:DA:1E:93:B0:83:C4:CD:94:C6:DC:E4:80:7E:84:05:AD:BD:BC:DD:92:D2:B0:A4:F5:ED:FB
a=ice-ufrag:578c497f376128f12eae063d1031ed73
a=ice-pwd:72cf2953540f6f5e41432ba818fb26d6
a=candidate:Hc0a80873 1 UDP 2130706431 192.168.8.115 19240 typ host
a=candidate:Sc5eadb13 1 UDP 1694498815 197.234.219.19 4498 typ srflx raddr 192.168.8.115 rport 19240
a=rtpmap:0 PCMU/8000
a=rtpmap:107 opus/48000/2
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-16
a=ptime:20
a=maxptime:60
a=sendrecv
a=rtcp-mux
a=ssrc:432912553 cname:26930b6e-8c83-4c60-99f8-b213059de97b
a=msid:12503215-31c2-43ae-9b84-71540ea0a063 b73b21f7-689a-42f8-bc23-e4d9b2e79acf
a=rtcp-fb:* transport-cc
a=mid:audio-0


Thank you very much for your contribution and availability

**Comment by InnovateAsterisk** [comment]
Yip, that looks much better 👊
