### ISSUE TITLE
latest version over internet

### ISSUE THREAD

**Issue by adrehmanforunity** [InnovateAsterisk/Browser-Phone#183]
hi all,

first of all i think i am conferrable with Browser-Phone "older version". its still working fine with over internet the only issue was that call hold was not working, so this mean i have properly working stun and trun available with me.

whereas now with latest version there is no audio or video and call get disconnected after few seconds, stun and trun configured in the same was as it still working in older version.

i don't know how to report this i have no clue, as i see no error in console.

any suggestions?

**Comment by InnovateAsterisk** [comment]
Fix being released now.

**Comment by adrehmanforunity** [comment]
yes voice and okay... as last version. 

just noticed that browser kept playing ringing sound, didn't stopped, from start of call to end of call .. even after call

**Comment by InnovateAsterisk** [comment]
>just noticed that browser kept playing ringing sound, didn't stopped, from start of call to end of call .. even after call

When this happens, would mind sending the console output, so this I can see what the issue is.

**Comment by adrehmanforunity** [comment]
yes sure.. some part is remote and some change as it was having internal information, if required let me know.

[BPM-1640960365426.log](https://github.com/InnovateAsterisk/Browser-Phone/files/7796410/BPM-1640960365426.log)

**Comment by InnovateAsterisk** [comment]
You appear to be sending a 180 progress twice.
>sip-0.20.0.min.js:2 Fri Dec 31 2021 19:17:39 GMT+0500 (Pakistan Standard Time) | sip.Inviter | Inviter.onProgress
phone.js:2175 Audio: media/Tone_EarlyMedia-US.mp3
sip-0.20.0.min.js:2 Fri Dec 31 2021 19:17:39 GMT+0500 (Pakistan Standard Time) | sip.Inviter | Inviter.onProgress
phone.js:2175 Audio: media/Tone_EarlyMedia-US.mp3

It's likely to be creating two early media objects. I'll put out a patch to avoid this.

**Comment by adrehmanforunity** [comment]
yes, its fixed and working well now... checking in further details
