### ISSUE TITLE
registered user is getting unregistered automatically after some time

### ISSUE THREAD

**Issue by prathibhacdac** [InnovateAsterisk/Browser-Phone#188]
In the latest version of Browser Phone, the registered user is automatically getting unregistered after a few minuted.

**Comment by prathibhacdac** [comment]
This behavior is observed in version 0.20 whereas it was not happening in version 0.11 of Browser Phone.

**Comment by InnovateAsterisk** [comment]
There will be an event of some sorts causing this - please send browser console log and asterisk console log.

**Comment by prathibhacdac** [comment]
[consoleLog.log](https://github.com/InnovateAsterisk/Browser-Phone/files/7827476/consoleLog.log)

**Comment by InnovateAsterisk** [comment]
Ah, you are trying to get XMPP going.

**Comment by prathibhacdac** [comment]
I'm using SIP

**Comment by InnovateAsterisk** [comment]
I need to do a video on this - it needs to be quite specifically setup.
> DOMException: Failed to construct 'WebSocket': The URL 'wss://undefined:undefinedundefined' is invalid.
    at r.value (https://dtd6jl0d42sve.cloudfront.net/lib/XMPP/strophe-1.4.1.umd.min.js:1:55500)

**Comment by prathibhacdac** [comment]
[siptraces.txt](https://github.com/InnovateAsterisk/Browser-Phone/files/7827517/siptraces.txt)

**Comment by InnovateAsterisk** [comment]
tHe browser phone has the ability to establish both a SIP connection for voice and an XMPP for texting. If you are only going to use the SIP modules, then remove the XMPP settings, so it can skip it

**Comment by prathibhacdac** [comment]
Have already removed it.

**Comment by InnovateAsterisk** [comment]
Does it maintain registration with the XMPP settings removed?

You should no longer see:
>phone.js:13177 Connect/Reconnect XMPP connection...
phone.js:13209 XMPP connect...
phone.js:12253 XMPP is connecting...

**Comment by prathibhacdac** [comment]
How to disable XMPP?

**Comment by InnovateAsterisk** [comment]
https://github.com/InnovateAsterisk/Browser-Phone/blob/df6bf122334bf701d18a22b677d25bab344de21b/Phone/phone.js#L134

Leave it as SIMPLE

**Comment by InnovateAsterisk** [comment]
In the UI its:

![image](https://user-images.githubusercontent.com/58937573/148517089-2aa48b3e-2119-49d0-85b2-1a1b182eda66.png)

**Comment by prathibhacdac** [comment]
[consolelog.log](https://github.com/InnovateAsterisk/Browser-Phone/files/7827693/consolelog.log)

**Comment by InnovateAsterisk** [comment]
Seems like the registration is stable.

**Comment by prathibhacdac** [comment]
Issue resolved
