### ISSUE TITLE
Stun Server declared in phoneOptions fails

### ISSUE THREAD

**Issue by answeringsp** [InnovateAsterisk/Browser-Phone#194]
I added this in index.html in order to use a private stun server

            var phoneOptions = {
                loadAlternateLang: true,
                **IceStunServerJson: [{"urls": "stun:stun.mystunserver.com:3478" }]**
            }

It threw an error so I had to make this change in phone.js remove the JSON.parse and use a simple "=" as the code being called after expects a JSON object.

    if(IceStunServerJson != ""){
        // options.sessionDescriptionHandlerFactoryOptions.peerConnectionConfiguration.iceServers = JSON.parse(IceStunServerJson);
        options.sessionDescriptionHandlerFactoryOptions.peerConnectionConfiguration.iceServers = IceStunServerJson;
    }

**Comment by InnovateAsterisk** [comment]
The settings in the storage system use values as a string, so to keep things the same, you should probably parse it as a string too.

The code executes a JSON.parse(...), that expects json as a string. Like this:
```
        var phoneOptions = {
            loadAlternateLang: true,
            IceStunServerJson: "[{\"urls\": \"stun:stun.mystunserver.com:3478\" }]"
        }
```
