### ISSUE TITLE
DTMF not working in attended and conference call

### ISSUE THREAD

**Issue by raulbmjr** [InnovateAsterisk/Browser-Phone#204]
Hi Conrad,

DTMF is working fine when I directly dial an outside number that has an IVR, but when I tried to do attended transfer or Conferencing, the DTMF is not working (I'm using RFC4733)

Please see attached for the console logs. Thank you!
[Webrtc-DTMF-Not-Working-conference.txt](https://github.com/InnovateAsterisk/Browser-Phone/files/8052322/Webrtc-DTMF-Not-Working-conference.txt)
[Webrtc-DTMF-Not-Working-attendedtransfer.txt](https://github.com/InnovateAsterisk/Browser-Phone/files/8052323/Webrtc-DTMF-Not-Working-attendedtransfer.txt)

**Comment by InnovateAsterisk** [comment]
I have been using the DTMF tones extensively without issues. Im testing on Ast18. Going according to: 
https://developer.mozilla.org/en-US/docs/Web/API/RTCDTMFSender/insertDTMF
with these options:
```JavaScript
var options = {
    duration: 100,
    interToneGap: 70
}
```
You can try alter these options. I believe they are the defaults. 

```
tones
A [DOMString](https://developer.mozilla.org/en-US/docs/Web/API/DOMString) containing the DTMF codes to be transmitted to the recipient. Specifying an empty string as the tones parameter clears the tone buffer, aborting any currently queued tones. A "," character inserts a two second delay.

duration Optional
The amount of time, in milliseconds, that each DTMF tone should last. This value must be between 40 ms and 6000 ms (6 seconds), inclusive. The default is 100 ms.

interToneGap Optional
The length of time, in milliseconds, to wait between tones. The browser will enforce a minimum value of 30 ms (that is, if you specify a lower value, 30 ms will be used instead); the default is 70 ms.
```

Are you sure you have enabled features for the attended transfer, and menus for the conference?

**Comment by raulbmjr** [comment]
Hi Conrad,

Just to clarify, I am not having issues with DTMF when the call is not passing via attended transfer or conferencing. I am only having ussies with the DTMF not being recognized by the IVR of the called party when the call is being dialed within attended transfer or conferencing.

I have tested your suggestion of altering the values of the duration and interToneGap but the issue is the same.

As for the attended transfer feature and menus for the conference, I am not sure what do you mean by this. Is this in the PBX itself?

**Comment by InnovateAsterisk** [comment]
ah... I see... you are saying that when in the middle of the attended transfer (before transfer is complete), or during the Conference Call (any time), the DTMF doesn't work on the call. Right?

Well, right away, the question is, on what call is the DTMF being sent. You see the "parent" call is the only channel that gets the DTMF signal, there is nothing to send DTMF to the "child" call. It simply doesn't exist... I would have to do an update to accommodate this.

**Comment by raulbmjr** [comment]
Yes correct, looks like there is nothing being send on the "child" call

Thanks for looking into this Conrad, really appreciate your immediate response

**Comment by InnovateAsterisk** [comment]
For the attended transfer option, it would make sense to simply divert the DTMF to the child call, as the parent one would be on hold before the refer is sent. 

For conference the same could be said, except when the call is joined. Then the DTMF would either need to be sent to both channels, or there would have to be some new interface.

**Comment by raulbmjr** [comment]
Hi Conrad,

Any news on the updated version? Thanks!

**Comment by InnovateAsterisk** [comment]
I’m in the middle of quite an extensive UI update. New release due end of next week.

**Comment by raulbmjr** [comment]
Hi Conrad,

Apologies for asking, how are the updates?

**Comment by InnovateAsterisk** [comment]
The UI is almost done, im actually busy with the Call Screen now - including DTMF handling. A few more days.

**Comment by raulbmjr** [comment]
Thank you

**Comment by raulbmjr** [comment]
Thank you so much Conrad for providing this great WebRTC application and for fixing the issues.
