### ISSUE TITLE
bundled lib

### ISSUE THREAD

**Issue by vieridipaola** [InnovateAsterisk/Browser-Phone#208]
Hi,

I was using these bundled libraries to host everything on my server:

https://dtd6jl0d42sve.cloudfront.net/lib/lib.zip

Could it be updated (sipjs version, etc)?

**Comment by InnovateAsterisk** [comment]
It would probably be better for future consistency to include this file into the git project, then you can just grab it each time it’s released. I’ll just script something to package a zip of the necessary .min files.

**Comment by InnovateAsterisk** [comment]
It's now included as a folder
