### ISSUE TITLE
Pin code dialpad

### ISSUE THREAD

**Issue by ssjunior** [InnovateAsterisk/Browser-Phone#212]
Hi, 

Very nice project and thank you for make it avaiable. 

I could not find a way to show a dialpad after a call to type a pin code. Is there a way?

Thank you very much.

**Comment by InnovateAsterisk** [comment]
First lift the call controls, then the click the Send DTMF button.

<img width="425" alt="image" src="https://user-images.githubusercontent.com/58937573/156727989-ad2003aa-1946-481f-8f4c-42e97a9b0498.png">

**Comment by ssjunior** [comment]
Hi Conrad,

First of all, thank you for the quick answer. Unfortunately I do not have this option.

After dialing the number, the call begins, but, I need to dial a pin code to complete the call. 

![Markup on 2022-03-04 at 12:48:23](https://user-images.githubusercontent.com/5460671/156795624-677c25a3-a5ca-4d84-b9e1-7a9ec04d772c.png)

At this point I dont have access to call controls. :(

I am self hosting the cloned code.

Any idea?

**Comment by InnovateAsterisk** [comment]
Ah, ok, this is during “early media” stage. I’ll have to update the code to allow DTMF during this state.

**Comment by ssjunior** [comment]
I tried to find it in the code, but, it's very extensive. Anyway if I can help somehow, just point me the direction.

All the html code is inside the JS, what do you think about separate the js from the presentation layer using something like react/preact? This way you can focus your energy on the js logic and the presentation could be implemented by other people.

**Comment by InnovateAsterisk** [comment]
The DTMF feature is valid, so I’ll build it in.

**Comment by ssjunior** [comment]
Thank you @InnovateAsterisk. I'll wait for it. :)

**Comment by InnovateAsterisk** [comment]
This feature has been added, it will be out in the next release. I'm just busy with some connectivity handing improvements, then will release.

**Comment by ssjunior** [comment]
Thank you very much!

**Comment by InnovateAsterisk** [comment]
Grab the latest code Version 0.3.4

**Comment by ssjunior** [comment]
Thank you. I will test and let you know if everything is ok. For some reason after I did update, I can't connect anymore to websocket due to a TLS error, but I will find out here. 

Thankss!!!!

**Comment by ssjunior** [comment]
Done. Working perfectly. Thanks.
