### ISSUE TITLE
configuration from index page

### ISSUE THREAD

**Issue by adrehmanforunity** [InnovateAsterisk/Browser-Phone#216]
Hi, we have applied configuration from sip account and other configuration from index page but change is making no difference, still asking for information as to its working for the first time.

BTW, we are using a private window to avoid saved information.
please suggested.

  
![image](https://user-images.githubusercontent.com/62665767/158177263-291e2bb4-a7b3-4ed8-be1e-dd752600c23f.png)

from index page.

            // Provision runtime options can go here.
            var phoneOptions = {
                loadAlternateLang: true,
				welcomeScreen: null,
				profileUser: "2003",
				profileName: "2003",
				wssServer: "192.168.18.90",
				WssInTransport:1,
				WebSocketPort: 8089,
				ServerPath: "/ws",
				SipUsername: "2003",
				SipPassword: "0102030405",
    				AudioOutputId: 'default',
    				VideoSrcId: 'default',
				VideoHeight: '240',
    				FrameRate: '15',
				AspectRatio: '1.33',
				VideoOrientation: 'rotateY(180deg)',
				AudioSrcId: 'default',
				AutoGainControl: "1",
				EchoCancellation: "1",
				NoiseSuppression: "1",
				RingOutputId:'default',
				Notifications:"0"
            };

**Comment by InnovateAsterisk** [comment]
You need to understand the ```profileUserID```. 

When you use this phone for the first time, and apply SIP details, it will also make an entry in local storage called ```profileUserID```. This is a random key, but the system will look for it on subsequent page loads, and provision the details, like sip username etc. The buddies/contacts are saved based off this key, so even if you do manage to load two profiles, they are not conflicting with each other.

When you want to provision the details from ```phoneOptions{}```, you should have already set the local storage, based off some unique identity of your own internal systems, like a DB id, LDAP id, etc, etc.

Something like this would work
```
<script type="text/javascript">
            window.localStorage.setItem("profileUserID", "<?php echo($_SESSION['session_id']); ?>");

            var phoneOptions = {
                loadAlternateLang: true,

// other settings here

           }
</script>
```

Another user on this pc would typically be separated by their windows session, so would not use the same storage. 

However, if multiple users are literally using the exact same login and the same chrome session, you can still separate them out based on the  ```profileUserID```. They would of course need to have separate session id's (I'm assuming PHP can handle that for you)

**Note:** make sure you copy only the variables from here:
https://github.com/InnovateAsterisk/Browser-Phone/blob/cc81b20d884e18bf75f7bae2f5c2628aa7a2276a/Phone/phone.js#L360
And not the "names" saved to the local storage.
