### ISSUE TITLE
keypad not fully viewable

### ISSUE THREAD

**Issue by prathibhacdac** [InnovateAsterisk/Browser-Phone#226]
While in video call, keypad is not fully viewable.

**Comment by InnovateAsterisk** [comment]
Please send a screen shot of the problem you are experiencing.

**Comment by prathibhacdac** [comment]
![Screenshot (167)](https://user-images.githubusercontent.com/26375790/161192231-5ee78f0e-bf17-4f0e-a90f-ebe49924105a.png)

**Comment by InnovateAsterisk** [comment]
Wow, that is so strange… it seems like you have a mixture of the old UI, and the new one. It could be a simple CSS issue, but to be sure, just got clone the latest version, and make sure you clear your browser cache.

**Comment by prathibhacdac** [comment]
This feature is not there in the latest version.
