### ISSUE TITLE
Able to call the user itself by using dialer.

### ISSUE THREAD

**Issue by prathibhacdac** [InnovateAsterisk/Browser-Phone#227]

**Comment by InnovateAsterisk** [comment]
Please explain your problem/issue further.

**Comment by prathibhacdac** [comment]
Suppose I've logged in as 10100. I can call to myself.

**Comment by prathibhacdac** [comment]
[phone-diff-profileUser.txt](https://github.com/InnovateAsterisk/Browser-Phone/files/8394792/phone-diff-profileUser.txt)

**Comment by InnovateAsterisk** [comment]
This feature will remain in place, as it's not possible to know what other people may do in this situation. Please handle this in the dial plan.

**Comment by prathibhacdac** [comment]
How to handle it in dialplan?

**Comment by InnovateAsterisk** [comment]
Check for something like ${EXTEN} being equal to  CALLERID(num)
