### ISSUE TITLE
Keypad

### ISSUE THREAD

**Issue by prathibhacdac** [InnovateAsterisk/Browser-Phone#229]
No Backspace in keypad

**Comment by InnovateAsterisk** [comment]
Noted

**Comment by prathibhacdac** [comment]
[diff-index.txt](https://github.com/InnovateAsterisk/Browser-Phone/files/8396206/diff-index.txt)
[phone-diff-backSpace.txt](https://github.com/InnovateAsterisk/Browser-Phone/files/8396208/phone-diff-backSpace.txt)

Patches to resolve this issue attached.
