### ISSUE TITLE
video calls between two webrtc peers

### ISSUE THREAD

**Issue by vieridipaola** [InnovateAsterisk/Browser-Phone#23]
Hi,

I noticed that video calls between two webrtc peers are not working as expected.

First of all, when both peers use Firefox ESR there's no option to make a video call -- only audio calls from both ends.

When using Chrome, in my case I see that only one of the two peers can initiate a video call (when both have cameras). The "video icon" is missing in one of the two. 

The webrtc extensions are defined in Asterisk as (pjsip):

```
[doctor]
type=aor
max_contacts=5
remove_existing=yes

[doctor]
type=auth
auth_type=userpass
username=doctor
password=doctor 

[doctor]
type=endpoint
aors=doctor
auth=doctor
dtls_auto_generate_cert=yes
webrtc=yes
context=default
disallow=all
allow=alaw,ulaw,opus,gsm,vp8,h264
rtp_symmetric=yes
force_rport=yes

```

```
[patient]
type=aor
max_contacts=5
remove_existing=yes

[patient]
type=auth
auth_type=userpass
username=patient
password=patient

[patient]
type=endpoint
aors=patient
auth=patient
dtls_auto_generate_cert=yes
webrtc=yes
context=default
disallow=all
allow=alaw,ulaw,opus,gsm,vp8,h264
rtp_symmetric=yes
force_rport=yes

```

Is this a bug, something I misconfigured, or a network-related issue?

Regards,

Vieri

**Comment by InnovateAsterisk** [comment]
I can double check with Firefox ESR, but I think you are describing the difference between a buddy as a contact or an extension. There are two types of buddies that get created when you click the "**Add Someone**" button.

**Extensions (typically other people on your PBX)**
To call another extension typically in your company (and on the same pbx), you will enter their DID in the "**_Subscribe Extension (Internal):_**" field. This marks the buddy as type "extension", and will allow you to chat, video call, and you also see their device state (subscribe). With the buddy of type extension, you can still enter their mobile numbers etc. The system just gives you these numbers as an option when you click the (audio) dial option. The systems assumes both parties have video codes and capabilities enabled (as described in the video).

**Contacts (Mobile numbers etc)**
When you leave the "**_Subscribe Extension (Internal):_**" field empty, it sets up the contact as an external contact. Typically someone outside of your company. You would then typically enter mobile numbers etc. With these types of contacts, you don't get chat, or video call options.

**Comment by vieridipaola** [comment]
You are right, and it works with Firefox ESR too.

By the way, once an "external extension/number" is created you cannot convert it to "local" by editing it since the "Subscribe Extension (internal)" field is not available. Is that intended?

**Comment by InnovateAsterisk** [comment]
> By the way, once an "external extension/number" is created you cannot convert it to "local" by editing it since the "Subscribe Extension (internal)" field is not available. Is that intended?

It's by design, yes... but admittedly something that should be looked at.
