### ISSUE TITLE
theme

### ISSUE THREAD

**Issue by prathibhacdac** [InnovateAsterisk/Browser-Phone#239]
How to change light theme to dark theme?

**Comment by InnovateAsterisk** [comment]
It will change with your System light/dark settings, also with your browser light and dark settings. 

Also there is a setting to override these:
https://github.com/InnovateAsterisk/Browser-Phone/blob/6c77230814fa60101b57cf98bc6a71b166f582f2/Phone/phone.js#L95

Use “system”, “dark”, “light”.
System will react according to the system or browser settings.

**Comment by prathibhacdac** [comment]
I've installed dark theme for google chrom from https://chrome.google.com/webstore/detail/dark-theme-for-google-chr/annfbnbieaamhaimclajlajpijgkdblo

But the theme is not changing for Browser phone?

**Comment by InnovateAsterisk** [comment]
set UiThemeStyle to "dark"
