### ISSUE TITLE
Voice Mail - MWI: Alerts and Access

### ISSUE THREAD

**Issue by rgonzalez-in** [InnovateAsterisk/Browser-Phone#242]
Hello:

Please:

The WebPhone need Voice Mail - MWI: Alerts and Access, like this: ![image](https://user-images.githubusercontent.com/27745450/162594581-f924ad9c-3e69-404a-96ce-3716df6edba1.png)

Regards.

**Comment by rgonzalez-in** [comment]
Hello:

Please:

The WebPhone need Voice Mail - MWI: Alerts and Access, like this: ![image](https://user-images.githubusercontent.com/27745450/162594543-ccf4ad58-cb18-4d32-a3d1-05d57f53e23f.png)

Regards.

**Comment by InnovateAsterisk** [comment]
Coming soon

**Comment by rgonzalez-in** [comment]
Hello:

Thanks for you response.

I try to activate the Voicemail Option, but not working. I use Asterisk 18.10.1

PJSIP Configuration:

mailboxes=70061@centralita
voicemail_extension=8006

Please help me:

let VoiceMailSubscribe = (getDbItem("VoiceMailSubscribe", "1") == "1");             // Enable Subscribe to voicemail
let VoicemailDid = getDbItem("VoicemailDid", "8006");                                  // Number to dail for VoicemialMain()


Regards.

**Comment by InnovateAsterisk** [comment]
What have you got in voicemail.conf?

**Comment by rgonzalez-in** [comment]
[centralita] ;Contexto Voice Mail
7006 =>1234,Web Phone,webphone@informatica-nacional.cl,,Tz=chile

**Comment by rgonzalez-in** [comment]
[7006]
type=endpoint
callerid="Web Phone" <7006>
language=es
context=centralita
allow_subscribe=yes
message_context=messenger
disallow=all
allow=h264,ulaw,ulaw
;transport=transporte-tls
transport=transporte-wss
ice_support=yes
direct_media=no
force_rport=yes
rtp_symmetric=yes
mailboxes=7006@centralita
voicemail_extension=7006
auth=7006
aors=7006
tos_audio=0
tos_video=0
cos_audio=0
cos_video=0
max_audio_streams=1
max_video_streams=1
;media_encryption=sdes
webrtc=yes

**Comment by InnovateAsterisk** [comment]
Could be just a typo:
mailboxes=70061@centralita

You don’t have such a mailbox. You have an extra 1 above.

[centralita] ;Contexto Voice Mail
7006 =>1234,Web Phone

**Comment by rgonzalez-in** [comment]
It doesn't work yet:

My configuration:

phone.js
let VoiceMailSubscribe = (getDbItem("VoiceMailSubscribe", "1") == "1");             // Enable Subscribe to voicemail
let VoicemailDid = getDbItem("VoicemailDid", "8006");                                  // Number to dail for VoicemialMain()

extensions.conf
exten => 8006,1,VoiceMailMain(7006@centralita_voicemail)
same => n,Ringing
same => n,Hangup()

pjsip.conf
mailboxes=7006@centralita_voicemail
voicemail_extension=8006

voicemail.conf
[centralita_voicemail] ;Context Voice Mail
7006 =>1234,Web Phone,operaciones@informatica-nacional.cl,,Tz=chile

**Comment by rgonzalez-in** [comment]
In my IP Phone Grandstream work perfect.

**Comment by rgonzalez-in** [comment]
SUBSCRIBE VOICEMAIL: 7006@sip.informatica-nacional.cl
sip.Subscription | Subscription undefined transitioned to NotifyWait

**Comment by rgonzalez-in** [comment]
I see this:

![image](https://user-images.githubusercontent.com/27745450/163689005-fc60db87-8caf-467f-b8c9-f03df6c54214.png)

**Comment by rgonzalez-in** [comment]
I see this:

![image](https://user-images.githubusercontent.com/27745450/163693879-c27e0819-2f09-4029-b6f9-48049e46bab8.png)

**Comment by rgonzalez-in** [comment]
I see this on console web browser:

![image](https://user-images.githubusercontent.com/27745450/163694186-2706ce38-0f15-415b-9eda-88b47edcbc4f.png)

**Comment by InnovateAsterisk** [comment]
Shortly after that you should see something like
‘Voicemail: 1 0 0 0 0’ in the browser console. 

And that should show the new notification icon under the profile info (next to dial etc).

**Comment by rgonzalez-in** [comment]
Sorry, but not working:

![image](https://user-images.githubusercontent.com/27745450/163726882-e876d484-5438-46fa-b743-4b9306f416eb.png)

**Comment by rgonzalez-in** [comment]
Do you have a example working?

Reggards.

**Comment by InnovateAsterisk** [comment]
Well, that pretty much is the working example. 
On receiving the message above, the following is executed:

https://github.com/InnovateAsterisk/Browser-Phone/blob/6f5051f5bc90b9927d06e38f00a6bec3061b93fd/Phone/phone.js#L3845

I have the exact same message body (except with full sip headers), and it works fine. Are your sure you have the latest code?

**Comment by rgonzalez-in** [comment]
Sorry, but not works: 

Voicemail: Not Icon and Notify

I have the same code:
https://github.com/InnovateAsterisk/Browser-Phone/blob/6f5051f5bc90b9927d06e38f00a6bec3061b93fd/Phone/phone.js#L3845

WebBrowser: Edge, Chrome, Firefox, Opera:

Incoming Calls: OK
Notify Calls: OK
Out Calls: OK
Incoming Messages: OK
Notify Messages: OK
Out Messages: Ok
BLF: OK
Transfer Calls: OK

**Comment by rgonzalez-in** [comment]
I Set traceSip: true

Display all sip headers.

![image](https://user-images.githubusercontent.com/27745450/163728310-6298b1a2-8ff8-4615-bac0-6ba0850853e0.png)


![image](https://user-images.githubusercontent.com/27745450/163728204-fe9fb5da-3f78-44d5-b2d4-e87e5686d607.png)

**Comment by rgonzalez-in** [comment]
![image](https://user-images.githubusercontent.com/27745450/163728435-f0e1d5e4-b8e3-4c53-98bd-f0fde263d0ed.png)

**Comment by rgonzalez-in** [comment]
![image](https://user-images.githubusercontent.com/27745450/163731792-db5d2309-12dc-4ded-8a8b-584a1265d71f.png)

**Comment by rgonzalez-in** [comment]
Asterisk 18.10.1

**Comment by InnovateAsterisk** [comment]
481 Call/Transaction Does Not Exist

You can also see the SIPJs is responding with full headers. I can’t find any documentation on SIP js supporting Compact Headers.

Try disable this feature in Asterisk and try again.

**Comment by InnovateAsterisk** [comment]
https://wiki.asterisk.org/wiki/display/AST/Asterisk+18+Configuration_res_pjsip

```
mailboxes
This option applies when an external entity subscribes to an AoR for Message Waiting Indications. The mailboxes specified will be subscribed to. More than one mailbox can be specified with a comma-delimited string. app_voicemail mailboxes must be specified as mailbox@context; for example: mailboxes=6001@default. For mailboxes provided by external sources, such as through the res_mwi_external module, you must specify strings supported by the external system.

For endpoints that cannot SUBSCRIBE for MWI, you can set the mailboxes option in your endpoint configuration section to enable unsolicited MWI NOTIFYs to the endpoint.
```

It maybe that the SIPjs is not accepting the messages because they are coming as unsolicited.

**Comment by rgonzalez-in** [comment]
Hello:

Sorry for the delay in writing... I was able to solve the voicemail problem.

My experience is the following:

I have a IP Phone Grandstream GXP2170 and the voicemail configuration must be included in type=endpoint. And Web Phone the voicemail configuration must be included in type=aor.

Thank you for your support.

Regards.
