### ISSUE TITLE
provisioning upon authentication

### ISSUE THREAD

**Issue by vieridipaola** [InnovateAsterisk/Browser-Phone#25]
Hi,

I was wondering if provisioning is contemplated somehow, or what would the best approach be.
The idea in my case is that a user needs to authenticate in order to open the "webphone". Each authenticated user would then have their account set up automatically, and probably even the contact list. 
For instance, if I use Apache HTTP I can force LDAP authentication, just to name one, and then somehow override the window.localStorage items. This is not my domain, and I usually don't program in javascript, but is there an "elegant" way to override what phone.js does? Can I call localStorage.setItem() in another custom js and load it in the html?
I don't care if the user can then modify the account details -- I just need to provision the SIP login details on HTTP authentication (they would be overwritten on each Apache HTTP login).

Provisioning the contact list actually doesn't make much sense to me right now. However, allowing an LDAP search for contacts to be "imported" would be neat. The "Find someone" input text field could be linked to an LDAP query, and the user would then have the option of importing contacts to his/her "buddy list". That would be useful when there are hundreds of internal extensions. Then again, all this can be outsourced on an intranet site, just as long as Browser-Phone can receive a contact/phone number via GET, POST, whatever, and eg. ask the user to import it.
Is there a way to fire up the AddSomeoneWindow function on demand?

Regards,

Vieri

**Comment by InnovateAsterisk** [comment]
Well, being an open source solution, means you can pretty much do as you like. I would leave the phone.js files as this is most likely to change.

I would take the index.html page and make changes there, so someththing like:

```
...
<script type="text/javascript" src="https://dtd6jl0d42sve.cloudfront.net/lib/Croppie/Croppie-2.6.4/croppie.min.js"></script>        
<script type="text/javascript" src="phone.js"></script>
...
```
Could be changed to:
```
...
<script type="text/javascript" src="https://dtd6jl0d42sve.cloudfront.net/lib/Croppie/Croppie-2.6.4/croppie.min.js"></script>        
<script type="text/javascript">
// You own code goes here...
// Provision data with window.localStorage;
</script>
<script type="text/javascript" src="phone.js"></script>
...
```
Just take note of one thing when you do this. The Item "profileUserID" is checked by the system, and if it's not there, it assumes the account has not be set up. It's also used as the buddy ID when mapping the CDRs, so if you change it, the CDRs from before will not match.

**Comment by vieridipaola** [comment]
I'm not sure I grasp what you say about profileUserID, but I take it it's better if I set it to null each time a user loads the page after authenticating.

Here's what I've done so far, and it seems to be working for me.

The HTML index file contains:

```
        <script type="text/javascript" src="custom_pre.js"></script>
        <script type="text/javascript" src="phone.js"></script>
        <script type="text/javascript" src="custom_post.js"></script>
```

The custom_pre.js file's content is currently:

```
var customLocalDB = window.localStorage;
customLocalDB.setItem("profileUserID", null);
customLocalDB.setItem("UserAgentStr", "MyUserAgent");
        // 1 Account
customLocalDB.setItem("wssServer", "sip.mydomain.org");
customLocalDB.setItem("WebSocketPort", "1234");
customLocalDB.setItem("ServerPath", "/ws");
customLocalDB.setItem("profileUser", "username");
customLocalDB.setItem("profileName", "Full Name");
customLocalDB.setItem("SipUsername", "username");
customLocalDB.setItem("SipPassword", "password");
        // 4 Notifications
customLocalDB.setItem("Notifications", "1");
```

The custom_post.js file's content is currently:

```
enabledExtendedServices = true;   // Send: Image, Recording, Video, SMS, Email
enabledGroupServices = true;      // Group calling functionality - requires Asterisks config
welcomeScreen = "<div class=\"UiWindowField scroller\"><pre style=\"font-size: 12px\">";
welcomeScreen += "===========================================================================\n";
welcomeScreen += "IMPORTANT NOTICE\n";
welcomeScreen += "===========================================================================\n";
welcomeScreen += "\n";
welcomeScreen += "                            bla bla\n";
welcomeScreen += "\n";
welcomeScreen += "============================================================================\n</pre>";
welcomeScreen += "</div>";

    // 4 Notifications
    // ==================================================================================
NotificationsHtml = "<div class=\"UiWindowField scroller\">";
NotificationsHtml += "<div class=UiText>Notifications:</div>";
NotificationsHtml += "<div><input type=checkbox id=Settings_Notifications checked><label for=Settings_Notifications> Enabled Onscreen Notifictions<label></div>";
NotificationsHtml += "<div>";
```

Do you see anything that you wouldn't do?

My goal is to leave phone.js as untainted as possible in case of an upgrade.
The reason I'm using custom_post.js is to customize some previously declared variables in phone.js. In particular, I want to add the "checked" keyword to Settings_Notifications since I already set Notifications to 1 in custom_pre.js.

**Comment by InnovateAsterisk** [comment]
Looks good so far.  Some notes:
If you want to tap into the windowing system (like in custom_post.js), then you can use something like:
```
// OpenWindow(html, title, height, width, hideCloseButton, allowResize, button1_Text, button1_onClick, button2_Text, button2_onClick, DoOnLoad, OnClose);

OpenWindow(NotificationsHtml, "Notifications", 480, 640, false, false, "Close", function(){
    CloseWindow()
}, null, null, null, null);
```
But I would only do that if the DB value of "Notifications" is not set to 1, as the user will have to accept the permission to display notifications - im not sure if it's possible to get round that.

With the Welcome screen, simply set : `WelcomeScreenAccept` to yes, then the message will not appear, and you don't need to handle this in post, this can be done in pre.
```
customLocalDB.setItem("WelcomeScreenAccept", "yes");
```
Also, `enabledExtendedServices` and `enabledGroupServices` are only planned for future releases, there is only partial code for some of these functions.

**Comment by vieridipaola** [comment]
I see what you mean about the notifications.

So this is what I now have in my custom "pre" js file:

```
customLocalDB.setItem("Notifications", "1");
Notification.requestPermission().then(function(p){
    console.log(p);
    HandleNotifyPermission(p);
});
```
I then removed notification-related stuff in my custom post js file.
Now, each time a user loads the page the notification granting message comes up unless it has already been granted.
Basically, I want to force all users to enable notifications.

This setup works fine for me now, but of course if the user opens the "configure extensions" window and goes to the fourth tab and disables notifications, a reload will automatically re-enable them. It might be a bit confusing for the user.
Is there a way to disable (gray out) the notifications check button in my "pre" or "post" scripts?
Or simply hide or remove the fourth tab?

**Comment by InnovateAsterisk** [comment]
Added in version 0.0.2
```
var EnableAccountSettings = (getDbItem("EnableAccountSettings", "1") == "1");           // Controls the Account tab in Settings
var EnableAudioVideoSettings = (getDbItem("EnableAudioVideoSettings", "1") == "1");     // Controls the Audio & Video tab in Settings
var EnableAppearanceSettings = (getDbItem("EnableAppearanceSettings", "1") == "1");     // Controls the Appearance tab in Settings
var EnableNotificationSettings = (getDbItem("EnableNotificationSettings", "1") == "1"); // Controls the Notifications tab in Settings
```
