### ISSUE TITLE
Firefox - features that doesn't work

### ISSUE THREAD

**Issue by prathibhacdac** [InnovateAsterisk/Browser-Phone#251]
Which feature of browser phone doesn't work with firefox as it mentioned most features work?

**Comment by InnovateAsterisk** [comment]
Firefox and Safari both don't support the setSinkId - an "experimental" feature sure, but one that can be beneficial in this case.
https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/setSinkId

Many people have dismissed this feature, as they cant think of a use-case for it. In the browser phone it's very useful to be able to direct audio out to a particular audio output. Imagine if you are using headphones, but want the ring tone to play out via the main speakers. setSinkId can do that. Also, what about using headphones, and then changing to a more suitable conference audio device, without having to fiddle with the audio settings. Personally, i think it's extremely valuable, I have no idea why it's still experimental, or not adopted by all browsers. 

Also, Firefox doesn't support Dictation.
