### ISSUE TITLE
status

### ISSUE THREAD

**Issue by prathibhacdac** [InnovateAsterisk/Browser-Phone#258]
For all the users the status is shown as "No status".

**Comment by prathibhacdac** [comment]
![Screenshot (186)](https://user-images.githubusercontent.com/26375790/165068256-60f9eddb-0117-4548-81ac-78ef61f5e577.png)

**Comment by InnovateAsterisk** [comment]
You must set it. Settings > Set Status 

<img width="363" alt="image" src="https://user-images.githubusercontent.com/58937573/165700882-9f677dc9-164c-4222-b94b-f0f51a9d69aa.png">

**Comment by prathibhacdac** [comment]
I've set the status. Still it is shown as No Status on the user who has subscribed to this user.
