### ISSUE TITLE
incoming call window does not close when no answer

### ISSUE THREAD

**Issue by vieridipaola** [InnovateAsterisk/Browser-Phone#259]
Hi,

When receiving a call and not answering it, the caller window stays open even when it stops ringing.
Is it expected behavior or should the window close as soon as ringing stops (function teardownsession)?

**Comment by InnovateAsterisk** [comment]
I believe the incoming call window was removed, all incoming ringing lines show as lines on the left, and if you are not on another call, the call line UI shows.

**Comment by vieridipaola** [comment]
Solved
