### ISSUE TITLE
Auto Answer with Video

### ISSUE THREAD

**Issue by vieridipaola** [InnovateAsterisk/Browser-Phone#26]
Hi,

The "Auto Answer" feature only answers an audio call.
Is it possible to Auto Answer with Video?

Regards,

Vieri

**Comment by InnovateAsterisk** [comment]
I'll update that. If the incoming call is with video, it will assume the intended action to accept the call with video.

**Comment by vieridipaola** [comment]
Thanks a lot for considering that.
A side note on this: is it possible to switch to video call on an ongoing audio call (without redialing of course)? I haven't seen the option to do so, so I guess it's not implemented yet.

**Comment by InnovateAsterisk** [comment]
I read somewhere this this is not possible on Asterisk, so I didn't try... I can take a look,  but i'm doubtful.
