### ISSUE TITLE
UI space between avatar and call option buttons

### ISSUE THREAD

**Issue by vieridipaola** [InnovateAsterisk/Browser-Phone#261]
Hi,

When making a call there's a lot of empty space between the number + avatar image and the call option buttons.
I need the buttons to be readily accessible, especially the "send DTMF window" whose button is hidden and needs to be expanded.
The earlier Browser-Phone versions had all these buttons on display right next to the dialed number.
Anyway, menu/button expansion notwithstanding, it would help a great deal if there were less empty space between the buttons and the avatar. Or maybe even put the avatar below the buttons so that these can be right next to the dialed number.

Thanks

**Comment by InnovateAsterisk** [comment]
Fair point. 
I can see the extra click/tap can slow things down a bit, but makes for a neater UI.

It was assumed that the **mute**, **hold** and **transfer** are the most common options, but it's fair to say that, if you are dialling out, **DTMF** may be more useful (without the extra click) than say **transfer**. 

What I could do is; on an outbound call - swap transfer for DTMF, and for an inbound call, have then is they are now.

**Comment by vieridipaola** [comment]
> What I could do is; on an outbound call - swap transfer for DTMF, and for an inbound call, have then is they are now.

That sounds OK.
Do you think that the call option buttons could be placed above the avatar picture (with a config option, eg. phoneOptions)?
Or somehow reduce the amount of space between the picture and the option buttons.
I'm asking because on some smaller screens it is inconvenient to scroll down to reach and act upon the buttons. Ideally, one would not want to scroll at all in order to use the buttons.
Maybe even a phoneOptions setting to disable viewing the avatar picture within an outgoing or incoming call window (avatars in the buddy list are OK)? That way the buttons would be right on top.

**Comment by InnovateAsterisk** [comment]
Scroll? 
The Call UI was specifically designed without any scrolling on even the smallest screen. (except for the graphs and the events)

Can you send a screenshot of what you see

**Comment by InnovateAsterisk** [comment]
Check that your UI looks the same as mine: 
https://github.com/InnovateAsterisk/Browser-Phone/blob/master/Screenshots/UI_Mobilr_Call_Light.jpg

**Comment by vieridipaola** [comment]
Mine is different. I include the app within a frame like so:

[](https://drive.google.com/file/d/1iX8SZZvU626paBSweL2VNR_UHIpDMrvE/view?usp=sharing)

**Comment by vieridipaola** [comment]
Even if I open the app without a frame on a desktop with Firefox I'm still seeing a lot of space between the avatar and the buttons . I also notice a small scroll as can be seen a little in this screenshot:

https://drive.google.com/file/d/1U8gGEO5vgKybcrUMgku8PFIbHzWDzQmc/view?usp=sharing

**Comment by InnovateAsterisk** [comment]
You can remove the avatar during a call with a simple CSS override:
```
.inCallAvatar{ display:none }
.CallPictureUnderlay{ display:none }
```

The Call Control Buttons are "anchor down", so no matter how the screen is sized, the call controls are always supposed to sit down, and how of the way.

I'm just checking the code now - the "space" (large space in the middle) was supposed to be for CRM - but cant seem to find the container - I'll do an update on that.

**Comment by InnovateAsterisk** [comment]
>  I also notice a small scroll as can be seen a little in this screenshot:

Strange, will double check Firefox (its not in Chrome)

**Comment by edimondi** [comment]
I think older version was better in my opinion because all buttons were there and easy to access

**Comment by InnovateAsterisk** [comment]
> I think older version was better in my opinion because all buttons were there and easy to access

Yes, but they didn't fit on smaller screens. You will find after the next change, the useful options will be available, and easy to access.
