### ISSUE TITLE
Not Re Registered after internet failover connection

### ISSUE THREAD

**Issue by edimondi** [InnovateAsterisk/Browser-Phone#274]
hi, sometimes when my internet connection switches from primary to backup and than again to primary connection the browser phone doesnt Register it says Sending Registration...
![sendingreg](https://user-images.githubusercontent.com/68370691/168586497-84f68ed4-3eaf-4ae9-af83-88fc485dfc48.jpg)

phone.js:1595 ReRegistered!
sip-0.20.0.min.js:2 Mon May[ 16 2022 03](sip: 16 2022 03):33:52 GMT-0800 (Alaska Daylight Time) | sip.Registerer | Waiting toggled to false
sip-0.20.0.min.js:2 Mon May[ 16 2022 03](sip: 16 2022 03):35:01 GMT-0800 (Alaska Daylight Time) | sip.Registerer | Waiting toggled to true
sip-0.20.0.min.js:2 Mon May[ 16 2022 03](sip: 16 2022 03):35:02 GMT-0800 (Alaska Daylight Time) | sip.Registerer | Registration expired
print @ sip-0.20.0.min.js:2
sip-0.20.0.min.js:2 Mon May[ 16 2022 03](sip: 16 2022 03):35:02 GMT-0800 (Alaska Daylight Time) | sip.Registerer | Registration transitioned to state Unregistered
phone.js:1428 User Agent Registration State: Unregistered
phone.js:1623 Unregistered, bye!
sip-0.20.0.min.js:2 Mon May[ 16 2022 03](sip: 16 2022 03):35:20 GMT-0800 (Alaska Daylight Time) | sip.Transport | WebSocket closed unexpectedly
print @ sip-0.20.0.min.js:2
sip-0.20.0.min.js:2 Mon May[ 16 2022 03](sip: 16 2022 03):35:20 GMT-0800 (Alaska Daylight Time) | sip.Transport | WebSocket closed wss://[mydomain:4987/ws](http://mydomain:4987/ws) (code: 1006)
sip-0.20.0.min.js:2 Mon May[ 16 2022 03](sip: 16 2022 03):35:20 GMT-0800 (Alaska Daylight Time) | sip.Transport | Transitioned from Connected to Disconnected
phone.js:1471 WebSocket Connection Failed: Error: WebSocket closed wss://[mydomain:4987/ws](http://mydomain:4987/ws) (code: 1006)
    at at.onWebSocketClose (sip-0.20.0.min.js:2:226066)
    at WebSocket.<anonymous> (sip-0.20.0.min.js:2:223454)
onTransportConnectError @ phone.js:1471
phone.js:1515 Waiting to Re-connect... 3 Attempt remaining 999
phone.js:1497 ReConnecting to WebSocket...
sip-0.20.0.min.js:2 Mon May[ 16 2022 03](sip: 16 2022 03):35:24 GMT-0800 (Alaska Daylight Time) | sip.Transport | Connecting wss://[mydomain:4987/ws](http://mydomain:4987/ws)
sip-0.20.0.min.js:2 Mon May[ 16 2022 03](sip: 16 2022 03):35:24 GMT-0800 (Alaska Daylight Time) | sip.Transport | Transitioned from Disconnected to Connecting
sip-0.20.0.min.js:2 Mon May[ 16 2022 03](sip: 16 2022 03):35:24 GMT-0800 (Alaska Daylight Time) | sip.Transport | WebSocket opened wss://[mydomain:4987/ws](http://mydomain:4987/ws)
sip-0.20.0.min.js:2 Mon May[ 16 2022 03](sip: 16 2022 03):35:24 GMT-0800 (Alaska Daylight Time) | sip.Transport | Transitioned from Connecting to Connected
phone.js:1455 Connected to Web Socket!
phone.js:1500 Reconnected to Web Socket!
phone.js:1455 Connected to Web Socket!
phone.js:1568 Registered!
phone.js:1532 Sending Registration...
sip-0.20.0.min.js:2 Mon May[ 16 2022 03](sip: 16 2022 03):35:25 GMT-0800 (Alaska Daylight Time) | sip.Registerer | An attempt was made to send a REGISTER request while a prior one was still in progress. RFC 3261 requires UAs MUST NOT send a new registration until they have received a final response from the registrar for the previous one or the previous REGISTER request has timed out. Note that if the transport disconnects, you still must wait for the prior request to time out before sending a new REGISTER request or alternatively dispose of the current Registerer and create a new Registerer.
print @ sip-0.20.0.min.js:2
sip-0.20.0.min.js:2 Uncaught (in promise) Error: REGISTER request already in progress, waiting for final response
    at he.register (sip-0.20.0.min.js:2:110877)
    at Register (phone.js:1535:26)
    at phone.js:1466:13
sip-0.20.0.min.js:2 Mon May[ 16 2022 03](sip: 16 2022 03):35:34 GMT-0800 (Alaska Daylight Time) | sip.user-agent-client | User agent client request timed out. Generating internal 408 Request Timeout.
print @ sip-0.20.0.min.js:2
sip-0.20.0.min.js:2 Mon May[ 16 2022 03](sip: 16 2022 03):35:34 GMT-0800 (Alaska Daylight Time) | sip.Registerer | Failed to register, status code 408
print @ sip-0.20.0.min.js:2
sip-0.20.0.min.js:2 Mon May[ 16 2022 03](sip: 16 2022 03):35:34 GMT-0800 (Alaska Daylight Time) | sip.Registerer | Waiting toggled to false
theme.css:1          Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by InnovateAsterisk** [comment]
Hmm, I see the registration loop appear to be in an overlap.  

> An attempt was made to send a REGISTER request while a prior one was still in progress. RFC 3261 requires UAs MUST NOT send a new registration until they have received a final response from the registrar for the previous one or the previous REGISTER request has timed out. Note that if the transport disconnects, you still must wait for the prior request to time out before sending a new REGISTER request or alternatively dispose of the current Registerer and create a new Registerer.
