### ISSUE TITLE
Distinguish connection server and username domain

### ISSUE THREAD

**Issue by racoonman** [InnovateAsterisk/Browser-Phone#278]
Hello,

I am trying to use your softphone with one of my providers. But I have a problem.

In the case of my SIP account, on one side I have the server where I have to connect and on the other side my SIP uri in which the server is not the same.

For example:
Connection address for websocket: wss://ws.provider.com:444
SIP uri: 100@mybussines.com

I understand that this scenario is fairly common in situations where the provider has a single platform where extensions from different PBXs are registered in the same endpoint and isolated by domain.

I have reviewed the code and I see that the same variable is used for the 2 options (inside the CreateUserAgent method in phone.js file)

Would it be possible to add an option in the account configuration so that these values can be indicated?

If you don't want to "complicate" the account configuration, maybe an interesting option would be to detect if the SIP Username contains an '@'. If it does, use the value for the sip URI and if it does not, concatenate the indicated service as it is currently done.

What do you think about this idea?

**Comment by InnovateAsterisk** [comment]
Nice idea
