### ISSUE TITLE
Error in call

### ISSUE THREAD

**Issue by KatiaSishost** [InnovateAsterisk/Browser-Phone#293]
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'getSenders')

**Comment by InnovateAsterisk** [comment]
‘getSenders’ will get the streams (audio and video) from the peer connection. If the peer connection is undefined, it’s because the call failed for some reason. If you have a log from the console, it will help to identify the cause.

**Comment by danilgorda** [comment]
@KatiaSishost, I have set the 'rtcpMuxPolicy':'negotiate' in "function CreateUserAgent()" and then
call connected successfully
