### ISSUE TITLE
video calls and optional input

### ISSUE THREAD

**Issue by vieridipaola** [InnovateAsterisk/Browser-Phone#30]
Hi,

Currently, it seems that for a one-on-one video call to succeed, both webrtc clients need to have a webcam + microphone available as input devices. Would it make sense to ignore an input web cam if it's not connected, thus allowing a video call with video only one way? For instance, browser A with a camera video calls browser B without a camera. Currently, if B "answers with video", the call fails and hangs up. If B answers "with audio only" then all's well.
So maybe, B could answer with video, and A would stream it's video source to B even though B wouldn't stream any video to A, just audio.

I don't know if it's hard to implement, but it's just one of those things that might come in handy.

**Comment by InnovateAsterisk** [comment]
The problem would come if you never intended to receive a video call, but now someone is calling you "with video". How would you accept this call as a video call if you don't even have your webcam plugged in. I have an idea for this.

**Comment by InnovateAsterisk** [comment]
There isn't a way to initialise a video call (make or receive), without a webcam. This is an odd limitation imposed by all browsers... the assumptions is that if you are making a video call, you are using a webcam... however there are multiple media streams; video, screen, canvas and webcam. It appears the only way to setup a call is to use the video: true constraint, then switch that stream to another source, say a canvas.

Asterisk doesn't seem to be able to go from an audio only, to an audio&video call. So for now, I have fixed a the video call handling as follows:
1) I have added Device Detection code, that is constantly checking for devices. If you add say a webcam at any time, this script picks it up.
2) If you make a video call, but don't have a webcam, it downgrades the call to audio.
3) If you receive a video call, and try to accept with video, but don't have a webcam, it downgrades the call to audio only.
4) If you suddenly add a webcam, the device becomes available to the next call.

P.S. If the user truly doesn't have a webcam, (and it wasn't just that it was unplugged,) and the requirement is to enable video calling even if it will be one-sided - then a software webcam may do the trick.
https://superuser.com/questions/681386/webcam-driver-that-uses-an-image-or-video-file-as-the-video-source

**Comment by vieridipaola** [comment]
Great job!
Yeah, that limitation is a bit silly, but I suppose browsers will change their behavior over time.
In the meantime however, your workaround is great and should be more than enough for most cases.

I see that the OBS Virtualcam "hack" is rather interesting. In fact, a lot of users can require to see their peer but not the other way around. In my specific case, I might have doctors who require seeing their patients in a "telemedicine" video call, but they might not have access to a PC or laptop with a webcam. This usually doesn't happen, but it might. So the virtual camera showing the MD's photo for example would be a nice solution.
And now deploy that software on every PC without a camera... ;-(

Thanks again!
