### ISSUE TITLE
Doesnt register correctly. 

### ISSUE THREAD

**Issue by Beatific-Angel** [InnovateAsterisk/Browser-Phone#300]
web phone 's location should be same with freepbx, asterisk?

**Comment by Beatific-Angel** [comment]
and I found one problem
if I try register in two computer with same credentials, one is registered and one is failed error message
what is problem?
![image](https://user-images.githubusercontent.com/64799935/179944469-b116362d-a167-4bed-980d-9ccea0d94877.png)
![image](https://user-images.githubusercontent.com/64799935/179945280-6019c8da-a63d-461b-baaa-aed2f2562379.png)

**Comment by InnovateAsterisk** [comment]
> web phone 's location should be same with freepbx, asterisk?

FreePBX is just a web based GUI for the .conf files that configure Asterisk. It is not part of the Signalling, and once the config is applied to Asterisk its not part of Asterisk either.

> if I try register in two computer with same credentials, one is registered and one is failed error message
what is problem?

The error actually seems to be on the WebSocket side. In Asterisks the WebSockets are received via the HTTP mini server (built into asterisk). There may be some settings that are badly set there - please check that more than 1 connection can connect to the http / web socket server.
Is there anything that appears on the CLI at the time of failure?

**Comment by Beatific-Angel** [comment]
> FreePBX is just a web based GUI for the .conf files that configure Asterisk. It is not part of the Signalling, and once the config is applied to Asterisk its not part of Asterisk either.

my mean is phone should be same locate with asterisk?

**Comment by Beatific-Angel** [comment]
> Is there anything that appears on the CLI at the time of failure?
current I checking now,
I can see error logs in console window of chrome.
but I can not see any problem in cli.
