### ISSUE TITLE
profileUserID and uID()

### ISSUE THREAD

**Issue by vieridipaola** [InnovateAsterisk/Browser-Phone#31]
Hi,

I'd like to understand how profileUserID and uID() work.
The problem I'm facing is that unfortunately some users don't log out of their OS session, so basically several users might end up "sharing" an OS user session/profile even though I set up LDAP/AD authentication to access Browser-Phone. Authentication works fine, and each user registers with his/her Asterisk extension. The problem is that all "Browser-Phone users" share the same buddy list, among other parameters. So, in order to address this, I wonder if I just need to set myself the value of profileUserID to a value derived from the LDAP/AD user login (eg. username+random_string).

Any thoughts?

**Comment by InnovateAsterisk** [comment]
The profileUserID only gets created once, when you first create registration settings, from then its like your own ID, and used to match CDR's with your buddies (who also get a unique ID). Typically in a database driven system user ids are mostly used rather than names etc, this is the same.

I have not tried this, but if you set a new id (say in _pre.js) for each user based on a constant LDAP id, it could create the same kind of effect as profiles. If you mess it all up, no worries, just clear out the Local Storage and the IndexedDB (In the Developer Tools)

When making this app, the idea was that I wanted it to work without any database or additional dependencies... in other words you could have a very simple Asterisk server environment and this extension would still work because it's completely self contained.

**Comment by vieridipaola** [comment]
...but shouldn't **UserBuddiesJson** contain a reference to **profileUserID** so that only the buddies associated with a given "login" or profile are displayed? Of course, _function_ **UpdateBuddyList**_(filter)_ would have to display only those buddies with the right **profileUserID**.

From a security point of view, it's null because anyone can go to the devtools and enmerate the buddy list (and see the ones that may have different ids). However, from a purely practical POV, it would do the trick as several properly "logged on" users with their unique  profileUserIDs would only see their own buddy list.

**Comment by InnovateAsterisk** [comment]
The idea was for people to take the index.html and change it to index to php, or .aspx or something with a server side process that could check authentication. No attempt was made to secure the application, and its relies purely user profiles that Windows, MacOS, etc have that separates user sessions and that follow into all the web browsers... so User1 Browser Local Storage is different to User2 Browser Local Storage. Then, the fact that people can go to their devtools and manipulate their own settings only impacts their own settings.

It wasn't designed to have multiple profileUserIDs.

The buddy list (UserBuddiesJson) is global to your session.

**Comment by vieridipaola** [comment]
Yes, I understand what you're saying. That's exactly what I did. I enabled LDAP authentication in my Apache server, and I also wrote a php script (in my case a "pre" php script that loads rigth before phone.js and sets things up according to the user login values). I also know that the buddy list is global to the session.

It is absolutely not my intention to change the design of this program (that I like very much). The only thing I'm suggesting is a trivial change so that I can filter the buddy list according to the user who logs in. Please have a look at this patch:

```
--- phone.original.js   2020-06-09 18:10:35.034098297 +0200
+++ phone.js    2020-06-11 23:52:38.409599977 +0200
@@ -353,7 +353,8 @@
                     Position: "",
                     Description: $("#AddSomeone_Desc").val(),
                     Email: $("#AddSomeone_Email").val(),
-                    MemberCount: 0
+                    MemberCount: 0,
+                    profileUserID: profileUserID
                 }
             );
             var buddyObj = new Buddy("contact", id, $("#AddSomeone_Name").val(), "", $("#AddSomeone_Mobile").val(), $("#AddSomeone_Num1").val(), $("#AddSomeone_Num2").val(), dateNow, $("#AddSomeone_Desc").val(), $("#AddSomeone_Email").val());
@@ -378,7 +379,8 @@
                     Position: $("#AddSomeone_Desc").val(),
                     Description: "",
                     Email: $("#AddSomeone_Email").val(),
-                    MemberCount: 0
+                    MemberCount: 0,
+                    profileUserID: profileUserID
                 }
             );
             var buddyObj = new Buddy("extension", id, $("#AddSomeone_Name").val(), $("#AddSomeone_Exten").val(), $("#AddSomeone_Mobile").val(), $("#AddSomeone_Num1").val(), $("#AddSomeone_Num2").val(), dateNow, $("#AddSomeone_Desc").val(), $("#AddSomeone_Email").val());
@@ -1643,7 +1645,8 @@
                     Position: "",
                     Description: "",
                     Email: "",
-                    MemberCount: 0
+                    MemberCount: 0,
+                    profileUserID: profileUserID
                 }
             );
             buddyObj = new Buddy("contact", id, callerID, "", "", did, "", dateNow, "", "");
@@ -1668,7 +1671,8 @@
                     Position: "",
                     Description: "",
                     Email: "",
-                    MemberCount: 0
+                    MemberCount: 0,
+                    profileUserID: profileUserID
                 }
             );
             buddyObj = new Buddy("extension", id, callerID, did, "", "", "", dateNow, "", "");
@@ -3634,14 +3638,10 @@
     // Make new contact of its not there
     if(buddyObj == null)
     {
-        // Note: typically incoming numbers are long, about 10+
-        // but also typically extension numbers aer short, about 3 or 4
-        // making this identifyer 6, should be comfortable.
-
         var json = JSON.parse(localDB.getItem("UserBuddiesJson"));
         if(json == null) json = InitUserBuddies();

-        if(did.length > 6){
+        if(did.length > DidLength){
             // Add Regular Contact
             var id = uID();
             var dateNow = utcDateNow();
@@ -3660,7 +3660,8 @@
                     Position: "",
                     Description: "",
                     Email: "",
-                    MemberCount: 0
+                    MemberCount: 0,
+                    profileUserID: profileUserID
                 }
             );
             buddyObj = new Buddy("contact", id, callerID, "", "", did, "", dateNow, "", "");
@@ -3685,7 +3686,8 @@
                     Position: "",
                     Description: "",
                     Email: "",
-                    MemberCount: 0
+                    MemberCount: 0,
+                    profileUserID: profileUserID
                 }
             );
             buddyObj = new Buddy("extension", id, callerID, did, "", "", "", dateNow, "", "");
@@ -6127,20 +6129,22 @@

     console.log("Total Buddies: " + json.TotalRows);
     $.each(json.DataCollection, function (i, item) {
-        if(item.Type == "extension"){
-            // extension
-            var buddy = new Buddy("extension", item.uID, item.DisplayName, item.ExtensionNumber, item.MobileNumber, item.ContactNumber1, item.ContactNumber2, item.LastActivity, item.Position, item.Email);
-            AddBuddy(buddy, false, false);
-        }
-        else if(item.Type == "contact"){
-            // contact
-            var buddy = new Buddy("contact", item.cID, item.DisplayName, "", item.MobileNumber, item.ContactNumber1, item.ContactNumber2, item.LastActivity, item.Description, item.Email);
-            AddBuddy(buddy, false, false);
-        }
-        else if(item.Type == "group"){
-            // group
-            var buddy = new Buddy("group", item.gID, item.DisplayName, item.ExtensionNumber, "", "", "", item.LastActivity, item.MemberCount + " member(s)", item.Email);
-            AddBuddy(buddy, false, false);
+        if(item.profileUserID == profileUserID){
+           if(item.Type == "extension"){
+               // extension
+               var buddy = new Buddy("extension", item.uID, item.DisplayName, item.ExtensionNumber, item.MobileNumber, item.ContactNumber1, item.ContactNumber2, item.LastActivity, item.Position, item.Email);
+               AddBuddy(buddy, false, false);
+           }
+           else if(item.Type == "contact"){
+               // contact
+               var buddy = new Buddy("contact", item.cID, item.DisplayName, "", item.MobileNumber, item.ContactNumber1, item.ContactNumber2, item.LastActivity, item.Description, item.Email);
+               AddBuddy(buddy, false, false);
+           }
+           else if(item.Type == "group"){
+               // group
+               var buddy = new Buddy("group", item.gID, item.DisplayName, item.ExtensionNumber, "", "", "", item.LastActivity, item.MemberCount + " member(s)", item.Email);
+               AddBuddy(buddy, false, false);
+           }
         }
     });


```

Correct me if I'm wrong, but I don't think it will affect the way you conceived the program. It will behave the same way except that in my special case I will be able to populate the buddy list differently according to user login (because profileUserID will be set accordingly upon authentication).

Please let me know if I'm completely off-track or if the code change I'm asking for is unacceptable.

Thanks

**Comment by vieridipaola** [comment]
BTW, lease note the change for

`if(did.length > DidLength){`

in the above patch. It has nothing to do with this issue, but I noticed it after my previous post.

Do I need to create a new issue for this?

**Comment by InnovateAsterisk** [comment]
The latest version 0.0.2 now uses a buddies format as follows:
< profileUserID>-Buddies
So one user buddy list will be different to the other, but the other settings like AutoAnswer are shared. If you want these to be per user profile you must have a different windows login.
