### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by prathibhacdac** [InnovateAsterisk/Browser-Phone#314]
You tried to make a video call(Not acceptable here)
 chan_sip.c:10405 process_sdp: Received SAVPF profle in audio offer but AVPF is not enabled, enabling: audio 49256 UDP/TLS/RTP/SAVPF 109 9 0 8 101
[Aug 30 14:48:16] WARNING[28135][C-000002ad]: chan_sip.c:10804 process_sdp: Rejecting secure audio stream without encryption details: audio 49256 UDP/TLS/RTP/SAVPF 109 9 0 8 101

I am using autocreatepeer=yes in sip.conf to allow everyone. This doesn't require password. But browser phone mandatorily requires a password to be entered.

**Comment by prathibhacdac** [comment]
You tried to make a video call(Forbidden). sometimes getting this error as well.

**Comment by prathibhacdac** [comment]
There will be thousands of webRTC clients and it will be impossible to create credentials for each one. Thats I've gone for autocreatepeer option.

**Comment by InnovateAsterisk** [comment]
> You tried to make a video call(Not acceptable here)
chan_sip.c:10405 process_sdp: Received SAVPF profle in audio offer but AVPF is not enabled, enabling: audio 49256 UDP/TLS/RTP/SAVPF 109 9 0 8 101
[Aug 30 14:48:16] WARNING[28135][C-000002ad]: chan_sip.c:10804 process_sdp: Rejecting secure audio stream without encryption details: audio 49256 UDP/TLS/RTP/SAVPF 109 9 0 8 101

You are not creating a web socket peer. I see you are using chan_sip in this case you have to use:
```
[webrtc](!)
transport=wss
allow=opus,ulaw,vp9,vp8,h264
encryption=yes
avpf=yes
force_avp=yes
icesupport=yes
rtcp_mux=yes
dtlsenable=yes
dtlsverify=fingerprint
dtlscertfile=/home/pi/certs/raspberrypi.pem
dtlscafile=/home/pi/ca/InnovateAsterisk-Root-CA.crt
dtlssetup=actpass
```

**Comment by InnovateAsterisk** [comment]
> You tried to make a video call(Forbidden). sometimes getting this error as well.

You will have to submit the error that shows on the Asterisk CLI in this case,

**Comment by InnovateAsterisk** [comment]
> There will be thousands of webRTC clients and it will be impossible to create credentials for each one. Thats I've gone for autocreatepeer option.

It doesn’t sound like you are using this project in its intended use. Can you explain your use case?

**Comment by prathibhacdac** [comment]
Using this project between call responders and mobile data terminal fitted in emergency response vehicles. There will be 1000 to max 5000 vehicles in each state. 1 or 2 call responders to attend video calls.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by InnovateAsterisk** [comment]
If the url that you use for the browser phone is public, you will probably want to restrict access to it, but I agree with you, that individually handing out sip details can be painful and could expose your pbx  depending on how it’s configured. 

I would only ever use autocreatepeer if the server was locked down with ip. 

If I may make a suggestion, I would convert the index.html into an index.php and have the server side script automatically generate a peer, and random password in a database, and parse these details to the font-end. Then when the client code (JavaScript) fires it can have the sip detail from the database on hand. You can also provision all sorts of settings and client information at this point. Even tho the sip details will be available in the source code of the page, this much more difficult to obtain for the average person, and even if this becomes known - you could expire the sip details making them useless if somehow obtained.

it also takes care of the possibility of thousands of accounts, as this is no problem for a database and php.

**Comment by prathibhacdac** [comment]
Will you create the index.php?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by InnovateAsterisk** [comment]
No, I don’t have time for this.

**Comment by prathibhacdac** [comment]
> > You tried to make a video call(Forbidden). sometimes getting this error as well.
> 
> You will have to submit the error that shows on the Asterisk CLI in this case,

 NOTICE[31846][C-000002c4]: chan_sip.c:26365 handle_request_invite: Failed to authenticate device "prathibha" <sip:10104@bp.erss.in>;tag=ud76vh7hgu

**Comment by prathibhacdac** [comment]
> the sip detail from the database on hand.

Can you explain a bit more. How does the authentication take place with the asterisk server?

**Comment by InnovateAsterisk** [comment]
You could do something like this:

index.php
```(php)
<?php
header('Expires: Sun, 01 Jan 2014 00:00:00 GMT');
header('Cache-Control: no-store, no-cache, must-revalidate, max-age=0');
header('Cache-Control: post-check=0, pre-check=0', false);
header('Pragma: no-cache');

// Other PHP stuff can go here. eg connect to database etc

<!DOCTYPE html>
<html>
...
        <!-- Provisioning Script -->
        <script type="text/javascript" id="ProvisioningScript">
            var phoneOptions = {
                profileUser: "123",
                profileName: "<?php echo(addslashes($LoginName)) ?>",
                wssServer: "192.168.88.1",
                WebSocketPort: "4443",
                ServerPath: "/ws",
                SipUsername: "<?php echo(addslashes($Username)) ?>",
                SipPassword: "<?php echo(addslashes($Password)) ?>",
                ...
                // Other default values can go here 
            }
        </script>
...
</html>

```

This would make the phone use these options at startup even if the local storage has something else.

**Comment by prathibhacdac** [comment]
How will asterisk know these dynamically created IDs?

**Comment by InnovateAsterisk** [comment]
Well, in the PHP code, you would actually create (add Row in the database) the extension. Because the PHP work is done by the time the front-end code executes, as the javascript initiates the register command, the row is already in the database to use. 
Of course this does require you to use Asterisk RealTime for Endpoints.

**Comment by prathibhacdac** [comment]
I'm passing the username and sip id through the url.

**Comment by InnovateAsterisk** [comment]
I'm generally not a fan of using url's for any kind of personal information. Remember that url's form part of your browsers history, and unless you are very good at cleaning up, you will be leaking this information. 

Some sort of local storage is better, but... to use this software commercially, it would be best that only a token is used, that the server can validate and refer to actual data.

**Comment by prathibhacdac** [comment]
> reate (add Row in the database) the extension.

extension has added in the asterisk realtime database. Am I right?

**Comment by InnovateAsterisk** [comment]
Yes.
Follow this: https://wiki.asterisk.org/wiki/display/AST/Setting+up+PJSIP+Realtime
Then add your users in the required tables

**Comment by prathibhacdac** [comment]
> I'm generally not a fan of using url's for any kind of personal information. Remember that url's form part of your browsers history, and unless you are very good at cleaning up, you will be leaking this information.
> 
> Some sort of local storage is better, but... to use this software commercially, it would be best that only a token is used, that the server can validate and refer to actual data.

How to generate tokens?

**Comment by InnovateAsterisk** [comment]
A simple way would be to use the ID of the row that holds the actual data.

[/index.php?account_id=1234](/index.php?account_id=1234)

while in the db, the row with id 1234 contains the actual username and password.

**Comment by prathibhacdac** [comment]
Eg:1004 and prathibha

**Comment by InnovateAsterisk** [comment]
These are kinda basic web development skills. I can't teach you this. There is a lot of resources online for this.
https://www.geeksforgeeks.org/how-to-get-parameters-from-a-url-string-in-php/ for example

**Comment by prathibhacdac** [comment]
> I'm generally not a fan of using url's for any kind of personal information. Remember that url's form part of your browsers history, and unless you are very good at cleaning up, you will be leaking this information.
> 
> Some sort of local storage is better, but... to use this software commercially, it would be best that only a token is used, that the server can validate and refer to actual data.

**Comment by prathibhacdac** [comment]
>         
>         <script type="text/javascript" id="ProvisioningScript">
>             var phoneOptions = {
>                 profileUser: "123",
>                 profileName: "<?php echo(addslashes($LoginName)) ?>",
>                 wssServer: "192.168.88.1",
>                 WebSocketPort: "4443",
>                 ServerPath: "/ws",
>                 SipUsername: "<?php echo(addslashes($Username)) ?>",
>                 SipPassword: "<?php echo(addslashes($Password)) ?>",


This portion of the code is not working.

**Comment by InnovateAsterisk** [comment]
Whats not working? do you have an error output?

**Comment by prathibhacdac** [comment]
> > ```
> >     
> >     <script type="text/javascript" id="ProvisioningScript">
> >         var phoneOptions = {
> >             profileUser: "123",
> >             profileName: "<?php echo(addslashes($LoginName)) ?>",
> >             wssServer: "192.168.88.1",
> >             WebSocketPort: "4443",
> >             ServerPath: "/ws",
> >             SipUsername: "<?php echo(addslashes($Username)) ?>",
> >             SipPassword: "<?php echo(addslashes($Password)) ?>",
> > ```
> 
> This portion of the code is not working.

This is working now. But when I change the password, the application is not taking the changed password. Only the initial password is set in the password field of Browser Phone application.

**Comment by prathibhacdac** [comment]
require('generateRandomString.php');
//database connection details go here
$userid=$_GET['userid'];
$username=$_GET['username'];
$randomString = generateRandomString(); 

$connection_string="host={$host} port={$port} dbname={$dbname} user={$user} password={$password}";
$conn = pg_connect($connection_string);

if($conn && !empty($userid) && !empty($username)) 
{
    //echo "Connected to ".pg_host($conn);
    $sql="Select name, secret from sip_conf where name='$userid'";
    $results = pg_query($sql);
    $row_count = pg_num_rows($results);
    if($row_count == 1) 
    {
    	//$row_users = pg_fetch_array($results);
        //$randomString = $row_users['secret'];
	$sql = "update sip_conf set secret='$randomString' where name='$userid'";
        $result = pg_query($conn, $sql);
        if(!$result)
	{
		echo pg_last_error($conn);
	}
    }
    else 
    {
    	$sql = "insert into sip_conf (name, callerid, username, secret)  values('$userid', '$username <$userid>', '$username', '$randomString')";
    	$result = pg_query($conn, $sql);
    	if(!$result)
	{
        	echo pg_last_error($conn);
     	} 
    }
}
else 
{
    echo "Error in connecting to database.";
}

// Provision runtime options can go here.
            var phoneOptions = {
                loadAlternateLang: true,
		profileUser: "<?php echo(addslashes($userid)) ?>",
                profileName: "<?php echo(addslashes($username)) ?>",
                wssServer: "bp.erss.in",
                WebSocketPort: "443",
                ServerPath: "/ws",
                SipUsername: "<?php echo(addslashes($userid)) ?>",
                SipPassword: "<?php echo(addslashes($randomString)) ?>"
            }

**Comment by prathibhacdac** [comment]
If I give sip reload, it is working. Asterisk realtime dynamic database should work without reload. If I save the registration details once, then the password is not getting updated in the browser phone application.

**Comment by prathibhacdac** [comment]
rtcachefriends=no in sip.conf resolves this issue.
