### ISSUE TITLE
Number of participants in video conferences

### ISSUE THREAD

**Issue by lucas-oliver-trondsen** [InnovateAsterisk/Browser-Phone#317]
Thank you for this wonderful application ! It is much appreciated.

I have a concern regarding the maximum number of participants in a video conference. In the past, I tried to use Nextcloud Talk. It's an application that gets installed inside Nextcloud (a free and open source alternative to Dropbox, written in PHP). Nextcloud Talk allows text/audio/video conversations between logged in Nextcloud users. It uses WebRTC, like Browser Phone. However, only about 5 users can participate in video conferences, because of technical limitations which they explain in the following words:

> Talk works peer to peer, that is, each participant sends an end-to-end encrypted stream to every other participant and receives one stream per other participant. Bandwidth usage grows with the number of participants.

> A single video stream currently uses about 1 Mbit/sec and the total required bandwidth can be calculated as follows:

> `1 Mbit/s * (participants - 1)`

> This means that in a call with 5 participants, each has to send and receive about 4 Mbit/sec. Given the asymmetric nature of most typical broadband connections, it's sending video that quickly becomes the bottleneck. Moreover, decoding all those video streams puts a big strain on the system of each participant.

My question is: Does Browser Phone have the same limitation as Nextcloud Talk, or is Asterisk sending the video streams in a more efficient way, so that Browser Phone can be used with a much larger number of participants (like 20 participants) in video conferences ?

Thank you!

**Comment by InnovateAsterisk** [comment]
The browser phone, and Asterisk does work in a different way. It’s debatable what’s the better way. Remember Asterisk is a B2BUA (Back to back user agent). In this solution you make one single up stream, and multiple down streams. You can view the SDP from the network tools, but essentially in the conference app of asterisks a new stream is added to the SDP each time someone joins, triggering a re-invite to all the attendants. This is also a limitation in itself, in that the SDP can become too big. This is probably why there is a hard-code limit to 50. That and also the cpu requirements to synchronise 50 streams will probably be quite a challenge. There are other practical considerations that come in at this point too, like 50 people attempting to talk at the same time! At even a smaller number, most people would consider a different strategy like “follow talker”, in this mode one singe stream is transmitted up, and one single stream is transmitted down, to each attendant, meaning your own bandwidth requirements are minimal, but asterisks does all the heavy lifting by switching the source of the video feed to all participants based on who is talking.

**Comment by lucas-oliver-trondsen** [comment]
Thank you very much for your reply. 

I didn't know about the hard-coded limit of 50 streams added to the SDP. I only knew that in Asterisk 18 LTS and probably in other previous versions, there is a hard-coded limit of 16 streams served in SFU mode. This limits the number of participants to a video conference in SFU mode to 15: one stream is used for the audio track with the combined sound of all participants, and the other 15 streams are used for the 15 individual video streams. Fortunately, since Asterisk is free and open source, this hard-coded limit of 16 can be changed before compiling, by opening the `/usr/src/asterisk-18.0.0/third-party/pjproject/patches/config_site.h` file and changing the value of the `PJMEDIA_MAX_SDP_MEDIA` parameter from 16 to about 100. I tested changing this parameter to 99 before compiling and and it worked just fine. However, when I changed it to something over 100, like 120, it didn't work, I couldn't register the application to Asterisk.

If you know that there is an additional hard-coded limit of 50 to the number of streams added to SDP, do you happen to know in what file it is hard-coded ?

**Comment by InnovateAsterisk** [comment]
Ah, thats interesting that you are able to set this value to 99... I was under the impression it was 50. It's the same value we are talking about... but it seems that by not being able to set the number greater than 99 means that the PJSIP isn't designed to hold this value, not sure.

**Comment by lucas-oliver-trondsen** [comment]
Yes, there may have been reasons to set a hard-coded limit to the number of streams, but it seems to work very well when that limit is increased from 16 to 99. I'm really hoping that Browser Phone can handle 20 or 30 participants in video conferences, since I know Asterisk is efficient in terms of CPU and RAM usage and WebRTC in intself doesn't have restrictions to the number of participants.

You were mentioning the “follow talker” mode of Asterisk. I know about this mode, but I hoped I can have the same behavior of a Zoom conference: every participant sees all the other participants in real-time and can hear all of them, since the individual audio tracks are combined into one audio track. As I understand it, only the 'selective forwarding unit' (SFU) mode of Asterisk offers this behavior, while in "follow talker" mode, each participant sees on the screen only that user who is talking. This behavior is more convenient in terms of bandwidth usage, but may not be so comfortable for the conference participant, who will see the speakers one after the other, while not being able to see the other 'passive' participants.

Do you think that installed on proper hardware, Asterisk + Browser Phone can handle 20 or 30 participants in SFU mode ? I never tested it with more than 3 participants.

**Comment by InnovateAsterisk** [comment]
It's tricky to test so many streams, so I used StreamEcho
https://wiki.asterisk.org/wiki/display/AST/Asterisk+18+Application_StreamEcho 
The UI handles the 15 video streams quite well. I have not tested 99... Would love yo know if it works.

I will not page the videos, as its assumed that the max is 15. Other than quite small video windows (depending on your screen resolution) it should all work fine.

![Conference_SFU](https://user-images.githubusercontent.com/58937573/188897508-7b709e00-86e5-4a8e-b1b1-1496931be7dc.jpg)
![VideoWall](https://user-images.githubusercontent.com/58937573/188897741-3d5ddf76-b83e-41f6-81a6-01c29a5ff40b.jpg)
![VideoWall1](https://user-images.githubusercontent.com/58937573/188897773-c5c9ea31-c5d8-4486-9007-63a8188eb1b2.jpg)

**Comment by lucas-oliver-trondsen** [comment]
Thank you so much for this info. I didn't know I could use StreamEcho() in Asterisk to simulate multiple participants. If I run tests and find relevant results about more than 15 participants, I'll post back on this thread.

So, in principle, Asterisk + Browser Phone can handle 20 or 30 participants in SFU mode. I'm so glad to hear this. Thanks again for this info and for Browser Phone. I predict a great future for this application.

If you agree, I'll close this 'issue'.

**Comment by lucas-oliver-trondsen** [comment]
I ran some tests using StreamEcho() to simulate multiple participants and it worked with 45 participants in Firefox and 80 participants in Chromium (I use Debian 11 as operating system). I noticed that my CPU (Intel Core i5 @ 2.40 GHz × 4 ) was under heavy load while doing the tests and the image happened to freeze from time to time, so, I think the maximum number of participants depends on the browser, on the way the browser uses the system's resources and even more on the system's resources, mostly the CPU.

I want to mention that I have a modified version of Browser Phone which uses the JsSIP library instead of SIP.js. However, since SIP.js is based upon JsSIP, I think my results can be reproduced with an unmodified Browser Phone, All I did was to change the maximum number of streams before compiling Asterisk, by opening the `/usr/src/asterisk-18.0.0/third-party/pjproject/patches/config_site.h` file and changing the value of the `PJMEDIA_MAX_SDP_MEDIA` parameter from 16 to 99. As I mentioned, I haven't seen any negative side-effects of this change. Only when I changed the parameter from 16 to 120 I noticed Browser Phone couldn't register, but with 99 it was all OK and is OK, since I'm still using Asterisk with this small modification.

I would conclude that with a good desktop/laptop, Asterisk + Browser Phone can handle video conferences in SFU mode with around 80 participants and maybe more if the hardware permits. I hope future versions of Asterisk will allow increasing the maximum number of streams even further.

Thank you very much for Browser Phone. It's an incredible application.

**Comment by InnovateAsterisk** [comment]
Wow, nice! Some things come to mind:

The first thing that comes to mind is that the UI should really page or scroll the participants. With so many videos, the size of each would really be quite small. 

Another trick would be to try determine if you are the current speaker, and increase your transmission video quality (and then decrease it again when you are not). This behaviour would save all the participants quite a lot of bandwidth from participants that are not actually talking. 

I would imagine that the SDP is quite large at this point. If you want, you can play around with FreeSWITCH. Its conference does not have a limit, as it stitches all participants into a single stream, this stream is then presented to all participants. I believe this saves quite a lot of bandwidth (maybe), but certainly simplifies the SDP, UI, and client processing abilities. Apparently tho, it’s quite intense on the server CPU.

**Comment by lucas-oliver-trondsen** [comment]
In my modified version of Browser Phone, all the video tiles appear side by side with no space between them and their dimentions get indeed smaller, the more numerous they are. Yet, I didn't implement scrolling or paging, because I wanted to reproduce Zoom's behavior, as much as possible. I haven't used Zoom, but from what I see in various recorded Zoom conferences, Zoom doesn't scroll or page the video tiles. It tries to display them all at once on the screen. In my tests, even when I had 85 participants, the video tiles were small, but I could still distinguish myself in each of them, so, I consider they have acceptable clarity, at least on a 20+ inch monitor.

Increasing/decreasing the video quality based on the active/passive participants is an interesting idea and it would indeed save bandwidth.

A few years ago I tried using FreeSWITCH instead of Asterisk for my projects, since there was so much talk about FreeSWITCH and I thought I might have missed something using Asterisk instead of FreeSWITCH. However, when I tried to implement a dialplan with a loop, I realized that I had to use XML files and even write a small program, whereas in Asterisk, with a simple GotoIf(), you can implement a loop, if a condition is met. Without modifying XML files and without any programming. Therefore, since with FreeSWITCH you can do the same things as with Asterisk, but it's 5 times more difficult, and since I also had some problems with the sound, I **switched** to Asterisk definitively, and I don't regret it. I think Asterisk is the best free and open source PBX. It has a long history of success, it's written in C, it's lightweight, very flexible, and the simplicity of its dialplan language proves there are some brilliant minds behind it.

What I appreciate the most in Browser Phone is that it's well-written, well-structured, and uses the best tools for the job: Asterisk on the back-end and an elegant front-end using only jQuery (+ CSS and HTML). Today it's very hard to find a web application that hasn't been infested with Node.js.

I extended Browser Phone quite a lot, to add new functionalities. After I add a few more features, I intend to publish it as a gratis free and open source web application and make a video presentation of it. My idea is to offer a truly free and open source, self-hosted alternative to Zoom/Skype, with much more features than Jitsy and Big Blue Button, more efficient and easier to install.

If you like the video presentation, would you be interested in a collaboration ? In the sense that I might receive requests for technical support, adding new features, installation, maintenance, etc. from users. I have a small company and we could sign an agreement to collaborate in offering the mentioned services, then split the income in half.
