### ISSUE TITLE
How to change voice on webphone?

### ISSUE THREAD

**Issue by Beatific-Angel** [InnovateAsterisk/Browser-Phone#318]
Dear Conrad de Wet
How are you?
your Webphone solution is very great.
I am using your phone continually.

Currently I have one problem.
I gonna change voice of caller.
to do this, I have to set mic before calling? otherwise I can change voice after connected calling?
this is possible?

**Comment by InnovateAsterisk** [comment]
The Browser Phone will use the default microphone and speaker device, so long as its still connected. You can set this in the settings.

<img width="370" alt="image" src="https://user-images.githubusercontent.com/58937573/189665082-39209920-9898-45ab-a75c-fdd86f07ba2b.png">


It will then try to use this device on each call (if its not plugged in at that point, it will just use the system default device). During a call you can also change the microphone or speaker device. This will not save, it's only during that call. To do this, click the speaker looking icon (under the hangup button):

<img width="352" alt="image" src="https://user-images.githubusercontent.com/58937573/189664648-2f645200-05a4-4758-b327-d280fcefcfab.png">

This will offer you a list of other possible devices:

<img width="352" alt="image" src="https://user-images.githubusercontent.com/58937573/189664787-01f7fa15-8ab5-4a4d-88bc-32581ed0f3ba.png">

Make you selection. This will not interrupt your call in any way. 

Note that some browsers don't support the device output option meaning that you cannot change the playout sound device, like have a different device for a ring tone.

**Comment by Beatific-Angel** [comment]
I read.
what i mean is to do change voice changer of caller.
I want two features.
one : 
before calling, I want to change caller 's voice to high or lower.
second: 
before calling, I want to change caller's voice to man or women.(otherwise while calling)

how is your think?

**Comment by InnovateAsterisk** [comment]
If this is even possible, i don't know how to do this.
