### ISSUE TITLE
messages within a call

### ISSUE THREAD

**Issue by vieridipaola** [InnovateAsterisk/Browser-Phone#32]
Hi,

I don't know if I have to set up something specifically in Asterisk so that "instant messages" work properly in Browser-Phone.

When I'm on a call, if I type anything in the "Type your message here" input field then an "anonymous" call is initiated to the peer. Even if the peer answers this anonymous call, there's no visual on the message interchange. 

I'll look into this further if I get the chance and give some more info, but I think it's easy to reproduce.

Thanks

**Comment by InnovateAsterisk** [comment]
Text Messages have to be specially set up. There are a few steps to complete. Take a look at the instructions or the video from the Readme page: 
https://github.com/InnovateAsterisk/Browser-Phone

PS, text messages are out of dialog messages, so you don't need to be on a call. You just have to be both registered. This is something like WhatsApp, Skype Etc... however there is no DB, so it can't spool messages if you are offline... something I would like to update

**Comment by vieridipaola** [comment]
OK, the README.md file refers to chan_sip, but I'm using pjsip only.
So I added:
message_context=textmessages
to each endpoint in pjsip.conf.
That seems to do the trick.

I must say that message_context is not well documented upstream. You may want to add it in README.md, if you wish.

**Comment by InnovateAsterisk** [comment]
Yes, pjsip supports out-of-dialog messaging by default, you only need to supply it with a context. In my example configs, I did this with templates. Something you should be using... so rather than 
> "So I added:
> message_context=textmessages
> to each endpoint in pjsip.conf."

you would have said:
> "I added it to my endpoint template" 

;-)

**Comment by vieridipaola** [comment]
Yes, you're right. It's tidier with templates. On it... :-)

**Comment by vieridipaola** [comment]
BTW I'm new to pjsip. There's no "general" section and no way of specifying the message_context value "globally", right? It must be done in a template as you say, and that would sort of mimic the "global" behavior you would get when using chan_sip, right?

**Comment by InnovateAsterisk** [comment]
Correct, I assume they want you to use templates.

**Comment by vieridipaola** [comment]
Great, thanks.
Closing issue...
