### ISSUE TITLE
Trying but not ringing

### ISSUE THREAD

**Issue by prathibhacdac** [InnovateAsterisk/Browser-Phone#322]
You tried to make a video call(declined).

Console output:

DTLS ECDH initialized (automatic), faster PFS enabled
  == DTLS ECDH initialized (automatic), faster PFS enabled
  == Using SIP VIDEO CoS mark 6
  == Using SIP RTP CoS mark 5
       > 0x7fe198010b30 -- Strict RTP learning after remote address set to: 116.68.80.164:63736
    -- Executing [231017@test:1] NoOp("SIP/7510715560-0000000b", "Calling:231017")
    -- Executing [231017@test:2] Dial("SIP/7510715560-0000000b", "SIP/231017,30")
  == DTLS ECDH initialized (automatic), faster PFS enabled
  == DTLS ECDH initialized (automatic), faster PFS enabled
  == Using SIP VIDEO CoS mark 6
  == Using SIP RTP CoS mark 5
[Sep 17 17:06:42] ERROR[21473][C-00000007]: chan_sip.c:4271 __sip_reliable_xmit: Serious Network Trouble; __sip_xmit returns error for pkt data
    -- Called SIP/231017
       > 0x7fe198036470 -- Strict RTP learning after ICE completion
    -- Nobody picked up in 30000 ms
    -- Executing [231017@test:3] Set("SIP/7510715560-0000000b", "JITTERBUFFER(adaptive)=200,,,60")
    -- Auto fallthrough, channel 'SIP/7510715560-0000000b' status is 'NOANSWER'
[Sep 17 17:07:12] ERROR[28311]: cdr_odbc.c:176 odbc_log: Unable to retrieve database handle.  CDR failed.

**Comment by InnovateAsterisk** [comment]
> chan_sip.c:4271 __sip_reliable_xmit: Serious Network Trouble; __sip_xmit returns error for pkt data

If signaling is working, but audio is failing you probably have an ICE issue. I also notice you are using chan_sip this is not recommended. I would use pjsip with asterisks greater than 16

**Comment by prathibhacdac** [comment]
STUN and TURN server details are given in rtp.conf. In trickle ice, I'm getting the srflx address.  I'm using asterisk 13.

**Comment by prathibhacdac** [comment]
I'm on the same network.

**Comment by prathibhacdac** [comment]
How to resolve the ICE issue?

**Comment by prathibhacdac** [comment]
Resolved.
