### ISSUE TITLE
dependency

### ISSUE THREAD

**Issue by vieridipaola** [InnovateAsterisk/Browser-Phone#33]
This isn't really an *issue*... Anyway, I guess I can post this here.

Just a note on the dependency list (README): fontawesome 4.7.0 should be added, and I believe the Roboto fonts are also missing.

**Comment by InnovateAsterisk** [comment]
![image](https://user-images.githubusercontent.com/58937573/84237532-cbbd9780-aaf9-11ea-874e-319b71878169.png)
The Roboto css calls the woof2 file, but appears to load fine on my side. Ill double check the CORS policy

**Comment by InnovateAsterisk** [comment]
![image](https://user-images.githubusercontent.com/58937573/84238834-f14ba080-aafb-11ea-88ef-1a41ada7e581.png)

Let me know if you don't get the same response.

**Comment by vieridipaola** [comment]
Sure, it's fine. I didn't explain myself properly -- my bad. By "dependency" what I really wanted to say was that if one wants to host every single "dependency" file on a server, one must download a few things, such as the fontawesome zip file v. 4.7.0 and unpack it into the right subdir, etc. I downloaded those roboto files myself, but I simply don't want to depend on Cloudfront.

**Comment by InnovateAsterisk** [comment]
Readme updated with Lib download link.
https://dtd6jl0d42sve.cloudfront.net/lib/lib.zip

**Comment by vieridipaola** [comment]
...and that lib file will be updated as the needed. Great! That's really convenient.
Thanks.
Closing "issue".
