### ISSUE TITLE
cannot dial with # prefix

### ISSUE THREAD

**Issue by vieridipaola** [InnovateAsterisk/Browser-Phone#330]
Hi,

How can I dial a number with # as prefix?

```
INVITE (audio): #4@sip.mydomain.org phone.js:4995:13
Uncaught TypeError: Invalid to URI: undefined
    X https://communicator.mydomain.org/webphone/external/lib/SipJS/sip-0.20.0.min.js:2
    AudioCall https://communicator.mydomain.org/webphone/phone.js?1664878606:4998
    DialByLine https://communicator.mydomain.org/webphone/phone.js?1664878606:7744
```

Thanks

**Comment by vieridipaola** [comment]
According to https://github.com/onsip/SIP.js/issues/1006 it seems that all Browser-Phone / phone.js must do is replace '#' with %23, eg. somethng like this for every makeURI call in phone.js:

`var targetURI = SIP.UserAgent.makeURI("sip:" + dialledNumber.replace(/#/g, "%23") + "@" + wssServer);`

**Comment by InnovateAsterisk** [comment]
I get ```Uncaught TypeError: Invalid to URI: undefined sip-0.20.0.min.js:formatted:3088```
when calling ```#1```

**Comment by InnovateAsterisk** [comment]
I would much rather ```SIP.UserAgent.makeURI``` perform this conversion for me, since this pretty much the job of the function.

**Comment by InnovateAsterisk** [comment]
I see tho, it's only necessary on the two INVITE points (audio and video), other than that the makeURI would probably not contain ```#```. 

I would probably implement this: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent 
in case the user has enabled ```EnableAlphanumericDial```
