### ISSUE TITLE
adding buddies and starting calls automatically

### ISSUE THREAD

**Issue by vieridipaola** [InnovateAsterisk/Browser-Phone#34]
Hi,

I was wondering if we could get this patch upstream somehow. It is incomplete, and that's why I'm posting it here instead of filing a PR. The idea is simple. If a user types in a number or extension on the buddy search input box, a buddy will be created automatically, and a call will also be initiated. My patch below will disable the "addsomeonewindow" which, of course, is not desired (but due to lack of time, I need to finish other tasks first).

```
--- phone.original.js   2020-06-09 18:10:35.034098297 +0200
+++ phone.js    2020-06-11 12:22:41.712065649 +0200
@@ -300,6 +300,88 @@
     HidePopup();
 }

+// CUSTOM: automatically add buddy and start call
+// ==========
+function AutoAddBuddy(peerid){
+    peerid = peerid.trim();
+    if(peerid.length == 0){
+       console.log("Cannot Auto Add Buddy");
+       return;
+    }
+    console.log("Auto Add Buddy " + peerid);
+
+    var CurrentCalls = CallSessions.length;
+
+    var buddyObj = FindBuddyByNumber(peerid);
+    if(buddyObj == null) buddyObj = FindBuddyByExtNo(peerid);
+    // Make new contact of its not there
+    if(buddyObj == null) {
+        var json = JSON.parse(localDB.getItem("UserBuddiesJson"));
+        if(json == null) json = InitUserBuddies();
+
+        if(peerid.length > DidLength){
+            // Add Regular Contact
+            var id = uID();
+            var dateNow = utcDateNow();
+            json.DataCollection.push(
+                {
+                    Type: "contact",
+                    LastActivity: dateNow,
+                    ExtensionNumber: "",
+                    MobileNumber: "",
+                    ContactNumber1: peerid,
+                    ContactNumber2: "",
+                    uID: null,
+                    cID: id,
+                    gID: null,
+                    DisplayName: "",
+                    Position: "",
+                    Description: "",
+                    Email: "",
+                    MemberCount: 0
+                }
+            );
+            buddyObj = new Buddy("contact", id, "", "", "", peerid, "", dateNow, "", "");
+            AddBuddy(buddyObj, true, (CurrentCalls==0));
+        }
+        else {
+            // Add Extension
+            var id = uID();
+            var dateNow = utcDateNow();
+            json.DataCollection.push(
+                {
+                    Type: "extension",
+                    LastActivity: dateNow,
+                    ExtensionNumber: peerid,
+                    MobileNumber: "",
+                    ContactNumber1: "",
+                    ContactNumber2: "",
+                    uID: id,
+                    cID: null,
+                    gID: null,
+                    DisplayName: "",
+                    Position: "",
+                    Description: "",
+                    Email: "",
+                    MemberCount: 0
+                }
+            );
+            buddyObj = new Buddy("extension", id, "", peerid, "", "", "", dateNow, "", "");
+            AddBuddy(buddyObj, true, (CurrentCalls==0), true);
+        }
+        // Update Size:
+        json.TotalRows = json.DataCollection.length;
+
+        // Save To DB
+        localDB.setItem("UserBuddiesJson", JSON.stringify(json));
+
+        UpdateBuddyList();
+    }
+    var buddy = buddyObj.identity;
+
+    VideoCall(buddy);
+}
+
 // UI Windows
 // ==========
 function AddSomeoneWindow(){
@@ -1433,7 +1515,9 @@
         CreateGroupWindow();
     });
     $("#BtnAddSomeone, #BtnAddSomeone1").on('click', function(event){
-        AddSomeoneWindow();
+        // AddSomeoneWindow();
+        // CUSTOM: add as contact buddy whatever is in txtFindBuddy (TODO: make sure buddy doesn't already exist, allow to add as extension too)
+        AutoAddBuddy($("#txtFindBuddy").val());
     });
     $("#ConfigureExtension").on('click', function(event){
         ConfigureExtensionWindow();
```

Do you think you can modify this and merge it in?
The idea is to keep the original behavior/design the same (add a buddy with all its details), but adding the ability to quickly dial someone. In some hectic environments (as in a hospital), users are often impatient, and they will find that the manual creation of a buddy in order to simply dial out (eg. a patient) is overly time consuming.  
So, if you have the time (or I can try to pick this up again later), the idea is that when a user clicks on the "Add someone" icon, there should be a dropdown menu with "Add with details" and "Quick Add and Call". The first option would open the addsomeonewindow form (and mayube even pass it the extension or number), and the second one would launch the code I wrote (AutoAddBuddy).

Thanks

**Comment by InnovateAsterisk** [comment]
I have an idea for this, it will take a bit longer, but will work better.

**Comment by InnovateAsterisk** [comment]
You can now at any arbitrary time after registration call: 
```
DialByLine(type, buddy, numberToDial)
```

The syntax is as follows:
- **type** = (string) either "audio" or "video"
- **buddy** = (string) the id of an exiting buddy or null create a buddy.
- **numberToDial** = (string) the number you are dialling. Must be [+#0-9]. If buddy is null, and the number does match an existing buddy, that buddy is used.

In your case you can typically use: ``` DialByLine("audio", null, "500"); ```

It will make the line and the buddy etc, you don't need to really do anything.

**Comment by vieridipaola** [comment]
Amazing!
Big thanks!

Just one thing though... If type is "video", it doesn't seem to downgrade to audio if one of the two does not have a camera.
I don't know if this can be supported or not.

**Comment by InnovateAsterisk** [comment]
Well, I may be able to read the response and double check if the video hint is in the SDP... and then downgrade the call. Will check.

**Comment by InnovateAsterisk** [comment]
It appears the Asterisk responds with acceptable video codecs even tho it would be impossible to establish a video call... in my test i was able to setup a video call to a non existent extension and an extension without video capabilities, but asterisk response SDP contained matching video line

```
...
m=video 27744 RTP/SAVPF 96 99
...
```
This means it doesn't know or doesn't care if the B side has video capabilities. This also means the only real way would be to show or hide the video interface based on the actual streams. 

I need to do this anyway for group calling in version 16 that supports multiple video streams... in other words the UI needs to be able to support N many video streams, where N is any number between 0 and max_streams
