### ISSUE TITLE
camera rotation

### ISSUE THREAD

**Issue by prathibhacdac** [InnovateAsterisk/Browser-Phone#346]
While on call, is it possible to change the front camera to back camera?

**Comment by InnovateAsterisk** [comment]
Remember this app isn't really designed for mobile devices, there are some limitations. Media handling like this for example is different. 

In the test that I was able to do, iPhone allows you to switch from front to back with two actual cameras that appear in the media selector (the speaker looking icon when you expand the call controls panel). 

With Android, i cant remember... it may have also, but the result may vary.

**Comment by prathibhacdac** [comment]
> While on call, is it possible to change the front camera to back camera?

Yes its possible.
