### ISSUE TITLE
es lang: save

### ISSUE THREAD

**Issue by vieridipaola** [InnovateAsterisk/Browser-Phone#348]
Hi,

The value of "save" in es.json should be "Guardar".

Thanks

**Comment by InnovateAsterisk** [comment]
https://github.com/InnovateAsterisk/Browser-Phone/blob/acd80e551208098ec12effbc4cbceefd0ccb579f/Phone/lang/es.json#L30

It's there. It may be hard coded in the script then, where is this showing?

**Comment by vieridipaola** [comment]
es.json contains the string "Guargar" with a second lowercase 'g'.
It should be "Guardar", so the second 'g' should be replaced with a 'd'.
