### ISSUE TITLE
Raspbx Instructions

### ISSUE THREAD

**Issue by victorkl400** [InnovateAsterisk/Browser-Phone#35]
As raspbx is a famous image to start using asterisk/freepbx on raspberry pi , would be great if you add intructions to setup with it.
Thx

**Comment by InnovateAsterisk** [comment]
Asterisk was quite well covered here: https://youtu.be/mS28vfT8wJ8
and: https://youtu.be/azWUfSBz__s

But it's quite a good idea to cover the how-to in FreePBX. Unless you feel like helping with that?
