### ISSUE TITLE
No audio / RTP

### ISSUE THREAD

**Issue by vieridipaola** [InnovateAsterisk/Browser-Phone#352]
Hi,

I've come across a weird scenario where calls from endpoint B to endpoint A are OK, but not from A to B.
In my example, A is pjsip endpoint web4053 and B is pjsip endpoint web4068.
Both A and B can be in the same physical LAN but in two different logical vlans, or A can be in WAN and B in LAN -- it is always reproducible within several network scenarios.

At first I thought it could be a firewall issue, but I do not see any traffic being blocked. Also, if B->A is OK then why should A->B fail as there should not be any direct connections between A and B (all goes through Asterisk)?

The observed behavior is that when B calls A, the call is established and audio flows both ways -- no problem.

However, when A calls B, the call seems to be established, but there is no audio flow no matter how much I wait. Neither of the endpoints can hear the other.

I notice that the channel is established in the Asterisk server (A: web4053, B: web4068):

```
# asterisk -rx "core show channels concise" | grep 4068
PJSIP/web4068-00012502!default!!1!Up!AppDial!(Outgoing Line)!4068!!!3!34!c419dbd0-74a0-4039-8856-d57ea04f403c!1667813921.467485
PJSIP/web4053-00012501!default!4068!12!Up!Dial!PJSIP/4068&PJSIP/web4068&PJSIP/webd4068,,tTXg!7002!!!3!34!c419dbd0-74a0-4039-8856-d57ea04f403c!1667813920.467484
```

In A's SIP trace I can see messages such as:

`INVITE sip:4068@xmpp.mydomain.org SIP/2.0`
followed by an ACK

The last "browser-phone client log line" shows:

`SoundMeter for RemoteAudio Connected, displaying levels for Line: 2`

In B's SIP trace I can see messages such as:

```
INVITE sip:0oeoln57@127.0.0.1:40266;transport=ws SIP/2.0
Via: SIP/2.0/WSS 127.0.0.1:8090;rport;branch=z9hG4bKPj3d3c4139-2544-4f0e-bf39-e95821c9f44c;alias
```

followed by

```
SIP/2.0 100 Trying
Via: SIP/2.0/WSS 127.0.0.1:8090;rport;branch=z9hG4bKPj3d3c4139-2544-4f0e-bf39-e95821c9f44c;alias
```
 
followed by

```
SIP/2.0 180 Ringing
Via: SIP/2.0/WSS 127.0.0.1:8090;rport;branch=z9hG4bKPj3d3c4139-2544-4f0e-bf39-e95821c9f44c;alias
```

followed by

```
Adding Remote Audio Track
sip.Invitation | Session bab7a982-4488-4356-871b-934de11a7ce4191b5130-2572-4f0f-a4a9-4b0b7161bac4 transitioned to state Established
sip.Transport | Sending WebSocket message:

SIP/2.0 200 OK
Via: SIP/2.0/WSS 127.0.0.1:8090;rport;branch=z9hG4bKPj3d3c4139-2544-4f0e-bf39-e95821c9f44c;alias
```

and finally

```
ACK sip:0oeoln57@127.0.0.1:40266;transport=ws SIP/2.0
Via: SIP/2.0/WSS 127.0.0.1:8090;rport;branch=z9hG4bKPjba1798c3-ed77-4092-834d-8e68c8cea254;alias
sip.Invitation | Session.onAckRequest
```

So, it seems that the call is established, but there's no RTP flow.

What can I try?
What should I look for?

**Comment by vieridipaola** [comment]
After reviewing the client log in Firefox I finally got a useful error message:

`WebRTC: ICE failed, add a TURN server and see about:webrtc for more details `

This is what I see in B's log, and about:webrtc shows me that the ICE candidates are all in the "failed" status.

This only happens when calling from A to B and whichever STUN/TURN server I use.

It doesn't seem to be a firewall issue.

When using my own STUN service:
```
In  IP 192.168.212.134.62552 > 10.215.144.92.3480: UDP, length 20
Out IP 192.168.212.134.62552 > 10.215.144.92.3480: UDP, length 20
In  IP 10.215.144.92.3480 > 192.168.212.134.62552: UDP, length 104
Out IP 10.215.144.92.3480 > 192.168.212.134.62552: UDP, length 104
```

When using default (google):
```
In  IP 192.168.212.134.52315 > 172.253.120.127.19302: UDP, length 20
Out IP 192.168.212.134.52315 > 172.253.120.127.19302: UDP, length 20
In  IP 172.253.120.127.19302 > 192.168.212.134.52315: UDP, length 32
Out IP 172.253.120.127.19302 > 192.168.212.134.52315: UDP, length 32
```

When ICE fails on B I get (192.168.212.134 is B's local IP addr.):

SDP
local SDP (reply)

```
v=0
o=mozilla...THIS_IS_SDPARTA-99.0 2336294347277766966 0 IN IP4 0.0.0.0
s=-
t=0 0
a=sendrecv
a=fingerprint:sha-256 A4:73:A7:9A:87:0B:76:85:17:D0:C5:47:89:D1:32:C7:98:CD:D9:82:8E:B7:8B:61:6A:64:D1:09:C8:FC:A6:86
a=group:BUNDLE audio-0
a=ice-options:trickle
a=msid-semantic:WMS *
m=audio 49866 UDP/TLS/RTP/SAVPF 8 0 107 9 101
c=IN IP4 192.168.212.134
a=candidate:0 1 UDP 2122252543 192.168.212.134 49866 typ host
a=candidate:2 1 TCP 2105524479 192.168.212.134 9 typ host tcptype active
a=sendrecv
a=end-of-candidates
a=fmtp:107 maxplaybackrate=48000;stereo=1;useinbandfec=1
a=fmtp:101 0-15
a=ice-pwd:f25355ae2786094d7dd16b6131d9aec1
a=ice-ufrag:4fdf40cf
a=mid:audio-0
a=msid:{d1d2d05b-5dd2-400b-97e0-b273feeee48a} {505c5d43-3300-40d5-add2-04d07ac5e8b0}
a=rtcp-mux
a=rtpmap:8 PCMA/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:107 opus/48000/2
a=rtpmap:9 G722/8000/1
a=rtpmap:101 telephone-event/8000
a=setup:active
a=ssrc:1995686134 cname:{5ba05fe6-2d38-40aa-89c9-b03d63c803de}
```

remote SDP (offer)

```
v=0
o=- 647512347 647512347 IN IP4 10.215.144.92
s=-
t=0 0
a=sendrecv
a=group:BUNDLE audio-0
a=msid-semantic:WMS *
m=audio 36412 UDP/TLS/RTP/SAVPF 8 0 107 9 3 101
c=IN IP4 10.215.144.92
a=candidate:Had7905c 1 UDP 2130706431 10.215.144.92 36412 typ host
a=candidate:Hac100002 1 UDP 2130706431 172.16.0.2 36412 typ host
a=candidate:Hc0a8e401 1 UDP 2130706431 192.168.228.1 36412 typ host
a=candidate:Hc0a86502 1 UDP 2130706431 192.168.101.2 36412 typ host
a=candidate:Hc0a86402 1 UDP 2130706431 192.168.100.2 36412 typ host
a=candidate:Hc0a85c02 1 UDP 2130706431 192.168.92.2 36412 typ host
a=candidate:Hd4aa5ea8 1 UDP 2130706431 PUBLIC.IPv4.ADDR.3 36412 typ host
a=candidate:H4f9478e1 1 UDP 2130706431 PUBLIC.IPv4.ADDR.2 36412 typ host
a=candidate:H533d03d8 1 UDP 2130706431 PUBLIC.IPv4.ADDR.1 36412 typ host
a=sendrecv
a=fingerprint:sha-256 A3:67:0A:27:B2:17:60:33:2F:80:55:76:B7:3C:5E:29:B6:97:76:3E:3C:2F:84:4F:F5:FF:D4:02:85:C4:48:ED
a=fmtp:107 maxplaybackrate=0;stereo=0;useinbandfec=1
a=fmtp:101 0-16
a=ice-pwd:646ec89f0498e40029a9a1e164faa045
a=ice-ufrag:2802483b61cde391264d02e72ddb5650
a=maxptime:20
a=mid:audio-0
a=msid:eb254c90-8541-489a-a255-06cb4f2e660f eb8b484e-9eff-4bcb-827e-ae0a9413aec5
a=ptime:20
a=rtcp-fb:* transport-cc
a=rtcp-mux
a=rtpmap:8 PCMA/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:107 opus/48000/2
a=rtpmap:9 G722/8000/1
a=rtpmap:3 GSM/8000/1
a=rtpmap:101 telephone-event/8000
a=setup:actpass
a=ssrc:518330258 cname:64616fef-2f94-47b6-8354-4d41f589e813
```


However, when calling from B to A (successful call and ICE works on B) I get (still on B):

SDP
local SDP (offer)

```
v=0
o=mozilla...THIS_IS_SDPARTA-99.0 1792656630186497946 0 IN IP4 0.0.0.0
s=-
t=0 0
a=sendrecv
a=fingerprint:sha-256 AB:40:34:20:B9:B4:8C:D5:83:7B:CA:2F:2D:79:90:C6:89:7A:3B:B8:44:5F:BF:6D:23:C7:11:ED:86:51:DC:F7
a=group:BUNDLE 0
a=ice-options:trickle
a=msid-semantic:WMS *
m=audio 61550 UDP/TLS/RTP/SAVPF 109 9 0 8 101
c=IN IP4 192.168.212.134
a=candidate:0 1 UDP 2122252543 192.168.212.134 61550 typ host
a=candidate:2 1 TCP 2105524479 192.168.212.134 9 typ host tcptype active
a=candidate:0 2 UDP 2122252542 192.168.212.134 61551 typ host
a=candidate:2 2 TCP 2105524478 192.168.212.134 9 typ host tcptype active
a=sendrecv
a=end-of-candidates
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:2/recvonly urn:ietf:params:rtp-hdrext:csrc-audio-level
a=extmap:3 urn:ietf:params:rtp-hdrext:sdes:mid
a=fmtp:109 maxplaybackrate=48000;stereo=1;useinbandfec=1
a=fmtp:101 0-15
a=ice-pwd:fdcb67fe47bc274fc13729f470719458
a=ice-ufrag:b7e9ac15
a=mid:0
a=msid:{c987c577-5fe7-4440-a335-9711166c3670} {93b04fb5-4944-4312-82bd-e2523f30e596}
a=rtcp:61551 IN IP4 192.168.212.134
a=rtcp-mux
a=rtpmap:109 opus/48000/2
a=rtpmap:9 G722/8000/1
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:101 telephone-event/8000
a=setup:actpass
a=ssrc:890098153 cname:{32a18172-2ef6-423b-8b71-afdf582bc7af}
```

remote SDP (reply)

```
v=0
o=- 243521434 2 IN IP4 10.215.144.92
s=-
t=0 0
a=sendrecv
a=group:BUNDLE 0
a=msid-semantic:WMS *
m=audio 28160 UDP/TLS/RTP/SAVPF 8 0 109 9 101
c=IN IP4 10.215.144.92
a=candidate:Had7905c 1 UDP 2130706431 10.215.144.92 28160 typ host
a=candidate:Hac100002 1 UDP 2130706431 172.16.0.2 28160 typ host
a=candidate:Hc0a8e401 1 UDP 2130706431 192.168.228.1 28160 typ host
a=candidate:Hc0a86502 1 UDP 2130706431 192.168.101.2 28160 typ host
a=candidate:Hc0a86402 1 UDP 2130706431 192.168.100.2 28160 typ host
a=candidate:Hc0a85c02 1 UDP 2130706431 192.168.92.2 28160 typ host
a=candidate:Hd4aa5ea8 1 UDP 2130706431 PUBLIC.IPv4.ADDR.3 28160 typ host
a=candidate:H4f9478e1 1 UDP 2130706431 PUBLIC.IPv4.ADDR.2 28160 typ host
a=candidate:H533d03d8 1 UDP 2130706431 PUBLIC.IPv4.ADDR.1 28160 typ host
a=sendrecv
a=fingerprint:sha-256 52:9D:FF:51:3C:46:C6:3B:E4:18:C4:8E:5C:62:DF:CB:AE:B3:75:38:EE:5E:69:10:B8:56:C6:FA:5C:2A:E1:62
a=fmtp:109 maxplaybackrate=0;stereo=0;useinbandfec=1
a=fmtp:101 0-16
a=ice-pwd:5cad745e0adde1d91a9b07c84069d337
a=ice-ufrag:0e639339587c92f507f2f7983383b30d
a=maxptime:20
a=mid:0
a=msid:7d2f5f68-af28-4873-8b93-8422777fa632 7aabeda8-0eb2-49a5-ab51-4e09fd03bcd9
a=ptime:20
a=rtcp-fb:* transport-cc
a=rtcp-mux
a=rtpmap:8 PCMA/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:109 opus/48000/2
a=rtpmap:9 G722/8000/1
a=rtpmap:101 telephone-event/8000
a=setup:active
a=ssrc:827475348 cname:22474737-d1f3-4080-9921-d4b314eedbf9
```

I also tried connecting from B to:

https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/
https://icetest.info/

The tests seem to be OK.

Any ideas?

**Comment by InnovateAsterisk** [comment]
What does this show (test on both ends)
https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/

Also, are you using TRUN? Remember, it's not necessary unless you are using a proxy server and end-to-end (encrypted) media. If you are using Asterisk, it will always **be in the media path** (just like a TURN server) because Asterisk is a back-to-back-user-agent (B2BUA), and therefor cannot negotiate out of the stream because encryption is established in the offer with ICE as part of the SDP, so if Asterisk is the endpoint (sends the OK), the encryption cannot be made with another endpoint. 

Signalling: [Browser] <==== WSS (TLS) ====> [Asterisk] <==== WSS (TLS) ====> [Browser]
Media: [Browser] <==== DTLS ====> [Asterisk] <==== DTLS ====> [Browser]

(With the above, remember "Browser" really means your last live IP address before its nated to your local lan.)

For you, It looks like NAT occurs 5 times on its way out... this is very complicated, and it could be any one of these devices causing issues there.

**Comment by vieridipaola** [comment]
This is an example network path:

`WAN / Internet Browser "A" --- WAN Gateway --- Apache Reverse Proxy --- Asterisk webrtc in DMZ --- LAN router/firewall ---WiFi vlan xxx --- Browser "B"`

Signalling would be:
```
WAN / Internet Browser "A" --- WAN Gateway --- Apache Reverse Proxy --- LAN router/firewall ---WiFi vlan xxx --- Browser "B"
                                                                                                \---  Asterisk webrtc in DMZ
``` 

Media via UDP RTP would be:
`WAN / Internet Browser "A" --- WAN Gateway --- Asterisk in DMZ --- LAN router/firewall ---WiFi vlan xxx --- Browser "B"`

where A and B are the Browser-Phone clients as described in my previous posts.

When B calls A, no problems.
When A calls B, I get an ICE failure in B, and there's no audio.

I have a COTURN server locally (in DMZ), but I'm using STUN -- not TURN or TURNS --  because in my case both my "WAN Gateway" and my "LAN router/firewall" allow UDP traffic (20000-40000) directly to "Asterisk in DMZ".

Frankly, I don't know if I should specify the STUN server in my Asterisk rtp.conf as such:

```
[general]
rtpstart=20000
rtpend=40000
stunaddr=sip.mydomain.org:3480
```

The Browser-Phones A and B both use;
`phoneOptions.IceStunServerJson = '[{ "urls":"stun:sip.mydomain.org:3480", "username":""user, "credential":"pwd" }]';`

Testing ICE on B with the github site using my Coturn service in DMZ returns this output which doesn't look good:

```
Time    Component    Type    Foundation    Protocol    Address    Port    Priority    relayProtocol (if present)    Mid    MLine Index    Username Fragment    URL (if present)
0.003    rtp    host    0    udp    a2153f84-6e25-4bb3-b5bd-4c3a60205115.local    52648    126 | 32512 | 255    
    0    0    ed06fcf3    

0.003    rtp    host    2    tcp    a2153f84-6e25-4bb3-b5bd-4c3a60205115.local    9    125 | 32704 | 255    
    0    0    ed06fcf3    

0.003    rtcp    host    0    udp    a2153f84-6e25-4bb3-b5bd-4c3a60205115.local    52649    126 | 32512 | 254    
    0    0    ed06fcf3    

0.003    rtcp    host    2    tcp    a2153f84-6e25-4bb3-b5bd-4c3a60205115.local    9    125 | 32704 | 254    
    0    0    ed06fcf3    

0.036    Done
```

However, I get a better result from A:

```
Time | Component | Type | Foundation | Protocol | Address | Port | Priority | relayProtocol (if present) | Mid | MLine Index | Username Fragment | URL (if present)
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
0.010 | rtp | host | 0 | udp | 2dd5a8f0-0d10-477f-8016-b42761b9dc92.local | 36203 | 126 \| 32512 \| 255 |   | 0 | 0 | 8c63990a |  
0.014 | rtp | host | 2 | tcp | 2dd5a8f0-0d10-477f-8016-b42761b9dc92.local | 9 | 125 \| 32704 \| 255 |   | 0 | 0 | 8c63990a |  
0.015 | rtcp | host | 0 | udp | 2dd5a8f0-0d10-477f-8016-b42761b9dc92.local | 57928 | 126 \| 32512 \| 254 |   | 0 | 0 | 8c63990a |  
0.016 | rtcp | host | 2 | tcp | 2dd5a8f0-0d10-477f-8016-b42761b9dc92.local | 9 | 125 \| 32704 \| 254 |   | 0 | 0 | 8c63990a |  
0.043 | rtp | srflx | 1 | udp | PUBLIC.IPv4.ADDR.A | 36203 | 100 \| 32543 \| 255 |   | 0 | 0 | 8c63990a |  
0.059 | Done
```

If I use the Google STUN service I get the same result for A, but this time I get this for B:

```
Time    Component    Type    Foundation    Protocol    Address    Port    Priority    relayProtocol (if present)    Mid    MLine Index    Username Fragment    URL (if present)
0.002    rtp    host    0    udp    2f7477c3-4e93-49af-b814-d9ebfae0eede.local    65422    126 | 32512 | 255    
    0    0    0659d745    

0.003    rtp    host    2    tcp    2f7477c3-4e93-49af-b814-d9ebfae0eede.local    9    125 | 32704 | 255    
    0    0    0659d745    

0.003    rtcp    host    0    udp    2f7477c3-4e93-49af-b814-d9ebfae0eede.local    65423    126 | 32512 | 254    
    0    0    0659d745    

0.003    rtcp    host    2    tcp    2f7477c3-4e93-49af-b814-d9ebfae0eede.local    9    125 | 32704 | 254    
    0    0    0659d745    

0.061    rtp    srflx    1    udp    PUBLIC.IPv4.ADDR.B    65422    100 | 32543 | 255    
    0    0    0659d745    

0.093    Done
```

Question 1 - Why is STUN with local Coturn failing for B even though communication is open? Probably not the right place to ask... I'll need to dig into this.

Question 2 - I'd expect everything to work if the public IP addresses of both peers are discovered with Google STUN, so why is A -> B still failing with ICE?

As a last resort, I decided to use y local Coturn service as TURN, so I set up both A and B as:

`phoneOptions.IceStunServerJson = '[{ "urls":"turn:sip.mydomain.org:5350", "username":"user", "credential":"pwd" }]';`

Lo and behold, that worked!

The trickle test on B would still not show B's public IP addr, but it did mention the public IP address of the Asterisk server (as "relay"). I don't know why that's enough to make things work.

Any ideas? I'd like to better understand what's happening before closing the issue.

**Comment by InnovateAsterisk** [comment]
I see yes, your STUN is not working correctly, it must come back with a ```srflx``` line. 

> Question 1 - Why is STUN with local Coturn failing for B even though communication is open? Probably not the right place to ask... I'll need to dig into this. 

I also run an instance of Coturn, but don't have the same issue. I'm not an expert on Coturn. But have once had something similar related to the actual client doing the lookup. There was a problem with the reply data being blocked ( like DNS on routers). Try trace it out on wireshark - your should be able to trace this out quite easily since you know the server ip address and port details. Make sure the response is being received. 

> Question 2 - I'd expect everything to work if the public IP addresses of both peers are discovered with Google STUN, so why is A -> B still failing with ICE? 

If the SDP can't populate from the ICE discovery webrtc just doesn't work. It no longer uses the other attributes like c= etc.

> As a last resort, I decided to use my local Coturn service as TURN, so I set up both A and B as:

If you specify a TURN server, and STUN fails, yes TURN will be used, but media will flow over this server, so this may not work over the public internet. (In other words, this may work only in your local network).

> The trickle test on B would still not show B's public IP addr, but it did mention the public IP address of the Asterisk server (as "relay"). I don't know why that's enough to make things work.

"relay" candidates - Gathered via TURN, relay candidates consist of the public IP address and a negotiated port for the relay server. This is useful when a firewall does not allow direct routing via srflx candidates. In this case, the remote peer has signaled a candidate it can use to route traffic to the relay server, which can then in turn relay that traffic to the peer behind the restrictive firewall. The firewall allows the TURN server to route traffic to the peer because the peer made the initial request to the server. In this way, the TURN server acts as a "man-in-the-middle" that the initiating peer uses to circumvent its firewall. From the discussion above, you know that communication over relay candidates is the least desirable option.

This shouldn't be this hard. If you are in control of the configuration of the Asterisk server, then you also shouldn't not need TURN. I am also not 100% sure the DMZ is really necessary, and it may be confusing Asterisk to some degree. I'm not a fan of DMZ, to just push the entire box onto the web, without really being careful about what you actually need exposed. I'm also concerned that Asterisk is seeing itself as being on a local lan (from its local ip), but because of the DMZ, its "actually" on a live IP, but without NAT. If you have the time, it may be better to NAT your Asterisk box, and forward the correct ports (sip, wss, RTP, etc), and then correctly describe the NAT arrangement to Asterisk. Then the next step is to get the endpoints and the server to be able to send media to each other. Remember that because Asterisk is a B2BUA, its actually Asterisk establishing the call for the 2nd leg of the call: Browser <=leg1=> Asterisk <=leg2=> Browser.  In my https://github.com/asterisk/asterisk/blob/master/configs/samples/rtp.conf.sample i specify:
```
[ice_host_candidates]
172.31.X.X => A.B.C.D
```

**Comment by vieridipaola** [comment]
I'm getting there...

When using Coturn and testing here: https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/
I get this wireshark trace on "B":

`Binding Success Response XOR-MAPPED-ADDRESS: 192.168.212.134:53526 MAPPED-ADDRESS: 192.168.212.134:53526 RESPONSE-ORIGIN: PUBLIC.IPv4.ADDR.COTURN:3480`

When using Google STUN I getting this instead:

`Binding Success Response XOR-MAPPED-ADDRESS: PUBLIC.IPv4.ADDR.B:58284`

So I changed my coturn configuration to this:

```
listening-port=3480
tls-listening-port=5350
external-ip=PUBLIC.IPv4.ADDR.B/192.168.212.134
listening-ip=PUBLIC.IPv4.ADDR.COTURN
verbose
fingerprint
lt-cred-mech
server-name=sip.mydomain.org
user=me:pwd
realm=sip.mydomain.org
cert=/etc/turnserver/cert.pem
pkey=/etc/turnserver/key.pem
log-file=/var/log/turnserver.log
simple-log
proc-user=turnserver
proc-group=turnserver
min-port=20000
max-port=40000
```

My wireshark trace to my Coturn service now shows this:

`Binding Success Response XOR-MAPPED-ADDRESS: PUBLIC.IPv4.ADDR.B:56564 MAPPED-ADDRESS: PUBLIC.IPv4.ADDR.B:56564 RESPONSE-ORIGIN: PUBLIC.IPv4.ADDR.COTURN:3480`

I'm going to have to dwell a bit on the external-ip setting in coturn...

Anyway, even with all this apparently OK the calls from A to B still didn't work for media until I read again what you said about Asterisk being B2BUA (thanks for repeating yourself quite a few times on this -- it finally came through).
I was missing a firewall rule to allow UDP traffic from the Asterisk system to the WiFi vlan where B is located.

However, I am seeing traffic of this type toward "B": 
```
UDP SPT=9102 DPT=51714
UDP SPT=25079 DPT=53187
```
etc

Instead, I'm expecting to see UDP ports in the 20000-40000 range.
My rtp.conf in Asterisk is:

```
[general]
rtpstart=20000
rtpend=40000
```

Any ideas?

If it weren't for this glitch everything would be working as expected.
I can now call from A to B, and audio flows both ways. (big thanks!)

I still need to solve the UDP port range though.

**Comment by vieridipaola** [comment]
Wait a minute... There's actually nothing wrong with receiving XOR-MAPPED-ADDRESS: 192.168.212.134 in my scenario, so I don't really need to use external-ip in coturn.
The SDP negotiation will succeed just as long as I enable the UDP traffic from Asterisk to B's VLAN.
The webrtc trickle website will still not show me the same as with Google's STUN, but it doesn't seem to matter.
Browser-Phone now works with STUN to a local Coturn service -- works with WAN and LAN clients.

I'm still struggling with the UDP port ranges though.

**Comment by vieridipaola** [comment]
That makes sense...

BTW "IceStunCheckTimeout" defaults to 500ms. Do you think it's enough?

**Comment by InnovateAsterisk** [comment]
There is an option "IceStunCheckTimeout"

**Comment by vieridipaola** [comment]
OK, I can finally close this issue.

Many thanks!
