### ISSUE TITLE
dialText focus

### ISSUE THREAD

**Issue by vieridipaola** [InnovateAsterisk/Browser-Phone#353]
In 

`function ShowDial(){`

there is an input text element:

`<input id=dialText oninput="handleDialInput(this, event)" onkeydown="dialOnkeydown(event, this)" `

When a Browser-Phone user clears his/her buddy list the dialpad window shows up automatically. That's fine.

Also, in most cases when the buddy list is empty there wouldn't be any reason for the user to type something in the "search input text field" (txtFindBuddy element).

Unless... someone like me implements a CRM search tool by using the data in txtFindBuddy (ie. the user can type any number or word, press enter and a ws replies with a list of contacts in a custom window).
This customization still works fine if the buddy list is non-empty. However, if it is the focus is "stolen" from the txtFindBuddy field and passed on to dialText at every keystroke.

All I did to "fix"/adapt this to my needs is comment out $("#dialText").focus() in funtion ShowDial().

I don't know how to "conditionally" focus txtFindBuddy even if the ShowDial window is displayed, ie. if the user starts typing in txtFindBuddy I don't want the focus to go back to dialText.

**Comment by InnovateAsterisk** [comment]
For most use cases the focus() is more useful, but you can write your own dial-pad 😀

https://github.com/InnovateAsterisk/Browser-Phone/blob/acd80e551208098ec12effbc4cbceefd0ccb579f/Phone/phone.js#L115

**Comment by vieridipaola** [comment]
So I had to add focus() to phone.js here:

```
    $("#txtFindBuddy").attr("placeholder", lang.find_someone)
    $("#txtFindBuddy").on('keyup', function(event){
        UpdateBuddyList();
        $("#txtFindBuddy").focus();
    });
```

and left function ShowDial() untouched.
Would it be possible to add
`$("#txtFindBuddy").focus();`
to phone.js as in the snippet above?

It shouldn't bother anyone.

Nice new UiCustom* settings. Could you them too, but the dial-pad is very nice... ;-)

**Comment by InnovateAsterisk** [comment]
Yip, will do

**Comment by InnovateAsterisk** [comment]
The UI was updated in this release or a previous one

https://github.com/InnovateAsterisk/Browser-Phone/commit/36751ca929ba884ce57c19077d6ac6680adf14d4
