### ISSUE TITLE
CustomPresence

### ISSUE THREAD

**Issue by vieridipaola** [InnovateAsterisk/Browser-Phone#355]
Hi,

Can Browser-Phone handle CustomPresence such as in the hint example below?

`exten => 1000,hint,PJSIP/alice,CustomPresence:alice`

I'd like my buddy alice to show up as BUSY or NOT AVAILABLE when I custom set her presence to, say, dnd. If custom presence not set then only consider device state of PJSIP/alice.

**Comment by InnovateAsterisk** [comment]
Do you have a sample of the NOTIFY message that is end to the watcher.

**Comment by vieridipaola** [comment]
One just needs to set the Browser-Phones User Agent string to something containing the string 'digium' or 'sangoma'. Something like:

`digium-compatible Browser-Phone`

The NOTIFY messages will then contain an XML with a digium_presence tag.

When a user sets to "available" you get:
 
```
NOTIFY sip:2bl6kftd@127.0.0.1:41264;transport=ws SIP/2.0

Via: SIP/2.0/WSS 127.0.0.1:8090;rport;branch=z9hG4bKPjd4d50cc3-d68c-4f2f-a075-84135615715a;alias

From: <sip:4155@xmpp.domain.org>;tag=a5c8ddff-0d3e-4737-9ec0-7ad84192d1eb

To: "Me" <sip:web4053@xmpp.domain.org>;tag=atoilt43h9

Contact: <sip:127.0.0.1:8090;transport=ws>

Call-ID: grfjb84mfcmkmoihbb1o

CSeq: 4248 NOTIFY

Event: presence

Subscription-State: active;expires=299

Allow-Events: message-summary, presence, dialog, refer

Max-Forwards: 70

User-Agent: Asterisk PBX 18.10.0

Content-Type: application/pidf+xml

Content-Length:   524



<?xml version="1.0" encoding="UTF-8"?>
<presence entity="sip:4155@127.0.0.1:8090;transport=ws" xmlns="urn:ietf:params:xml:ns:pidf" xmlns:dm="urn:ietf:params:xml:ns:pidf:data-model" xmlns:rpid="urn:ietf:params:xml:ns:pidf:rpid">
 <note>Ready</note>
 <tuple id="4155">
  <status>
   <basic>open</basic>
  </status>
  <contact priority="1">sip:web4053@xmpp.domain.org</contact>
 </tuple>
 <tuple id="digium-presence">
  <status>
   <digium_presence type="available" />
  </status>
 </tuple>
 <dm:person />
</presence>
```

When a user sets to DND you get:

```
NOTIFY sip:2bl6kftd@127.0.0.1:41264;transport=ws SIP/2.0

Via: SIP/2.0/WSS 127.0.0.1:8090;rport;branch=z9hG4bKPj1685153e-da24-49ea-aa1a-c1dfe8e8d862;alias

From: <sip:4155@xmpp.domain.org>;tag=2b4d7c71-9b97-4640-b0e0-dbd9f71f2b9b

To: "Me" <sip:web4053@xmpp.domain.org>;tag=p5174g5t5t

Contact: <sip:127.0.0.1:8090;transport=ws>

Call-ID: grfjbefg3h0gkaqf69v2

CSeq: 21547 NOTIFY

Event: presence

Subscription-State: active;expires=138

Allow-Events: message-summary, presence, dialog, refer

Max-Forwards: 70

User-Agent: Asterisk PBX 18.10.0

Content-Type: application/pidf+xml

Content-Length:   518



<?xml version="1.0" encoding="UTF-8"?>
<presence entity="sip:4155@127.0.0.1:8090;transport=ws" xmlns="urn:ietf:params:xml:ns:pidf" xmlns:dm="urn:ietf:params:xml:ns:pidf:data-model" xmlns:rpid="urn:ietf:params:xml:ns:pidf:rpid">
 <note>Ready</note>
 <tuple id="4155">
  <status>
   <basic>open</basic>
  </status>
  <contact priority="1">sip:web4053@xmpp.domain.org</contact>
 </tuple>
 <tuple id="digium-presence">
  <status>
   <digium_presence type="dnd" />
  </status>
 </tuple>
 <dm:person />
</presence>
```

More info here:

https://wiki.asterisk.org/wiki/display/AST/Presence+State

I don't know how to show the digium_presence data in browser-phone, but maybe a nice way would be to display the text (presence state) maybe next to the registration status. If it's any of dnd, away or unavailable it should be in red (I guess).

Thanks for trying to get this feature into Browser-Phone.

**Comment by vieridipaola** [comment]
A quick phone.js hack.

In 
`function RecieveBlf`

I added right at the end of the pidf-xml clause:

```
        var DigiumPresence = xml.find("presence").find("tuple#digium-presence").find("status").find("digium_presence").attr("type");
        if (typeof DigiumPresence !== 'undefined') {
            console.log("Digium Presence", DigiumPresence);
            if ( (DigiumPresence == "dnd") || (DigiumPresence == "away") || (DigiumPresence == "unavailable") ) Presence = "Not online";
        }
```

It's fine for now, but it would be best to be able to actually show the user the content of the digium_presence attribute.

**Comment by InnovateAsterisk** [comment]
That's fine, but I have added a custom hook, so that you can do what you want there without changing the code.

Also, remember the notify message are informing you about the status of the buddy you are watching, so you will want the take the results there and update the buddy status. The function currently provides, the content type, buddy and body of the message.

**Comment by vieridipaola** [comment]
Which custom hook are you referring to?

**Comment by InnovateAsterisk** [comment]
Coming soon.

```
if(typeof web_hook_on_notify !== 'undefined')  web_hook_on_notify(ContentType, buddyObj, notification.request.body);
```

**Comment by vieridipaola** [comment]
OK, thanks, I guess the custom hook would be enough.
Maybe a comment in phone.js so that others can easily and quickly enable CustomPresence "the Digium way"...
This could be enough:

```
// To enable Digium/Sangoma Presence State, retrieve the status with:
// xml.find("presence").find("tuple#digium-presence").find("status").find("digium_presence").attr("type")
// and make sure userAgentStr contains 'digium' or 'sangoma'
```

**Comment by vieridipaola** [comment]
...and what if the buddy is of type "xmpp", but I still want to show the CustomPresence data?

I can't use this, can I?

`$("#contact-" + buddyObj.identity + "-presence").html()`

**Comment by vieridipaola** [comment]
If the buddy type is xmpp then I should either set a dynamically appended element next to 

`$("#contact-" + buddyObj.identity + "-presence").html()`

(eg. -presence-digium), and use that for my CustomPresence data, or phone.js could include that very element (-presence-digium) in UpdateBuddyList(), right?

**Comment by InnovateAsterisk** [comment]
I would not work directly with the HTML objects, rather update the memory objects.

You are already given the buddy object in the custom hook, so all you need to do is: 
```
buddyObj.presenceText = "Some cool presence text here";
```
and then call:
```
UpdateBuddyList()
```

The UpdateBuddyList will do all the work for you once you have updated the buddyObj memory object.

**Comment by vieridipaola** [comment]
In the case of an xmpp buddy the presence text is auto-updated, right?
I want to be able to "append" the Digium CustomPresence information, not overwrite anything.
I'l look into presenceText, thanks.

**Comment by InnovateAsterisk** [comment]
The problem is that the UpdateBuddyList() is lite-weight refresh function designed to be called many times. Each time, it will re-write the html, so unless you update the memory object, it will be re-written the very next time the UpdateBuddyList() is called.

I wouldn't use ```+=``` as you may end up with ```...(...)...(...)...(...)```. 

You are however going to be firing your custom hook at each NOTIFY message, so even if the underlying code has just set 
```
buddyObj.presence = "Ready";
```
You can just do this: 
```
var web_hook_on_notify = function(ContentType, buddyObj, notify){
    var DigiumPresence = <get DigiumPresence from notify>
    buddyObj.presence = buddyObj.presence + " ("+ DigiumPresence  +")";
    UpdateBuddyList();
}

```

I just tried the above: 

![image](https://user-images.githubusercontent.com/58937573/201907856-2f1d36d4-6634-4e5c-8d73-46e58b676b77.png)

**Comment by vieridipaola** [comment]
The web hook will be in function receiveblf()?

**Comment by InnovateAsterisk** [comment]
Yes, it is already:

https://github.com/InnovateAsterisk/Browser-Phone/blob/46f6911ba48d362c486089a73c7382b706e1dcc0/Phone/phone.js#L4527

**Comment by vieridipaola** [comment]
You mean presenceText for xmpp, right?

I have this now:

```
var web_hook_on_notify = function(ContentType, buddyObj, notify) {
    var xml = $($.parseXML(notify));
    var DigiumPresence = xml.find("presence").find("tuple#digium-presence").find("status").find("digium_presence").attr("type");
    if (typeof DigiumPresence !== 'undefined') {
        if (DigiumPresence == "dnd" || DigiumPresence == "away")
            buddyObj.devState = "dotOnHold";
        else if (DigiumPresence == "unavailable")
            buddyObj.devState = "dotOffline";
        if (buddyObj.type == "xmpp")
            buddyObj.presenceText = buddyObj.presenceText + " (" + DigiumPresence + ")";
        else
            buddyObj.presence = buddyObj.presence + " (" + DigiumPresence + ")";
        UpdateBuddyList();
        console.log("DEBUG: web_hook_on_notify presence for " + buddyObj.ExtNo + " should now be " + buddyObj.presenceText);
    }
}
```

This works fine, but I 'm getting concatenations like:
`
DEBUG: web_hook_on_notify presence for 4155 should now be (No Status) (available) (available) (available)`

**Comment by InnovateAsterisk** [comment]
Oh, hang on... with XMMP buddies it no longer uses the device state text "Ready" etc, in the display area under the Display Name.

It only shows the status text, and "is typing..." if they are typing.

The above example was for extensions, not XMPP. Yes, the XMPP buddies, us the memory object and parameter: ```buddyObj.presenceText``` and its set with another event.

You sort of want to mix the two... have the custom status from Asterisk, and the XMPP status? With an XMPP Buddy, the device state is still there, it's just only visible via ```buddyObj.devState``` - the little icon next to the name changes color according to the status (ready/offline/calling etc). Also, the "Ready" text falls away for the more custom status text provided via XMPP, allowing users to set a status (again like whatsapp), but then only this text shows as presence or a "(no status)".

So now, you are saying Asterisk can also give the user another status (a third "status"), not a "device state" (like ready/offline), not a "personal status" (like In a "meeting until 5pm"), something like "do not disturb" (meaning your device may be "Ready'", and your status may "in a meeting", but if you try call, you will not even get through because the device is set to DND.

Right?

**Comment by vieridipaola** [comment]
Yes, that is correct.

> `buddyObj.presenceText` and its set with another event

Which one?

**Comment by vieridipaola** [comment]
I'm afraid that if I need a web hook in OnPresenceChange to customize presenceText depending on DigiumPresence (CustomPresence) then I won't be able to do it because I won't have access to the notify body.

Hence a workaround would be my other post here:
https://github.com/InnovateAsterisk/Browser-Phone/issues/363
and I'd abandon my idea of mixing XMPP with Asterisk CustomPresence.

**Comment by vieridipaola** [comment]
OK, the following hack is ugly, but it works for me:

```
var web_hook_on_notify = function(ContentType, buddyObj, notify) {
    var xml = $($.parseXML(notify));
    var DigiumPresence = xml.find("presence").find("tuple#digium-presence").find("status").find("digium_presence").attr("type");
    if (typeof DigiumPresence !== 'undefined') {
        if (DigiumPresence == "dnd" || DigiumPresence == "away")
            buddyObj.devState = "dotOnHold";
        else if (DigiumPresence == "unavailable")
            buddyObj.devState = "dotOffline";
        if (buddyObj.type == "xmpp") {
            // Ugly hack to remove previous DigiumPresence:
            buddyObj.presenceText = buddyObj.presenceText.replace(" (available)", "");
            buddyObj.presenceText = buddyObj.presenceText.replace(" (unavailable)", "");
            buddyObj.presenceText = buddyObj.presenceText.replace(" (dnd)", "");
            buddyObj.presenceText = buddyObj.presenceText.replace(" (not_set)", "");
            buddyObj.presenceText = buddyObj.presenceText.replace(" (away)", "");
            buddyObj.presenceText = buddyObj.presenceText.replace(" (xa)", "");
            buddyObj.presenceText = buddyObj.presenceText.replace(" (chat)", "");
            buddyObj.presenceText = buddyObj.presenceText + " (" + DigiumPresence + ")";
        } else
            buddyObj.presence = buddyObj.presence + " (" + DigiumPresence + ")";
        UpdateBuddyList();
    }
}
```

If you find a better and cleaner way please let me know.

**Comment by InnovateAsterisk** [comment]
You will find the custom web hook in this or a previous update:
https://github.com/InnovateAsterisk/Browser-Phone/commit/36751ca929ba884ce57c19077d6ac6680adf14d4
