### ISSUE TITLE
AutoDelete

### ISSUE THREAD

**Issue by vieridipaola** [InnovateAsterisk/Browser-Phone#357]
Hi,

I haven't had time to dig into this, but it seems that when creating a new buddy and leaving the Auto Delete check button untouched (ie. unchecked) the buddy object is created with AllowAutoDelete = true.

If I then edit the buddy and simply press Save (leaving Auto Delete unchecked) the buddy obj AllowAutoDelete updates to false.

I haven't looked at phone.js yet, but it's probably a trivial condition to fix.

**Comment by InnovateAsterisk** [comment]
No, If you use the Add Buddy from the normal UI button, its default to not auto delete (since the check box is visible and unchecked).

However any auto generated buddy, is set to AutoDelete true by default. (inbound and outbound calls.)

If you are creating your own buddies with your own code, you can include the AutoDelete as a parameter.

**Comment by vieridipaola** [comment]
It's because of:

```
var Buddy = function(type, identity, CallerIDName, ExtNo, MobileNumber, ContactNumber1, ContactNumber2, l
astActivity, desc, Email, jid, dnd, subscribe, subscription, autoDelete){
[...]
    this.AllowAutoDelete = (autoDelete)? autoDelete : true;
```

So the default is true if passed param as "autoDelete" is false?
So the default 'false' is converted to 'true'.

I guess

`this.AllowAutoDelete = autoDelete;`

would do.

**Comment by vieridipaola** [comment]
Yes, works fine now.
Thanks

**Comment by InnovateAsterisk** [comment]
I have also added:
```
let AutoDeleteDefault = (getDbItem("AutoDeleteDefault", "1") == "1");                   // For automatically created buddies (inbound and outbound), should the buddy be set to AutoDelete.
```
So you can control this behaviour 
```
this.AllowAutoDelete = (typeof autoDelete !== 'undefined')? autoDelete : AutoDeleteDefault;
```

**Comment by vieridipaola** [comment]
Great

**Comment by vieridipaola** [comment]
Well, rethinking this it seems that defaulting to "true" might be an issue for xmpp buddies created from roster.

In my case I want  to keep using the default for AutoDeleteDefault (which means that auto-created buddies are maked with Auto Delete = true), except that I want xmpp roster auto-created buddies to be marked with Auto Delete = false.
I think one would agree that if the buddy is in the roster it should always be the user who decides to explicitly delete it.
Consider this:  a user works on a PC and creates XMPP buddies and even marks them as Auto Delete = false. Thsi info is sent to the XMPP server. The user then changes PC, logs in, and retrieves the roster buddies. They will be auto-created  with AllowAutoDelete=true. If there's a MaxBuddies or BuddyMaxAge setting _t could very well delete the xmpp buddy -- even in the roster. That would be unwanted behavior in my opinion.

**Comment by vieridipaola** [comment]
I think XmppGetBuddies function should call MakeBuddy by setting autodelete to false, or at least allow customization via a phoneOptions or DB setting.

**Comment by InnovateAsterisk** [comment]
I would be happy to set this to ```false```, as its seems more part of the internal workings of XMPP, and unlikely that there would be hundreds of buddy automatically created, especially since from inbound callers are made into regular contacts or extensions.

**Comment by vieridipaola** [comment]
> Remember also someone can easily change this setting after the buddy is created.

That's fine if the user wants to.

**Comment by vieridipaola** [comment]
> buddyObj = MakeBuddy("xmpp", false, false, true, displayName, buddyDid, jid, false, true, false);

Yes, that's how I changed my copy of phone.js.
If you commit the change to github I can update and delete my copy.
Thanks

**Comment by vieridipaola** [comment]
One may want to do the same for "group" within XmppGetBuddies.

**Comment by vieridipaola** [comment]
Shouldn't it be more like this?

`buddyObj = MakeBuddy("xmpp", false, false, true, displayName, buddyDid, jid, false, buddyObj.ExtNo, false);`

**Comment by InnovateAsterisk** [comment]
https://github.com/InnovateAsterisk/Browser-Phone/commit/36751ca929ba884ce57c19077d6ac6680adf14d4

**Comment by InnovateAsterisk** [comment]
> Shouldn't it be more like this?
buddyObj = MakeBuddy("xmpp", false, false, true, displayName, buddyDid, jid, false, buddyDid, false);

True! 
```
function MakeBuddy(type, update, focus, subscribe, callerID, did, jid, AllowDuringDnd, subscribeUser, autoDelete)
```

**Comment by InnovateAsterisk** [comment]
Fixed in 
https://github.com/InnovateAsterisk/Browser-Phone/commit/ec7548392e09ecf889a876758e9b1b21a6b5aa68
