### ISSUE TITLE
XMPP name on client update

### ISSUE THREAD

**Issue by vieridipaola** [InnovateAsterisk/Browser-Phone#360]
Hi,

When an xmpp buddy is in the buddy list and is in the "both" subscribed state in the xmpp server (which means everything is OK) the Browser Phone user can edit the xmpp buddy and change its "name". This attribute ("name") is not updated on the xmpp server roster for the Browser Phone JID.

Can/Should it be updated?

**Comment by InnovateAsterisk** [comment]
From what I remember, this was something of a "_how xmpp works_" thing. 

I can look into this further but it seems that it was like this; I may call someone Bob, but they may refer to them self (via vCard) as Mr Smith, so when I add them, (I start my by making the buddy,) I just call them what I know, so to Browser Phone, it has the identity on the internal side as Bob, so then when the vCard is downloaded, it corrects it to Mr Smith. So who is right? i'm not sure, they both seem right. Should it update? Again, not sure. It sort of seems like it should remain as is unless it becomes an issue.

**Comment by vieridipaola** [comment]
OK, makes sense. Closing this issue, and considering it as an xmpp thing.
Thanks!
