### ISSUE TITLE
Openfire Roster List

### ISSUE THREAD

**Issue by rgonzalez-in** [InnovateAsterisk/Browser-Phone#362]
Hello:

I have this issue:

![image](https://user-images.githubusercontent.com/27745450/202071118-911db165-2ee7-4f8f-bc7a-c37304c582a2.png)

Please help me.

Regards.

**Comment by vieridipaola** [comment]
Same here.

It is not Openfire-specific.
I have this error too, and I'm running Prosody.

**Comment by InnovateAsterisk** [comment]
The undefined object is ```userAgent.BlfSubs```, this is an array holding the subscribe objects. In a recent update this array was created with the ```userAgent``` object, so its almost impossible to be undefined. I'm just checking to see if its deleted at any point.

**Comment by vieridipaola** [comment]
It doesn't *always* happen.
It may be due to a race condition of some sort.

**Comment by InnovateAsterisk** [comment]
https://github.com/InnovateAsterisk/Browser-Phone/commit/36751ca929ba884ce57c19077d6ac6680adf14d4
