### ISSUE TITLE
Set Status and code injection

### ISSUE THREAD

**Issue by vieridipaola** [InnovateAsterisk/Browser-Phone#364]
Hi,

I'm not sure this has any security risks -- probably not.
Just wanted to point out that a user can insert HTML code with "Set Status".

eg. one could type this in the Set Status input box:

`<i class="fa fa-hand-spock-o">`

There's probably no harm in that, but it can be a bit messy if a user sets this status:

`<script>alert(phoneOptions.SipUsername);</script>`

as it will make an alert window pop up for all the subscribed buddies...

So maybe Set Status should only accept a-zA-Z0-9. Just a thought.

**Comment by InnovateAsterisk** [comment]
Good point

**Comment by InnovateAsterisk** [comment]
https://github.com/InnovateAsterisk/Browser-Phone/commit/36751ca929ba884ce57c19077d6ac6680adf14d4
