### ISSUE TITLE
UpdateBuddyList: custom sorting

### ISSUE THREAD

**Issue by vieridipaola** [InnovateAsterisk/Browser-Phone#365]
Hi,

Would it be possible to add yet another web hook? This time in function UpdateBuddyList()?

The function sorts the buddy list according to activity timestamp:

```
    // Sort and shuffle Buddy List
    // ===========================
    Buddies.sort(function(a, b){
        var aMo = moment.utc(a.lastActivity.replace(" UTC", ""));
        var bMo = moment.utc(b.lastActivity.replace(" UTC", ""));
        if (aMo.isSameOrAfter(bMo, "second")) {
            return -1;
        } else return 1;
        return 0;
    });
```

I would like to customize the above in order to sort and filter according to other criteria. For instance:

```
    // Sort and shuffle Buddy List
    // ===========================
    Buddies.sort(function(a, b){
        var aMo = moment.utc(a.lastActivity.replace(" UTC", ""));
        var bMo = moment.utc(b.lastActivity.replace(" UTC", ""));
        if (aMo.isSameOrAfter(bMo, "second")) {
            return -1;
        } else return 1;
        return 0;
    });

    Buddies.sort(function(a, b){
        if(a.AllowAutoDelete == true && b.AllowAutoDelete == false) return 1; // +1 means that b sorted before a
        if(a.AllowAutoDelete == false && b.AllowAutoDelete == true) return -1; // -1 means that a sorted before b (so display a before b)
        if(a.type != "xmpp" && b.type == "xmpp") return 1; // +1 means that b sorted before a
        if(a.type == "xmpp" && b.type != "xmpp") return -1; // -1 means that a sorted before b (so display a before b)
        return 0; // 0 means no change in sort order
    });

    for(var b = 0; b < Buddies.length; b++) {
        var buddyObj = Buddies[b];

        if(phoneOptions.applyPersistentBuddyFilter == true && buddyObj.AllowAutoDelete == true && buddyObj.type != "xmpp") {
            console.log("skipping buddy in UpdateBuddyList", buddyObj);
            continue;  // persistent-only buddies
        }

        if(filter && filter.length >= 1){
            // Perform Filter Display
[...]
```

The above orders the buddy list so that the ones with Auto Delete checked are last. I also want xmpp contacts to come first.

BTW in function XmppGetBuddies there is a call to auto-create xmpp buddies from roster (https://github.com/InnovateAsterisk/Browser-Phone/blob/46f6911ba48d362c486089a73c7382b706e1dcc0/Phone/phone.js#L13824):

```
                        console.log("Adding roster (xmpp):", buddyDid, "-", displayName);
                        buddyObj = MakeBuddy("xmpp", false, false, true, displayName, buddyDid, jid);
```

I haven't had time to look into this, but the MakeBuddy function has an autodelete parameter which should default to false if undefined, right?
In other words, xmpp auto-created buddies from roster should have AllowAutoDelete = false, right? Isn't that the expected behavior?
However, if I print out Buddies in the console I see AllowAutoDelete: true for these xmpp contacts created from roster.
Furthermore, the xmpp buddy in Local Storage has nothing related to autodelete.
Is this consistent?

Coming back to the customization of UpdateBuddyList() the custom code then filters out the buddy list so that non-xmpp buddies and those that are marked with Auto Delete are not displayed.
That's because trhrough the custom setting phoneOptions.applyPersistentBuddyFilter I want users to be able to toggle between a full buddy list and one with just the "persistent" non-deletable buddies.

Can phone.js be updated so that UpdateBuddyList() can be easily customized without changing the upstream code?

**Comment by InnovateAsterisk** [comment]
Included in this or an older release:
https://github.com/InnovateAsterisk/Browser-Phone/commit/ec7548392e09ecf889a876758e9b1b21a6b5aa68
