### ISSUE TITLE
Provisioning buddies and auto-dial

### ISSUE THREAD

**Issue by vieridipaola** [InnovateAsterisk/Browser-Phone#37]
Hi,

I was wondering if we could add a simple way to automatically add a list of buddies/contacts. Some kind of provisioning (of a contact list)...

Here's what I do now. In my index file I include a 'custom_post.php' file right after phone.js. 

```
# cat custom_post.php
<?php

header('Content-Type: application/javascript');

?>
function ProvisionBuddyList(number, displayName, mobileNum, contactNum1, contactNum2, position, description, email){
    number = number.trim();
    if(number.length == 0){
        console.log("Cannot provision buddy");
        return;
    }
    console.log("Provisioning buddy " + displayName + " with number " + number);

    var buddyObj = FindBuddyByNumber(number);
    if(buddyObj == null) buddyObj = FindBuddyByExtNo(number);
    // Make new contact of its not there
    if(buddyObj == null) {

        // Add Contact / Extension
        var json = JSON.parse(localDB.getItem(profileUserID + "-Buddies"));
        if(json == null) json = InitUserBuddies();

        if(number.length > DidLength){
            // Add Regular Contact
            var id = uID();
            var dateNow = utcDateNow();
            json.DataCollection.push(
                {
                    Type: "contact",
                    LastActivity: dateNow,
                    ExtensionNumber: "",
                    MobileNumber: mobileNum,
                    ContactNumber1: number,
                    ContactNumber2: contactNum2,
                    uID: null,
                    cID: id,
                    gID: null,
                    DisplayName: displayName,
                    Position: "",
                    Description: description,
                    Email: email,
                    MemberCount: 0
                }
            );
            var buddyObj = new Buddy("contact", id, displayName, "", mobileNum, number, contactNum2, dateNow, description, email);
            AddBuddy(buddyObj, false, false);
        }
        else {
            // Add Extension
            var id = uID();
            var dateNow = utcDateNow();
            json.DataCollection.push(
                {
                    Type: "extension",
                    LastActivity: dateNow,
                    ExtensionNumber: number,
                    MobileNumber: mobileNum,
                    ContactNumber1: contactNum1,
                    ContactNumber2: contactNum2,
                    uID: id,
                    cID: null,
                    gID: null,
                    DisplayName: displayName,
                    Position: position,
                    Description: "",
                    Email: email,
                    MemberCount: 0
                }
            );
            var buddyObj = new Buddy("extension", id, displayName, number, mobileNum, contactNum1, contactNum2, dateNow, position, email);
            AddBuddy(buddyObj, false, false, true);
        }
        // Update Size:
        json.TotalRows = json.DataCollection.length;

        // Save To DB
        localDB.setItem(profileUserID + "-Buddies", JSON.stringify(json));

    }
}

$(document).ready(function () {

console.log('Start provisioning buddies');

<?php

@require_once('custom_buddies.php');

?>

console.log('Update buddy list');
UpdateBuddyList();

});
```

The file custom_buddies.php is generated by another script, and it's basically a list of calls to the function defined above:

```
ProvisionBuddyList('1234', 'John Doe', '', '', '', '', '', '');
ProvisionBuddyList('5678', 'Mr Smith', '', '', '', '', '', '');
...etc...
```

I usually have hundreds of these function calls.

Now, in order to not have to maintain this provisioning function myself, would it be possible to somehow include it in phone.js?
I know that calling this function hundreds of times can block the UI, but I can live with that. Maybe a "worker" would be better off, but I'm not sure how to program that just yet.
I also know that calling this may occur before userAgent is not null.

I would also like to expand on this topic and ask if it is possible to implement some sort of auto-dial.
In this case, what I need to do is:

1) not provide hundreds of buddies but just one (actually it would be an Asterisk extension leading to a 'queue')
2) disable the "Find someone" and "Add someone" UI elements
3) remove or disable 'Add someone' from the user's dropdown menu
4) on page load, auto-dial the buddy that has been provisioned (auto-dial with video if available)

**Comment by vieridipaola** [comment]
Step (4) could be done by setting a variable such as:

`(getDbItem("autodialFirstBuddy", "0") == "1")`

**Comment by InnovateAsterisk** [comment]
The Buddy list is just json, so you can populate the localDB value with a json string from your own provisioning in a pre script. 
``` (pseudo php code)
<?php
...
echo localDB.setItem(profileUserID + "-Buddies", "{ ... json string .... }");
...
?>
```
To handle local edits (after loading) just poll the same localDB, and push it pack to your provisioning server with ajax. (You can include your own change detection code locally to limit wasteful posts)
``` (pseudo javascript code)
window.setInterval(function(){
    var myBuddies = localDB.getItem(profileUserID + "-Buddies");
    if(hasChanged(myBuddies)){
       $.ajax({ 
           type:'POST', url: '/provisioning.php',data: myBuddies
       });
    }
}, 1 * 60 * 1000);
```

**Comment by InnovateAsterisk** [comment]
With regards to:

> 1. not provide hundreds of buddies but just one (actually it would be an Asterisk extension leading to a 'queue')
> 2. disable the "Find someone" and "Add someone" UI elements
> 3. remove or disable 'Add someone' from the user's dropdown menu
> 4. on page load, auto-dial the buddy that has been provisioned (auto-dial with video if available)

Most of these will be solved in version 0.0.2, this will be done in the next few days. Mostly this update changes from a "buddy" style system to a "Lines" style system. It's something that has been on the back of my mind anyway. This solves a lot of internal problems anyway, and mostly allows a load-and-dial type system that people a more accustom too. Also, this eliminates a massive problem that existed that limits you to only being able to dial (or receive a call from) a single buddy... so now, you can dial a buddy again and again... there is no limit to the number of lines, and it doesn't mind that the same buddy is being called.

**Comment by vieridipaola** [comment]
I'm eager to see version 0.0.2.... I'd like to thank you for this great project.
Also, you just zapped my provisioning function with a single line of code... Wow.
Thanks!

**Comment by vieridipaola** [comment]
BTW, regarding the "auto-dial" feature, I'm not sure if my idea of "passing along the number to be dialed via GET or POST" to, say, index.php is the best way to go. Maybe one should simply create "call files" in Asterisk whenever triggered by a web app (for example) which would first call the extension registered through Browser-Phone and then bridge it with a channel dialing out the destination number.

Anyway, just thought I'd share this now... I don't want to distract you from v. 0.0.2, but as I mentioned the auto-dial feature, I thought it would be better to mention it here.

**Comment by vieridipaola** [comment]
Also, setting the following in a pre script implies that profileUserID is defined. First time around, it won't be. So I guess I should create it first with my own algo (or include uID() in the pre script). Maybe the phone.js file could be split in two? A file such as phone_lib.js would contain all the useful lib functions such as uID() and would have to be loaded before phone.js in the HTML page. That way I could insert a pre script between phone_lib.js and phone.js.

**Comment by InnovateAsterisk** [comment]
The way I would approach this is, that if you are going to be provisioning your own settings, then provision everything, including the uID. So make something up in your back-end, it could even be a database id value, and just apply all your own values to the localDB. Again, you can get php or whatever to output (pseudo code):

```(php)
<script id="_pre">
<?php
echo localDB.setItem("profileUserID", "$profileUserID");
echo localDB.setItem(profileUserID + "-Buddies", "{ ... json string .... }");
?>
</script>
```

The only purpose of the localDB is to save the user settings for the next time. (This will be come more and more like this, if it's not already). Long term storage (CDR's, Call Recordings, etc), will all move to the indexDB.

**Comment by vieridipaola** [comment]
Yes, I'm doing that now, but am facing a new problem. The idea of provisioning "buddies" is a great way to help people search through a large directory. Unfortunately, I have to provision hundreds of contacts/buddies (healthcare facility) even if I try to trim these down according to who logs in. The problem I see is that the browser becomes sluggish (too many contacts make the whole page slower). I also have a UI problem because some contact/extension names are long and wrap around in a second line. That causes overlapping with the next element (the hint/presence status of the next buddy is partially hidden). Anyway, I'm going to have to rethink how and if I'm going to provision buddies. 
So at this point, I guess we can close this issue.
Thanks!
