### ISSUE TITLE
filter and sort settings

### ISSUE THREAD

**Issue by vieridipaola** [InnovateAsterisk/Browser-Phone#376]
Hi,

In the filter and sort settings would it be possible to also add another option to "hide Auto Delete" so that the buddies that are marked with Auto Delete are not displayed?
If the user selects to "hide" these buddies then it would be better to also change the background color of the "filter and sort" button so as to warn that some buddies are filtered out.

A default phoneOptions setting for this new option would be nice too.

**Comment by InnovateAsterisk** [comment]
Currently the indication for auto-delete items is a small clock icon next to the last activity - this is a visual indication to the user that a buddy is set to auto-delete. It's subtle, but noticeable.

There is also a "pinned" option I want to work in, that will allow you to stick a few buddies to the top of the list - this will be visually indicated too.

For the hidden auto-delete buddies, it would probably be best to say something like:
"(Not showing 10 Auto Delete Buddies)" in small at the bottom of the list, and probably clickable to show them. I'll check it out and see whats best.

**Comment by vieridipaola** [comment]
> "(Not showing 10 Auto Delete Buddies)" in small at the bottom of the list, and probably clickable to show them

Oh, yes, that would be even better, definitely.
Thanks!
