### ISSUE TITLE
disable account settings

### ISSUE THREAD

**Issue by vieridipaola** [InnovateAsterisk/Browser-Phone#38]
Hi,

The option:

setItem("EnableAccountSettings", "0")

works fine as it grays out the tab element to configure account details.

However, when I click on the "configure extension" from the user's dropdown menu, this very tab is shown first and, even if it's grayed out, I can still see all the settings, scroll down and press the save button.
A possible solution would be to only display the "enabled tabs", or focus on an enabled tab on window open.

**Comment by InnovateAsterisk** [comment]
Good point... will fix

**Comment by InnovateAsterisk** [comment]
Fixed in: ad2d88

Tho it hides the disabled tabs, so if you disable all of them it will display an empty window
