### ISSUE TITLE
Remove Video Configuration

### ISSUE THREAD

**Issue by rgonzalez-in** [InnovateAsterisk/Browser-Phone#383]
Hello:

On phone.js this line:

let EnableVideoCalling = (getDbItem("EnableVideoCalling", "1") == "1");                 // Enables Video during a call

![image](https://user-images.githubusercontent.com/27745450/204424930-898aee9d-efc0-4e1f-ac23-9689243c1484.png)
![image](https://user-images.githubusercontent.com/27745450/204425216-32289074-ff09-4741-a08f-0a441e65b806.png)

let EnableVideoCalling = (getDbItem("EnableVideoCalling", "0") == "1");                 // Disable Video during a call

![image](https://user-images.githubusercontent.com/27745450/204425057-08b1db94-e10c-4e26-aa19-03fdbcb8fcf7.png)
![image](https://user-images.githubusercontent.com/27745450/204425124-d447bfc2-8e6c-4f73-879e-f276c6a31a37.png)

But the Video Configuration is still available:

![image](https://user-images.githubusercontent.com/27745450/204425388-15d94a2a-5a20-4298-8883-ecac34a13d5c.png)

Is posible remove this configuration too?

Regards.

**Comment by InnovateAsterisk** [comment]
Good point.
