### ISSUE TITLE
DialByLine and extensions that are not numbers

### ISSUE THREAD

**Issue by vieridipaola** [InnovateAsterisk/Browser-Phone#39]
Hi,

I usually have numbers for extensions, but in some cases I use alphanumeric strings such as "patient", "doctor", etc. In other words, I have pjsip extensions registering as strings without numbers or containing numbers and letters.

The problem is now with the DialByLine function as it tries to extract the number with \d before @ in the URI. It fails of course if it's not an integer, and the peer can't be contacted.

Can't an "extension" be just about anything?

**Comment by InnovateAsterisk** [comment]
I'm generally against this as its common practice to call people via a telephone number.... however I guess this could be a setting.

**Comment by InnovateAsterisk** [comment]
Set the flag: **EnableAlphanumericDial** to **1** to allow this feature, it will allow dialling of
``` \da-zA-Z\*\#\+```

**Comment by vieridipaola** [comment]
Itty bitty mistake here:

```
 # grep 'var EnableAlphanumericDial' phone.js
var EnableAlphanumericDial = (getDbItem("EnableNotificationSettings", "1") == "1");     // Allows calling /[^\da-zA-Z\*\#\+]/g default is /[^\d\*\#\+]/g

```

Thanks :-)

**Comment by InnovateAsterisk** [comment]
Fixed
