### ISSUE TITLE
MaxBuddyAge

### ISSUE THREAD

**Issue by vieridipaola** [InnovateAsterisk/Browser-Phone#392]
Hi,

I set MaxBuddyAge to 7 which is supposed to delete every buddy contact older than 7 days just as long as autodelete is true.

I currently have several 9-day-old autodeletable contacts still showing up in the buddy list - the last one of which gives e a console error when trying to open it (and the right panel stays blank).

```
Selecting Buddy: 3044
Uncaught TypeError: history.get(...) is undefined
```

So it seems that the last one of these expired contacts actually has been removed but is still in memory. All the other 9-day-old contacts are still there and their history is accessible.
If I reload the page (F5) the last buddy that gave me the "history" error (ie. 3044 in my example) vanishes as expected while the rest of the 9-day-old contacts are still there. Now, the last one of these gives me the "history" console error when selecting it.

So it seems that only one buddy is partially removed on page load.

If I look at the console when loading Browser Phone I see:

```
Running Buddy Cleanup for activity older than:  2022-12-09 8:07:21 AM phone.js:9340:21
This buddy is too old, and will be deleted:  2022-12-07 8:27:43 AM phone.js:9348:33
Closing Buddy: 1670230727602162F phone.js:10222:13
Unsubscribe:  167058063864924D7 phone.js:4318:13
Updating Buddy List... phone.js:9460:13
Selecting previously selected buddy... null phone.js:1551:17
```

Running v. 0.3.20.

Any ideas?

**Comment by InnovateAsterisk** [comment]
> So it seems that only one buddy is partially removed on page load.

Yes, and it seems that because the history is gone, it fails the delete, and now its stuck partially removed. Ill have to apply a condition for this.
