### ISSUE TITLE
Call button and text within search input box

### ISSUE THREAD

**Issue by vieridipaola** [InnovateAsterisk/Browser-Phone#40]
Hi,

If user types something in the "Find someone" text input field then maybe when click the "call" button next to it, it should simply take its value and DialByLine (directly, without the need to show the dialpad). Actually, even an ENTER key event could be enough to trigger the call.

Ideally, it would default to a video call with a downgrade to audio if one of the two peers does not support video.

**Comment by InnovateAsterisk** [comment]
Nice idea, but I would prefer the people get the choice, I have an idea for this.
