### ISSUE TITLE
allow disabling of specific elements

### ISSUE THREAD

**Issue by vieridipaola** [InnovateAsterisk/Browser-Phone#41]
I currently disable a few things when a specific user logs in:

```
document.getElementById("BtnFreeDial").style.display = "none";
document.getElementById("BtnAddSomeone").style.display = "none";
document.getElementById("BtnCreateGroup").style.display = "none";
document.getElementById("txtFindBuddy").style.display = "none";
```

I would also like to remove the "Add someone" option from the profile menu, but that requires changing some js code.

In:
`function ShowMyProfileMenu`

the dhtmlx menu ids can be modified with:

`menu.splice`

as it is already the case for 'enabledGroupServices'.

Could another setting be created so that these elements can be hidden?

eg.

```
enabledAddSomeone
enabledFreeDial
enabledFindBuddy
```

**Comment by InnovateAsterisk** [comment]
So you basically don't want any of the functionality? ;(

**Comment by vieridipaola** [comment]
Of course I do :-), but some users shouldn't. Just a quick example: teleconsulting patient-doctor. A patient receives a URL via SMS, opens  the link in a smartphone to Browser-Phone (with custom php), we program the patient's Browser-Phone to immediately auto-dial a specific Asterisk queue. The call will be answered only when the doctor is ready and in the queue. In the meantime, the leaner the patient's web UI, the better. No need to add buddies, dial, etc. That's the only case for now where I need to trim things down.

**Comment by InnovateAsterisk** [comment]
Ok, will do.
