### ISSUE TITLE
No audio for WebRTC client

### ISSUE THREAD

**Issue by hayzamjs** [InnovateAsterisk/Browser-Phone#440]
Hello,

I know this is not specific to this repo, but I thought I could ask for some insights.

I have 2 extensions configured on asterisk

```
[199]
type=endpoint
aors=199
auth=199
use_avpf=yes
media_encryption=dtls
dtls_cert_file=/etc/asterisk/certs2/fullchain.pem
dtls_private_key=/etc/asterisk/certs2/privkey.pem
dtls_verify=fingerprint
dtls_setup=actpass
ice_support=yes
media_use_received_transport=yes
rtcp_mux=yes
context=helloworld2
disallow=all
allow=opus

[199]
type=auth
auth_type=userpass
username=199
password=199@pass1

[199]
type=aor
max_contacts=1
remove_existing=yes
```

This is what the webrtc extension looks like, I have a dialplan that just plays an audio when called to 1234. With the regular extension everything works fine but with the webrtc extension using browserphone I am unable to hear anything. I can see with `rtp set debug on` that there are RTP packets being set to the correct IP address of my webrtc client like this:

```
Sent RTP packet to      49.37.212.107:62658 (via ICE) (type 111, seq 020449, ts 102720, len 000032)
Sent RTP packet to      49.37.212.107:62658 (via ICE) (type 111, seq 020450, ts 103680, len 000033)
Sent RTP packet to      49.37.212.107:62658 (via ICE) (type 111, seq 020451, ts 104640, len 000030)
Sent RTP packet to      49.37.212.107:62658 (via ICE) (type 111, seq 020452, ts 105600, len 000032)
Sent RTP packet to      49.37.212.107:62658 (via ICE) (type 111, seq 020453, ts 106560, len 000027)
Sent RTP packet to      49.37.212.107:62658 (via ICE) (type 111, seq 020454, ts 107520, len 000029)
Sent RTP packet to      49.37.212.107:62658 (via ICE) (type 111, seq 020455, ts 108480, len 000027)
Sent RTP packet to      49.37.212.107:62658 (via ICE) (type 111, seq 020456, ts 109440, len 000025)
```

`49.37.212.107` is my WAN IP (the webrtc client machine)

I can also see the packets reaching my machine with the webrtc client in wireshark 

![image](https://user-images.githubusercontent.com/3922884/220102314-466e5bcc-e03e-423c-bdaa-c93ddb5ac69f.png)

45.x.x.x is the PBX running Asterisk 20.x LTS, I don't see anything much in the web browser dev tools console of Browser Phone either. 

Any pointers would be greatly appreciated!

**Comment by hayzamjs** [comment]
I browsed around a bit on this repo and found out that 

![image](https://user-images.githubusercontent.com/3922884/220168445-c9fd500e-55bc-4338-a057-da1de01a67ae.png)

This might be unusual? 

![image](https://user-images.githubusercontent.com/3922884/220168657-0fed6fe5-f2d7-4b8e-b1f5-f7c4e9ec5514.png)

This is the first few lines of my wireshark output when I begin a call with the Browser Phone client

**Comment by InnovateAsterisk** [comment]
Rather use 
webrtc=yes 
In your endpoint. (Rather than specifying the webrtc settings)

**Comment by hayzamjs** [comment]
Okay

These are my configs just for clarity:

rtp.conf:

```
[general]
rtpstart=10000
rtpend=20000
icesupport=yes
stunaddr=stun.l.google.com:19302
```

extensions.conf

```
[transport-udp]
type = transport
protocol = udp
bind = 0.0.0.0:5060

[wss]
type=transport
protocol=wss
bind=0.0.0.0

[199]
type=endpoint
aors=199
auth=199
dtls_auto_generate_cert=yes
webrtc=yes
context=helloworld2
disallow=all
allow=opus,ulaw

[199]
type=auth
auth_type=userpass
username=199
password=199@pass1

[199]
type=aor
max_contacts=1
remove_existing=yes

[3001]
type=endpoint
context=helloworld2
disallow=all
allow=opus
auth=3001
aors=3001

[3001]
type=auth
auth_type=userpass
password=3001pass
username=3001

[3001]
type=aor
max_contacts=1
remove_existing=yes
```

http.conf:

```
[general]
enabled=yes
bindaddr=0.0.0.0
bindport=8088
tlsenable=yes
tlsbindaddr=0.0.0.0:8089
tlscertfile=/etc/asterisk/keys/asterisk.crt
tlsprivatekey=/etc/asterisk/keys/asterisk.key
```

Unfortunately I'm still having the issue of no audio to the webrtc client also I still see the DTLSv1.0 error on my wireshark still

**Comment by InnovateAsterisk** [comment]
Then it can be a compile issue with the crypto related files. There may be a missing dependency. Can you see any further information about the error, or something on the CLI?

**Comment by hayzamjs** [comment]
You were right! My compile of openssl didn't have support for DTLS for some reason. Once that was fixed audio started working perfectly. Thank you for the advice and also for the awesome repo 👍🏻
