### ISSUE TITLE
Naming

### ISSUE THREAD

**Issue by Fred-Zweig** [InnovateAsterisk/Browser-Phone#47]
Hi,

Thank you so much for developing and publishing this amazing project. It's really impressive what you have achieved. Thank you also for publishing it under a free software license.

Either knowingly or unknowingly, by choosing Asterisk as a backend, you created the most efficient browser softphone / web video conferencing application. This is because Asterisk is written in C, the most efficient programming language for server resources usage. Jitsi Meet is also an interesing web conferencing application but because the developers made the wrong choice when they used Java as programming language for the backend, Jitsi Meet will never surpass your application in performance and popularity. Thank you also for not using node.js and the related frameworks. I'm strongly convinced that node.js is a big failure: because of the wrong programming language it uses: JavaScript is only suitable for client-side programming, people shouldn't have 'stretched' it to use it for server-side programming. So, by using only HTML, JavaScript and CSS for the frontend and Asterisk as backend, you created the best architecture possible for this kind of application.

I think your application will be the only complete, free and open source, self-hosted, Skype replacement and also a self-hosted Zoom replacement. But for this to happen I think a new name, simple and easy to pronounce would fit better than 'Browser Phone'. What do you think about **Sipspace** or **sipspace** ?

**Comment by InnovateAsterisk** [comment]
Thanks @Fred-Zweig, for you message, and appreciation! This app has a long way to go before it's anything close to a Zoom, Skype or Teams alternative, but - yes the idea was that it could fill the gap for people... well... for the people who prefer to do it them self. 

My hope is that slowly people begin to see this as a true alternative to a desktop phone, by leveraging the built-in features like the "Activity Stream" that can show a complete history of all your activity, and not be reliant on the PBX call detail record to provide only a single slice of information.

A beautiful future for this app would be; one that integrates calling (will recordings), with instant messaging (of any kind), Email, even Fax, so that any interaction with a contact (or group), over any medium at all, is neatly and chronologically displayed.

The name... well I guess, once i'm closer to that future, im sure ill come up with a cool (one-or-two-syllable word) name for it ;-)

**Comment by Fred-Zweig** [comment]
Creating a complete, free and open source, self-hosted, Skype replacement, has been one of the main goals of the FOSS community for many years. Unfortunately, all the completely free and open source applications that have attempted to replace Skype somehow failed: mainly because of the wrong choice of programming languages and frameworks. I gave Jitsi Meet as an example, another example of relative failure is Nextcloud Talk. As you may know, Nextcloud is completely free and open source and is very good as a Dropbox replacement, but the Talk app uses a non-optimal JavaScript library (simpleWebRTC) and doesn't use a central server to stream video: all the streaming is done in a peer-to-peer manner, based on WebRTC alone: this burdens the users' browsers so much, that Talk can't be used by more than 4 users in a video conference. So, what if you want to have a videoconference with 7 or 10 participants ? Another example is Janus, a WebRTC Server which although written in C, can't surpass Asterisk as a SIP to WebRTC gateway (this from what I heard about Janus and what I know from my experience with Asterisk). Besides, Asterisk can do so much more than interacting with WebRTC clients. I won't speak about the multiple media servers based on node.js, which are from the beginning condemned to mediocrity because JavaScript is the wrong language for server-side programming.

In conclusion, the architecture that you have chosen for this type of application is the best possible. I was thinking to write a similar application myself but it would have taken me too much time. That is why I was so glad I found your project.

At this stage, I can contribute with suggesting the best SIP trunk providers in terms of clear sound at the lowest prices possible, so that Asterisk can be connected to their servers and make your application capable to make phone calls to PSTN numbers, and also accept call-in-conference from regular PSTN numbers. These are Telnyx and Localphone. They offer local phone numbers in almost all countries.

In terms of SMS, the best providers in terms of good deliverability at the lowest prices possible, the best provider, with good API that your application can connect to, is Telnyx. Plivo is also good in terms of prices and quality but they don't offer SMS enabled numbers in as many countries as Telnyx. Vonage offers the widest coverage of local phone numbers that can be rented, but they are more expensive than Telnyx.

In terms of FAX, the best provider is Phaxio. I'm already using their API in an application to send faxes from my browser with very good results. Unfortunately they only offer FAX enabled numbers in USA and Canada. A second choice is again Telnyx: they offer FAX enabled numbers all over the world. Unfortunately, they launched their faxing API very recently and for the moment it can only be used to send faxes and not to receive. I sent them a message urging them to add the receiving capability also.

The foundation of an application is enormously important: its goal, the phylosophy underpinning it, which should express respect for its users' freedom, what programming languages are used, the interaction between components, etc. Also, part of the foundation is the name of the application itself. So, please consider adopting a new name for your application from this early stage, because the name will be part of its success. All the good names are already taken and turned into registered trademarks. I had to face this truth when choosing names for my own applications and domain names. So I think a short artificial word that would include the word sip would sound very well: maybe **sipspace** or **sipzone** or **sipmeet** or **sipclip** or **sipship** or **sipzip** or **friendSIP** ?
