### ISSUE TITLE
Use SIP account without websocket

### ISSUE THREAD

**Issue by HoussemBrahem** [InnovateAsterisk/Browser-Phone#481]
Can i use this webphone with the SIP technology and not with PjSIP.

**Comment by InnovateAsterisk** [comment]
You seem to have ask two different questions here

> Use SIP account without websocket

No, this is not possible, the connection to the browser has to be established via secure websocket, and then regular SIP messages are transmitted over the websocket connection. Just remember, with this option, media packets are sent via encrypted UDP packets out side of the websocket connection.

> Can i use this webphone with the SIP technology and not with PjSIP.

Any compatible SIP library. Asterisk used to use `chan_sip` many years ago. This library used to work with this phone the last time i checked on around version 13. But it had some unfixable issues (mostly around video). The latest versions of Asterisk now use chan_pjsip, and appears to work fine. If you want you can even use Freeswitch, Kamailio and OpenSIPS. If its conforms to the SIP RFC/IETF, it will probably work.

**Comment by HoussemBrahem** [comment]
Thanks
