### ISSUE TITLE
setting for video calls in fullscreen

### ISSUE THREAD

**Issue by vieridipaola** [InnovateAsterisk/Browser-Phone#49]
Hi,

Another interesting improvement would be to add yet another setting via setItem to decide, upon user login, if video calls should start in fullscreen mode or not.
That would be useful for specific patient profiles calling in: they would receive a URL via SMS, they click and open Browser-Phone which identifies them as patients, auto-launch freedial to enter an Asteisk queue right away, and in fullscreen.
Simple and with a clean trimmed down UI for no-hassle patients.

**Comment by InnovateAsterisk** [comment]
Oh, I like that. Nice idea!

**Comment by InnovateAsterisk** [comment]
Video calls start in full screen (maximised), you can still use your own browsers "fullscreen" options after that.

There is a setting: StartVideoFullScreen to disable this. This feature may become a menu toggle
