### ISSUE TITLE
post js script and user agent

### ISSUE THREAD

**Issue by vieridipaola** [InnovateAsterisk/Browser-Phone#50]
Hi,

What is the best way to call custom code as soon as the user agent is ready and registered?

This is what I currently wrote in a custom js script loaded right after phone.js:

```
$(document).ready(function () {
    var onUserAgent = window.setInterval(function () {
        if ( userAgent != null && userAgent.isRegistered() == true ) {
            console.log("This clause should be called only once as soon as the user agent is ready.");
	    // do stuff...
            console.log('Removing setInterval');
            clearInterval(onUserAgent);
        }
    }, 4 * 1000);
});
```

However, I'm seeing the 2 console log messages twice instead of just once.
So, either clearInterval is not working as I expect it to, or I've misunderstood the whole logic.

**Comment by InnovateAsterisk** [comment]
This will be easier once the Web Hooks are in place - it will be then possible to tie into (or create) the onRegister event.

I’ll need a few days for this.

**Comment by InnovateAsterisk** [comment]
Done: 
https://github.com/InnovateAsterisk/Browser-Phone/commit/f55762937c02fd821e82c23f2b464b3a29ebab20
