### ISSUE TITLE
questionnaire on call hangup

### ISSUE THREAD

**Issue by vieridipaola** [InnovateAsterisk/Browser-Phone#53]
Hi,

I guess what I'm about to ask can be done once the web hooks are in place.

I have a specific use case:

1) a patient receives an SMS with a link to a Browser-Phone URL

2) patient clicks that link, and Browser-Phone auto-dials an Asterisk queue until a doctor picks the call up

3) once the call hangs up, I'd like to load/redirect the patient's page to another URL -- a questionnaire. 

So basically, "onCallHangup" would trigger loading another URL (effectively leaving the Browser-Phone page).

**Comment by InnovateAsterisk** [comment]
Yip, web hooks, coming soon.

**Comment by InnovateAsterisk** [comment]
Done: 
https://github.com/InnovateAsterisk/Browser-Phone/commit/f55762937c02fd821e82c23f2b464b3a29ebab20
