### ISSUE TITLE
sipjs version

### ISSUE THREAD

**Issue by vieridipaola** [InnovateAsterisk/Browser-Phone#55]
Hi,

Is there a reason why the sipjs library used in this project is 0.11.6 instead of the most recent 0.16.0?
Is it as simple as version bumping, or are there any known incompatibilities?

Vieri

**Comment by InnovateAsterisk** [comment]
I have not really tried the latest version, mainly because the current one did exactly what I needed, ill check their changelog, and see if it should be updated.
