### ISSUE TITLE
Error when configuring sip endpoint in zoiper

### ISSUE THREAD

**Issue by bp2468** [InnovateAsterisk/Browser-Phone#569]
Here is my sip.conf:

[general]

udpbindaddr=0.0.0.0:5060

context=from-outside
useragent=Raspberry Pi BPX
realm=bp214.erss.in
srvlookup=no
mohsuggest=default
parkinglot=default
allowguest=no
alwaysauthreject=yes
videosupport=no
maxcallbitrate=5120
ignoreregexpire=no

allowsubscribe=yes
notifyhold=yes
notifyringing=yes
callcounter=yes

progressinband=yes ; yes|no|never

tos_sip=af42
tos_audio=ef
cos_sip=3
cos_audio=5

rtptimeout=0
rtpkeepalive=60

jbenable=yes
jbforce=no
jbmaxsize=200
jbresyncthreshold=1000
jbimpl=fixed
jblog=no

tcpenable=no
tlsenable=no
websocket_enabled=yes
 encryption=no

deny=0.0.0.0/0.0.0.0
permit=10.0.0.0/255.0.0.0
permit=172.16.0.0/255.240.0.0
permit=192.168.0.0/255.255.0.0

accept_outofcall_message=yes
auth_message_requests=no
outofcall_message_context=textmessages

; == Templates

[basic](!)
type=friend
qualify=yes
context=from-extensions
subscribecontext=subscriptions
host=dynamic
directmedia=no
nat=force_rport,comedia
dtmfmode=rfc2833
disallow=all
videosupport=yes

[phones](!)
transport=udp
allow=ulaw,alaw,g722,gsm,vp9,vp8,h264

[webrtc](!)
transport=wss
allow=opus,ulaw,vp9,vp8,h264
encryption=yes
avpf=yes
force_avp=yes
icesupport=yes
rtcp_mux=yes
dtlsenable=yes
dtlsverify=fingerprint
dtlscertfile=/root/certs/asterisk.pem
dtlscafile=/root/ca/Asterisk-Root-CA.crt
dtlssetup=actpass

[100](basic,webrtc)
callerid="Conrad de Wet" <100>
secret=1234

[200](basic,webrtc)
callerid="User 2" <200>
secret=1234

[300](basic,phones)
callerid="300"
secret=1234
                       

when configuring the sip end point(300) in zoiper, I get the 401: Unauthorized error

**Comment by bp2468** [comment]
Unauthorized (code: 401)

**Comment by InnovateAsterisk** [comment]
What does the CLI show at the same time?

**Comment by bp2468** [comment]
WebSocket connection from '10.203.0.6:44238' closed
  == WebSocket connection from '10.203.0.6:58666' for protocol 'sip' accepted using version '13'

**Comment by bp2468** [comment]
However I'm able to configure the endpoint (100 and 200) successfully in web.

 Registered SIP '100' at 10.203.0.6:58172
       > Saved useragent "Browser Phone 0.3.20 (SIPJS - 0.20.0) Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36" for peer 100

**Comment by InnovateAsterisk** [comment]
> What does the CLI show at the same time?
> WebSocket connection from '10.203.0.6:44238' closed
> == WebSocket connection from '10.203.0.6:58666' for protocol 'sip' accepted using version '13'

Extension 300 is not a web socket extension - so you should not have this response.

**Comment by bp2468** [comment]
Entered the hostname,  username as 300 and password as 1234. Showing the error Registration timeout.

**Comment by bp2468** [comment]
Added
noload => res_pjsip.so
noload => res_pjsip_pubsub.so
noload => res_pjsip_session.so
noload => chan_pjsip.so
noload => res_pjsip_exten_state.so
noload => res_pjsip_log_forwarder.so
in /etc/modules.conf. It is working now.
