### ISSUE TITLE
no ringtone heard on incoming call

### ISSUE THREAD

**Issue by bp2468** [InnovateAsterisk/Browser-Phone#577]
Unable to play audio file. NotAllowedError: play() failed because the user didn't interact with the document first. This happens when browser phone is integrated with a react application.

**Comment by InnovateAsterisk** [comment]
Yes, as the message say, the agent must click or tap on the page. 

This is the default behaviour of the browser - its not an error, it's by design. You may be able to flip the flag on this in you r browser settings.

**Comment by bp2468** [comment]
**Solution in Edge:** Open edge://settings/content/mediaAutoplay and click Allow -> Add the required URL.

**Solution in Chrome:** Open chrome://settings/content/sound and add "Allow to play sound" to the required URL.
