### ISSUE TITLE
responsive design

### ISSUE THREAD

**Issue by bp2468** [InnovateAsterisk/Browser-Phone#578]
index.html page is responsive in tablet but not responsive in mobile phone. How to make it responsive in both the devices?

**Comment by bp2468** [comment]
In mobile, the size of the Browser phone appears in  small size and it needs to zoomed in by the user.

![WhatsApp Image 2024-12-20 at 13 05 26](https://github.com/user-attachments/assets/44b4d56d-4354-4b6c-aa33-188da22ae14c)

**Comment by bp2468** [comment]
Even responsive.html appears in small size.

**Comment by InnovateAsterisk** [comment]
You can adjust the viewport meta tag as you need.

> In mobile, the size of the Browser phone appears in small size and it needs to zoomed in by the user.

In this image, it looks like the phone is presented with j query ui. There is a window width and window height in the code that allows you to adjust the initial size. Also note that the window is resizable by default. Put your cursor near the bottom right of the window. However this would only be applicable with a mouse.

**Comment by bp2468** [comment]
Solution: Added the viewport meta tag:

meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no"
