### ISSUE TITLE
force language

### ISSUE THREAD

**Issue by vieridipaola** [InnovateAsterisk/Browser-Phone#63]
Hi,

Sometimes a traveling user may use another person's device or go to a cyber cafe or the likes...
Security aside, I think it could be useful to force the UI language via a setItem variable, especially if one is already forcing user authentication on the web site (I know beforehand the users' language preferences).

**Comment by InnovateAsterisk** [comment]
I thought the auto-detect was kinda nice, but I hear your point.
I'll make it a setting or a menu.

**Comment by InnovateAsterisk** [comment]
Done. You can use the Language db setting
