### ISSUE TITLE
user media: Firefox vs Chrome

### ISSUE THREAD

**Issue by vieridipaola** [InnovateAsterisk/Browser-Phone#64]
Hi,

I tested the latest github version, and there seems to be a difference between FF and Chrome when it comes to getting user media.

On a desktop I have some earphones connected but no webcam. Instead I use some kind of "virtual cam", eg. "screen-capture-recorder" which basically takes the screen as source.

If I open Browser-Phone with Chrome, all user media devices are properly detected.

However, with Firefox (68.5.0esr 64-bit) I get "Error getting User Media" (javascript popup message) even though I allow the virtual camera source, of course. This happens when I click on "configure Extension". Not only does the Audio & Video tab not show me the "camera" device, but even the speaker and microphone dropdowns are empty.

From the FF console log I get:
```
MediaStreamError
​
constraint: ""
​
message: "Failed to allocate videosource"
​
name: "NotReadableError"
​
stack: ""
​
<prototype>: MediaStreamErrorPrototype
​​
constraint: 
​​
message: 
​​
name: 
​​
stack: ""
​​
<get constraint()>: function constraint()
​​
<get message()>: function message()
​​
<get name()>: function name()
​​
<prototype>: Object { … }
phone.js:1232:25
    ConfigureExtensionWindow

```

**Comment by InnovateAsterisk** [comment]
I'm testing on 79.0. Are you able to update?
![image](https://user-images.githubusercontent.com/58937573/89533734-24f13100-d7f4-11ea-9405-980c5ae23057.png)

**Comment by vieridipaola** [comment]
Hi,

I need to use ESR, so I updated to 78.1.0esr (64-bit) which is the latest.
Still, I'm getting the exact same behavior.

I'll try a different source.

**Comment by InnovateAsterisk** [comment]
Found this:
https://stackoverflow.com/questions/42568498/notreadableerror-failed-to-allocate-videosource

**Comment by vieridipaola** [comment]
Yes, thanks, but unfortunately I am trying to use the virtual cam in Firefox before any other app (eg. Chrome). In other words, I still get the error if I reboot the PC and try to use the virtual camera right away with FF. No problem at all with Chrome.
I guess I'll have to try some other drivers.

**Comment by vieridipaola** [comment]
Closing this old issue. Thanks.
