### ISSUE TITLE
Date and time format

### ISSUE THREAD

**Issue by ogogon** [InnovateAsterisk/Browser-Phone#66]
If I understand correctly, now the program displays the date and time in a hard-coded American format.

In countries where dates and times are historically recorded in a different form, this causes a constant need to delve into and disassemble the unusual form of recording.

I guess it's not very difficult to teach a program to take this format from the localization of the browser.

Ogogon.

**Comment by InnovateAsterisk** [comment]
Nice suggestion! I'll make it a setting.

I have always has a preference to the date in "dd-mm-yyyy" format as it the easiest to read (for me anyway), so ill probably leave it as the default. For the moment there will be a db setting like all the others. Once im done with the settings UI there will be a dropdown.

**Comment by InnovateAsterisk** [comment]
https://en.wikipedia.org/wiki/Date_format_by_country

> The ISO 8601 format YYYY-MM-DD (2020-08-06) is intended to harmonize these formats and ensure accuracy in all situations. Many countries have adopted it as their sole official date format, though even in these areas writers may adopt abbreviated formats that are no longer recommended.

**Comment by ogogon** [comment]
In our country, and a number of neighboring countries, the twelve-hour time format has not been used for more than a hundred years.
Unfortunately, people perceive the "AM/PM" format very badly.
When in the early 90s of the last century foreign companies came to us with their software, they immediately made a conclusion of the time in the format HH:MM[:SS].

It is also customary to write the date in a different order.
In formal documents - DD.MM.YYYY, but in reality the generally accepted format is DD-Mon-YYYY, where month is a three-letter abbreviation.
Here are the russian abbreviations for the months in your localization format:
"shortmonth_jan": "Янв"
"shortmonth_feb": "Фев"
"shortmonth_mar": "Мар"
"shortmonth_apr": "Апр"
"shortmonth_may": "Май"
"shortmonth_jun": "Июн"
"shortmonth_jul": "Июл"
"shortmonth_aug": "Авг"
"shortmonth_sep": "Сен"
"shortmonth_oсt": "Окт"
"shortmonth_mov": "Ноя"
"shortmonth_dec": "Дек"

**Comment by InnovateAsterisk** [comment]
Moment supports multi-language, i have applied the `moment.locale(userLanguage);` call when the language is detected.

**Comment by ogogon** [comment]
Everything became noticeably better, but some moments remained.

In the left window, the date is still displayed in US format. Here's an example.
![Снимок экрана в 2020-08-09 06-22-36](https://user-images.githubusercontent.com/3341221/89724248-38c1b080-da09-11ea-8595-7b96d9efb459.png)
But I would like this - 09.08.2020 or 09-Авг-2020 г.

There is much more progress in the right window. Time is displayed in 24 hour format.
But there is a certain oddity, before the time is indicated not the date, but the day of the week. In my opinion, this is not very informative - you need to look for a calendar to set the date. Here's an example.
![Снимок экрана в 2020-08-09 06-21-49](https://user-images.githubusercontent.com/3341221/89724346-9a364f00-da0a-11ea-80e9-62c9f80d4c00.png)

**Comment by InnovateAsterisk** [comment]
This is by design. There is a condition for the data display. If the "last activity" was more than a day ago, it will display a date, otherwise it will display a time (the assumption then is date = today)
