### ISSUE TITLE
Device Error: No video / webcam devices found

### ISSUE THREAD

**Issue by ogogon** [InnovateAsterisk/Browser-Phone#67]
Every time I try to enter my account settings, I get a window with the text "Device Error. No video / webcam devices found, make sure one is plugged in.".

On the one hand, this is true. There are no "video/webcam devices" on my Mac mini.
On the other hand, there is no disaster in the absence of a video device. Moreover, since childhood I was raised to be humble and taught not to poke anyone with my non-photogenic physiognomy.

I believe that there should be a setting that tells the program that I do not have a video device and trying to search for it is obviously pointless.

In my opinion, in the section "Audio and Video", in the all drop-down menus with lists of devices, there should be a choice "None". 

Ogogon.

**Comment by InnovateAsterisk** [comment]
True

**Comment by InnovateAsterisk** [comment]
Done. 
It will have an option for "(Default)" if there are other devices, if not then the dropdown will just be empty. It easily skips over any video device if there are problems with the camera - like it's been unplugged.
