### ISSUE TITLE
Button "Send": Non-localizable element

### ISSUE THREAD

**Issue by ogogon** [InnovateAsterisk/Browser-Phone#73]
Apparently, there is no localization mechanism for the "Send" button.
To better understand what is at stake - here is a photo.
![Снимок экрана в 2020-08-10 17-26-05](https://user-images.githubusercontent.com/3341221/89794397-a9fb8380-db2f-11ea-81b4-c8a3b06290f8.png)
![Снимок экрана в 2020-08-10 17-24-25](https://user-images.githubusercontent.com/3341221/89794410-ad8f0a80-db2f-11ea-91f2-28f47263f03e.png)

If you hover over the button with the mouse, then the English text "Send" pops up and in the file "ru.json" I didn't find a field for this button.

I suppose we need to create a localization mechanism for this button.

**Comment by InnovateAsterisk** [comment]
Will do.
