### ISSUE TITLE
support for Edge browser

### ISSUE THREAD

**Issue by vieridipaola** [InnovateAsterisk/Browser-Phone#82]
Hi,

Browser-Phone officially supports Edge according to the README. However, I'm getting several errors in the console. The first one is that it expects a closing ')' in this function instead of '=':

`function formatBytes(bytes, decimals=2) {`

(phone.js)

The next error I'm getting in the console is:

`jQuery.Deferred exception: 'localDB' is undefined ReferenceError: 'localDB' is undefined`

This is because I'm calling localDB in a js "post" script (ie. a custom js included right after phone.js in my Browser-Phone HTML page) within a "success" function of an ajax call.
Sure, I could use 'window.localStorage' instead to solve the localDB issue, but I'd have similar errors with other calls to functions defined in phone.js.

The browsers I usually use are Firefox and Chrome -- no problems of this type there.
Any ideas why I'm getting these errors in Edge?

**Comment by InnovateAsterisk** [comment]
Strange, im in Version 81.0.416.58 (Official build) (64-bit), and i don't get the `formatBytes` error.

I have an update, and will test more with the script block isolation issue.

**Comment by vieridipaola** [comment]
It's an Edge version issue. Closing...
