### ISSUE TITLE
new web hook on transport error

### ISSUE THREAD

**Issue by vieridipaola** [InnovateAsterisk/Browser-Phone#84]
Hi,

I find it useful to have a custom web hook when there's a web socket error.

Trivial patch:

[phone.js.patch.txt](https://github.com/InnovateAsterisk/Browser-Phone/files/5141264/phone.js.patch.txt)

**Comment by InnovateAsterisk** [comment]
SIPJS don't actually have an "descriptive error" parameter for transport, so although this web hook was added the only useful parameters to parse along are the transport objet and the userAgent object.
