### ISSUE TITLE
missing reasonCode

### ISSUE THREAD

**Issue by vieridipaola** [InnovateAsterisk/Browser-Phone#85]
Hi,

In function teardownSession, there is a call to a custom web hook (on terminate) and the session object is passed. However, I am unable to find the reason for which the call was terminated (statusCode and reasonPhrase are always undefined). 

On the other hand, if I pass reasonCode and reasonText to the custom web hook function call from within  function teardownSession, I can then properly have the SIP code with which the call has been terminated.

So, can this be included?

eg.:
`if(typeof web_hook_on_terminate !== 'undefined') web_hook_on_terminate(session, reasonCode, reasonText);`

**Comment by InnovateAsterisk** [comment]
The reasonCode and the reasonText are now added to the session.data so can be picked up in the session object passed to the web hook
