### ISSUE TITLE
playing and stopping early media audio

### ISSUE THREAD

**Issue by vieridipaola** [InnovateAsterisk/Browser-Phone#89]
Hi,

I thought this was discussed earlier, but I couldn't find the issue here. Sorry if I double post.

It seems that the "early media" audio files are not properly stopped in certain conditions. I've yet to properly identify these conditions.
However, at a first glance I see that to stop playing the audio files, the following code is used:

```
    if(session.data.earlyMedia){
        session.data.earlyMedia.pause();
        session.data.earlyMedia = null;
    }
```

Some posts in other forums suggest doing things like:

```
session.data.earlyMedia.currentTime = 0; 
session.data.earlyMedia.src = ''; 
```

right after .pause().

I will do some testing, but I was wondering if anyone else has had early media audio playing "forever" even after terminating a call (the only solution to actually stop the audio being a page reload).

**Comment by vieridipaola** [comment]
Whenever I get this issue, I hear the Tone_EarlyMedia-US.mp3 file play endlessly, when the call is answered/accepted and also when the whole call session is torn down.

From the console log I can check that the code in the following section is run at a given time:

```
    session.on('accepted', function (data) {

        if(session.data.earlyMedia){
            session.data.earlyMedia.pause();
            session.data.earlyMedia = null;
        }
```

However, oddly enough AFTER running the above this other part of the code is run (last line below):

```
session.on('progress', function (response) {
        // Provisional 1xx
        if(response.status_code == 100){
            $(MessageObjId).html(lang.trying);
        } else if(response.status_code == 180){
            $(MessageObjId).html(lang.ringing);

            var soundFile = audioBlobs.EarlyMedia_European;
            if(UserLocale().indexOf("us") > -1) soundFile = audioBlobs.EarlyMedia_US;
            if(UserLocale().indexOf("gb") > -1) soundFile = audioBlobs.EarlyMedia_UK;
            if(UserLocale().indexOf("au") > -1) soundFile = audioBlobs.EarlyMedia_Australia;
            if(UserLocale().indexOf("jp") > -1) soundFile = audioBlobs.EarlyMedia_Japan;

            // Play Early Media
            console.log("Audio:", soundFile.url);
            var earlyMedia = new Audio(soundFile.blob);
            earlyMedia.preload = "auto";
            earlyMedia.loop = true;
            console.log("DEBUG: AUDIO PLAY: preload and loop");
            earlyMedia.oncanplaythrough = function(e) {
                if (typeof earlyMedia.sinkId !== 'undefined' && getAudioOutputID() != "default") {
                    earlyMedia.setSinkId(getAudioOutputID()).then(function() {
                        console.log("Set sinkId to:", getAudioOutputID());
                    }).catch(function(e){
                        console.warn("Failed not apply setSinkId.", e);
                    });
                }
                earlyMedia.play().then(function(){
                    // Audio Is Playing
```

So this seems to indicate that the oncanplaythrough method which calls the play() method on the audio file is run *after* the pause() method, effectively playing the sound file again.

Funny thing though is that if I repeat the same calling actions I do NOT always get the same behavior. Sometimes, the pause() method is fired up after play() in oncanplaythrough which means that the sound file is properly silenced.

Something else I've noticed is that I never reach the last line of this code snippet (both "Mixed Tracks" and "Stop any Early Media" sections are not run):

```
function teardownSession(lineObj, reasonCode, reasonText) {
    if(lineObj == null || lineObj.SipSession == null) return;

    var session = lineObj.SipSession;
    if(session.data.teardownComplete == true) return;
    session.data.teardownComplete = true; // Run this code only once

    // Call UI
    HidePopup();

    // End any child calls
    if(session.data.childsession){
        try{
            if(session.data.childsession.status == SIP.Session.C.STATUS_CONFIRMED){
                session.data.childsession.bye();
            }
            else{
                session.data.childsession.cancel();
            }
        } catch(e){}
    }
    session.data.childsession = null;

    // Mixed Tracks
    if(session.data.AudioSourceTrack && session.data.AudioSourceTrack.kind == "audio"){
        session.data.AudioSourceTrack.stop();
        session.data.AudioSourceTrack = null;
    }
    // Stop any Early Media
    if(session.data.earlyMedia){
        session.data.earlyMedia.pause();
        session.data.earlyMedia = null;
    }
```

So, I gave it another shot by adding the following line to the session.on 'accepted' function right after session.data.earlyMedia.pause():

`session.data.earlyMedia.src = '';`

This way, even if oncanplaythrough is fired after the audio file was "paused" then it simply won't be able to play it again. There's a warning on the console about it, but code execution proceeds as usual.

I realize it might be an ugly hack, but it "works for me".

Thanks

**Comment by vieridipaola** [comment]
By the way, I also noticed another artifact that can happen sometimes -- the ringer for INCOMING calls does not stop even if the call has been cancelled.

So here's a quick fix that seems to work for me (I added the "Stop the ringtone" section below within function ReceiveCall):

```
    // Inbound You or They Rejected
    session.on('rejected', function (response, cause) {
        console.log("Call rejected: " + cause);

        // Stop the ringtone
        if(session.data.rinngerObj){
            session.data.rinngerObj.pause();
            session.data.rinngerObj.src = '';
            session.data.rinngerObj = null;
        }

        AddCallMessage(buddy, session, response.status_code, cause);

        // Custom Web hook
        if(typeof web_hook_on_terminate !== 'undefined') web_hook_on_terminate(session, response.status_code, cause);
    });


```

**Comment by InnovateAsterisk** [comment]
Nice find, thank you. 
This happened to me, and my approach was to ensure the the media was always immediately available, thinking that if the file was ready to play it would do so right away, and it could also be stopped. This seems to only have solved the issue that sometimes the audio files don't play quick enough because of slow internet.

**Comment by InnovateAsterisk** [comment]
Maybe there can be a default silence.mp3 that gets loaded, this way the script would not error out.

**Comment by InnovateAsterisk** [comment]
I see the correct way to do this is: 
```
            session.data.rinngerObj.pause();
            session.data.rinngerObj.removeAttribute('src');
            session.data.rinngerObj.load();
            session.data.rinngerObj = null;
```
