### ISSUE TITLE
presence message not for you

### ISSUE THREAD

**Issue by vhatzist** [InnovateAsterisk/Browser-Phone#98]
Hello,

We've been testing the Browser-Phone with our SIP server and while registrations and subscriptions seem to work fine, whenever the Browser-Phone receives a NOTIFY we see the message "presence message not for you" in the browser console. As is expected, the button for the monitored phone on the browser-phone's web page does not change colors or do anything.

I have attached a file with 

- the logs from the registration, subscription and an initial notify that is received 

and 

- another log file from when a monitored phone was in a call and browser-phone received 3 NOTIFYs (for ringing, answer and hangup events). 

The actual host name and IP address of our SIP server was removed from the logs for security reasons.

If you need more detailed logs could you please let us know how to increase the verbosity?

Thank you in advance. 

[registration_subscription_notify.txt](https://github.com/InnovateAsterisk/Browser-Phone/files/5294234/registration_subscription_notify.txt)
[notify_ringing_answer_hangup.txt](https://github.com/InnovateAsterisk/Browser-Phone/files/5294235/notify_ringing_answer_hangup.txt)

**Comment by InnovateAsterisk** [comment]
I was wondering if this was going to come up.

So the way the code works is that it will check the entity node or the contact tuple. (Both fields are required by the RFC: https://tools.ietf.org/html/rfc3863). Things get a bit muddy about why and what for etc etc. The way I used it was to check that the user portion of URI matched to the SIP username of your current registered account. In other words, it asks the question "is this message for you?"

> "The <presence> element MUST have an 'entity' attribute.  The value of the 'entity' attribute is the 'pres' URL of the PRESENTITY publishing this presence document."

and PRESENTITY is:

> the source of the PRESENCE INFORMATION

My observation in Asterisk 13 and 16 on both chan_sip and pjsip was that it seemed to be a mixed bag... in some version it was using the entity node to describe the destination of the presence message... hence the either or code. It seemed to be either the entity node or the Contact field of the tuple node. But the subject of the presence was consistently the tuple id field.

```
        var xml = $($.parseXML(notification.request.body));

        var Entity = xml.find("presence").attr("entity");
        var Contact = xml.find("presence").find("tuple").find("contact").text();
        if (SipUsername == Entity.split("@")[0].split(":")[1] || SipUsername == Contact.split("@")[0].split(":")[1]){
            // Message is for you.
        } 
        else {
            console.warn("presence message not for you.", xml);
            return;
        }
```

See if you can send the presence xml that is parsed along to the console.warn (second parameter). What you sent seems incomplete (you sent only the first line of the presence xml).

`<presence ... entity="sip:1127976@host.removed.for.security.reasons">`

It's probably fine to take this test out... or at least the "return". But, I would be interested to know what your presence xml looks like, what the Sip Username is, and how to have setup your `hint` lines line the asterisk dialplan/config

**Comment by vhatzist** [comment]
Hello,

I have attached the complete NOTIFY messages that are sent to the browser-phone for the ringing, answer and hangup states. In this case the browser phone (tuple id 1127975) is receiving updates for that status of the monitored phone 1127976 (entity). 

[ringing.txt](https://github.com/InnovateAsterisk/Browser-Phone/files/5306978/ringing.txt)
[answer.txt](https://github.com/InnovateAsterisk/Browser-Phone/files/5306979/answer.txt)
[hangup.txt](https://github.com/InnovateAsterisk/Browser-Phone/files/5306980/hangup.txt)

**Comment by vhatzist** [comment]
Hi Conrad,

Did you find the time to look into the debug info I posted?

**Comment by InnovateAsterisk** [comment]
Yes, In the next update, the ```return;``` is removed, so it just stays as warning.

**Comment by vhatzist** [comment]
Thank you Conrad, indeed it is a warning now, but how can I make Browser-Phone understand that the Presence messages **are** actually for it?

**Comment by vhatzist** [comment]
Hi Conrad, is there an update on this please?

**Comment by InnovateAsterisk** [comment]
This update is in my next release, but... i'm busy with XMPP integration and this is a major release, so any code changes, and i'm still busy with it, I would anticipate end of first quarter 2021. 

COVID has really messed me around this year, so things have been a little slow!

The XMPP will not be on by default, so it will still work exactly as it did before - with this and a few other fixes.

**Comment by vhatzist** [comment]
Thank you for the update, Conrad!

I understand, COVID-19 has been tough on us all. I'll be looking forward for the next update.

Stay safe!

**Comment by vhatzist** [comment]
Hi Conrad,

I hope everything is well, is there an update on the upcoming new commit?

**Comment by xgs-spain** [comment]
In case someone have problems with this, in my case although  SipUsername was not present in Entity or Contact, it was in the To header, so instead of bypassing the check completely i went with:

var To = notification.request.headers.To[0].raw;
if (SipUsername == Entity.split("@")[0].split(":")[1] || SipUsername == Contact.split("@")[0].split(":")[1] || SipUsername==To.split("@")[0].split(":")[1]){

**Comment by InnovateAsterisk** [comment]
https://github.com/InnovateAsterisk/Browser-Phone/commit/7a6dd82a1bf69c84a11e9a41236b07819d2b6128

This version removes the ```return;```.
