### ISSUE TITLE
SIP MESSAGE (SMS) not accepted

### ISSUE THREAD

**Issue by vhatzist** [InnovateAsterisk/Browser-Phone#99]
Hello,

This may be related to issue #98 . When the browser-phone receives a SIP MESSAGE it is not displayed, and we see in the browser console:

New Incoming Message! "" <1127976>

where 1127976 is the sender of the message.

Attached is the SIP MESSAGE that is received.

Any assistance would be appreciated.
[sip message.txt](https://github.com/InnovateAsterisk/Browser-Phone/files/5307192/sip.message.txt)

**Comment by InnovateAsterisk** [comment]
There is a variable called "DidLength"

```
var DidLength = parseInt(getDbItem("DidLength", 6));                 // DID length from which to decide if an incoming caller is a "contact" or an "extension". 
```

Text messages check this length. This application assumes only internal extension (short numbers) can send each other text messages. 

You should set the length DB Item DidLength to 7, as you seem to be using 7 digit local extensions.

**Comment by vhatzist** [comment]
Thank you Conrad,

I'll look into this more, we'd be interested in a variable length extension number, I'll see whether this is possible to do with minor modifications.

**Comment by vhatzist** [comment]
Hi Conrad, editing DidLength as you recommended worked fine. Although we'd be interested in a variable length extension number we can close this issue.
